<?php $presets["skin16r"] = array (
  'preset' => 'skin16r',
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin16r.header-logo-regular.png?w=216&h=133',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin16r.header-logo-hd.png?w=432&h=266',
    1 => 0,
  ),
  'bottom_bar-logo_regular' => 
  array (
    0 => '',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '',
    1 => 0,
  ),
  'general-floating_menu_show_logo' => '1',
  'general-floating_menu_logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin17b.general-floating-menu-logo-regular.png?w=25&h=40',
    1 => 0,
  ),
  'general-floating_menu_logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin17r.general-floating-menu-logo-hd.png?w=50&h=80',
    1 => 0,
  ),
  'general-bg_color' => '#ffffff',
  'general-bg_opacity' => 100,
  'general-bg_ie_color' => '#252525',
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-content_width' => '1250px',
  'general-layout' => 'wide',
  'general-box_width' => '1280px',
  'general-boxed_bg_color' => '#ffffff',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin16r.general-boxed-bg-image.jpg',
    'repeat' => 'no-repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-show_titles' => '1',
  'general-title_align' => 'left',
  'general-show_breadcrumbs' => '1',
  'general-responsive' => '1',
  'general-hd_images' => 'srcset_based',
  'general-accent_bg_color' => '#88cccf',
  'general-border_radius' => 3,
  'general-thick_divider_style' => 'style-5',
  'general-thin_divider_style' => 'style-1',
  'general-custom_css' => '',
  'general-show_rel_posts' => '1',
  'general-rel_posts_head_title' => 'Related posts',
  'general-rel_posts_max' => 6,
  'general-rel_projects_meta' => '1',
  'general-blog_meta_postformat' => '1',
  'general-smooth_scroll' => 'off',
  'fonts-font_family' => 'Open Sans',
  'fonts-normal_size' => 14,
  'fonts-normal_size_line_height' => 24,
  'fonts-small_size' => 12,
  'fonts-small_size_line_height' => 22,
  'fonts-big_size' => 14,
  'fonts-big_size_line_height' => 24,
  'fonts-h1_font_family' => 'Roboto Slab',
  'fonts-h1_font_size' => 47,
  'fonts-h1_line_height' => 53,
  'fonts-h1_uppercase' => false,
  'fonts-h2_font_family' => 'Roboto Slab',
  'fonts-h2_font_size' => 35,
  'fonts-h2_line_height' => 41,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Roboto Slab',
  'fonts-h3_font_size' => 25,
  'fonts-h3_line_height' => 31,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Roboto Slab',
  'fonts-h4_font_size' => 19,
  'fonts-h4_line_height' => 25,
  'fonts-h4_uppercase' => false,
  'fonts-h5_font_family' => 'Roboto Slab',
  'fonts-h5_font_size' => 17,
  'fonts-h5_line_height' => 25,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Roboto Slab',
  'fonts-h6_font_size' => 15,
  'fonts-h6_line_height' => 25,
  'fonts-h6_uppercase' => false,
  'buttons-s_font_family' => 'Open Sans:600',
  'buttons-s_font_size' => 12,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 30,
  'buttons-m_font_family' => 'Open Sans:600',
  'buttons-m_font_size' => 14,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 38,
  'buttons-l_font_family' => 'Open Sans:600',
  'buttons-l_font_size' => 16,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 48,
  'top_bar-show' => '1',
  'top_bar-bg_color' => '#282828',
  'top_bar-bg_opacity' => 100,
  'top_bar-bg_ie_color' => '#ffffff',
  'top_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text_color' => '#ffffff',
  'top_bar-dividers_color' => '#dedfdf',
  'top_bar-dividers_opacity' => 100,
  'top_bar-dividers_ie_color' => '#dadee1',
  'top_bar-contact_show' => '1',
  'top_bar-contact_address' => '102580 Santa Monica BLVD Los Angeles',
  'top_bar-contact_phone' => '+3 045 224 33 12',
  'top_bar-contact_email' => 'info@yoursite.com',
  'top_bar-contact_skype' => 'yourname',
  'top_bar-contact_clock' => '10 AM - 8 PM',
  'top_bar-contact_info' => '',
  'top_bar-text' => '',
  'top_bar-soc_icon_color' => '#767d80',
  'top_bar-soc_icon_hover' => 'default',
  'top_bar-soc_icon_hover_color' => '#2a83ed',
  'top_bar-soc_ico_facebook' => 'https://www.facebook.com/WordPress.Premium.Theme',
  'top_bar-soc_ico_twitter' => 'https://twitter.com/premium_theme',
  'top_bar-soc_ico_google' => '',
  'top_bar-soc_ico_dribbble' => 'http://dribbble.com/dream-theme',
  'top_bar-soc_ico_you-tube' => '',
  'top_bar-soc_ico_rss' => '',
  'top_bar-soc_ico_delicious' => '',
  'top_bar-soc_ico_flickr' => '',
  'top_bar-soc_ico_forrst' => '',
  'top_bar-soc_ico_lastfm' => '',
  'top_bar-soc_ico_linkedin' => '',
  'top_bar-soc_ico_vimeo' => '',
  'top_bar-soc_ico_tumbler' => '',
  'top_bar-soc_ico_pinterest' => 'http://www.pinterest.com/dreamtheme/boards/',
  'top_bar-soc_ico_devian' => '',
  'top_bar-soc_ico_skype' => '',
  'top_bar-soc_ico_github' => '',
  'top_bar-soc_ico_instagram' => 'http://instagram.com/dream_theme_photo',
  'top_bar-soc_ico_stumbleupon' => '',
  'top_bar-soc_ico_behance' => '',
  'top_bar-soc_ico_mail' => '',
  'top_bar-soc_ico_website' => '',
  'top_bar-soc_ico_px-500' => '',
  'top_bar-soc_ico_tripedvisor' => '',
  'top_bar-soc_ico_vk' => '',
  'top_bar-soc_ico_foursquare' => '',
  'top_bar-soc_ico_xing' => '',
  'header-bg_color' => '#ffffff',
  'header-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'header-transparent_bg_color' => '#ffffff',
  'header-transparent_bg_opacity' => 100,
  'header-transparent_bg_ie_color' => '#000000',
  'header-transparent_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-bg_height' => 60,
  'header-layout' => 'side',
  'header-contentarea' => '<p><span class="paint-accent-color">Address:</span>  102580 Santa Monica BLVD Los Angeles
</p>
<span class="paint-accent-color">Phone: </span> +3 045 224 33 12, 220 30 22',
  'header-contentarea_color' => '#373a41',
  'header-font_family' => 'Open Sans',
  'header-font_size' => 16,
  'header-font_uppercase' => false,
  'header-font_line_height' => 34,
  'header-font_color' => '#474950',
  'header-menu_bg_color' => '#6a6e71',
  'header-menu_bg_opacity' => 18,
  'header-menu_bg_ie_color' => '#dadee1',
  'header-color_frame' => '1',
  'header-next_level_indicator' => '1',
  'header-icons_size' => 
  array (
    'width' => 14,
    'height' => 14,
  ),
  'header-submenu_parent_clickable' => false,
  'header-submenu_color' => '#373a41',
  'header-submenu_bg_color' => '#ffffff',
  'header-submenu_bg_opacity' => 97,
  'header-submenu_bg_ie_color' => '#ffffff',
  'header-submenu_next_level_indicator' => '1',
  'header-submenu_icons_size' => 
  array (
    'width' => 12,
    'height' => 12,
  ),
  'header-show_floating_menu' => '1',
  'header-search_show' => '1',
  'slideshow-bg_color' => '#f7f7f8',
  'slideshow-bg_opacity' => 100,
  'slideshow-bg_ie_color' => '#ffffff',
  'slideshow-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'slideshow-bg_fullscreen' => false,
  'content-headers_color' => '#3a3a3a',
  'content-primary_text_color' => '#888888',
  'content-dividers_color' => '#dadee1',
  'content-dividers_opacity' => 100,
  'content-dividers_ie_color' => '#dadee1',
  'stripes-stripe_1_color' => '#f5f5f5',
  'stripes-stripe_1_opacity' => 100,
  'stripes-stripe_1_ie_color' => '#f7f7f8',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin16r.stripes-stripe-1-bg-image.gif',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#3a3a3a',
  'stripes-stripe_1_text_color' => '#888888',
  'stripes-stripe_1_div_color' => '#dadee1',
  'stripes-stripe_1_div_opacity' => 100,
  'stripes-stripe_1_div_ie_color' => '#dadee1',
  'stripes-stripe_2_color' => '#2b2b2b',
  'stripes-stripe_2_opacity' => 100,
  'stripes-stripe_2_ie_color' => '#f7f7f8',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin16r.stripes-stripe-2-bg-image.gif',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_headers_color' => '#eeeeee',
  'stripes-stripe_2_text_color' => '#a5a5a5',
  'stripes-stripe_2_div_color' => '#2e383c',
  'stripes-stripe_2_div_opacity' => 100,
  'stripes-stripe_2_div_ie_color' => '#dadee1',
  'stripes-stripe_3_color' => '#d1f0f2',
  'stripes-stripe_3_opacity' => 100,
  'stripes-stripe_3_ie_color' => '#cacaca',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin16r.stripes-stripe-3-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_headers_color' => '#3a3a3a',
  'stripes-stripe_3_text_color' => '#3a3a3a',
  'stripes-stripe_3_div_color' => '#ffffff',
  'stripes-stripe_3_div_opacity' => 12,
  'stripes-stripe_3_div_ie_color' => '#afc5d2',
  'sidebar-bg_color' => '#f6f6f6',
  'sidebar-bg_opacity' => 100,
  'sidebar-bg_ie_color' => '#ffffff',
  'sidebar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'sidebar-dividers_color' => '#81d742',
  'sidebar-dividers_opacity' => 100,
  'sidebar-dividers_ie_color' => '#dadee1',
  'sidebar-headers_color' => '#3a3a3a',
  'sidebar-primary_text_color' => '#888888',
  'footer-bg_color' => '#f5f5f5',
  'footer-bg_opacity' => 100,
  'footer-bg_ie_color' => '#1B1B1B',
  'footer-bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin16r.footer-bg-image.gif',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-dividers_color' => '#dadee1',
  'footer-dividers_opacity' => 0,
  'footer-dividers_ie_color' => '#dadee1',
  'footer-headers_color' => '#3a3a3a',
  'footer-primary_text_color' => '#888888',
  'bottom_bar-bg_color' => '#ffffff',
  'bottom_bar-bg_opacity' => 0,
  'bottom_bar-bg_ie_color' => '#ffffff',
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#888888',
  'bottom_bar-dividers_color' => '#dadee1',
  'bottom_bar-dividers_opacity' => 85,
  'bottom_bar-dividers_ie_color' => '#dadee1',
  'bottom_bar-credits' => '1',
  'hoover-color' => '#ff4f89',
  'hoover-opacity' => 58,
  'hoover-style' => 'blur',
  'top_bar-soc_ico_weibo' => '',
  'general-woocommerce_show_mini_cart_in_top_bar' => '1',
  'top_bar-font_size' => 'small',
  'top_bar-padding' => '',
  'top_bar-bg_mode' => 'solid',
  'menu-font_family' => 'Roboto:500',
  'menu-font_size' => 17,
  'menu-font_uppercase' => '1',
  'menu-next_level_indicator' => false,
  'menu-font_color' => '#3a3a3a',
  'menu-hover_font_color_mode' => 'color',
  'menu-hover_font_color' => '#3a3a3a',
  'menu-hover_font_color_gradient' => 
  array (
    0 => '#dd3333',
    1 => '#0ce6ab',
  ),
  'menu-decoration_style' => 'underline',
  'menu-hover_decoration_color_mode' => 'accent',
  'menu-hover_decoration_color' => '#a7e673',
  'menu-hover_decoration_color_gradient' => 
  array (
    0 => '#eeee22',
    1 => '#0bed56',
  ),
  'top_bar-paddings' => 8,
  'menu-iconfont_size' => 14,
  'menu-images_size' => 
  array (
    'width' => 14,
    'height' => 14,
  ),
  'menu-items_distance' => 26,
  'menu-bg_mode' => 'fullwidth_line',
  'menu-bg_color' => '#8224e3',
  'menu-top_bottom_paddings' => 10,
  'submenu-font_family' => 'Roboto:500',
  'submenu-font_size' => 12,
  'submenu-font_uppercase' => '1',
  'submenu-next_level_indicator' => '1',
  'submenu-font_color' => '#3a3a3a',
  'submenu-hover_font_color_mode' => 'accent',
  'submenu-hover_font_color' => '#895cb8',
  'submenu-hover_font_color_gradient' => 
  array (
    0 => '#81d742',
    1 => '#eeee22',
  ),
  'submenu-iconfont_size' => 12,
  'submenu-images_size' => 
  array (
    'width' => 14,
    'height' => 14,
  ),
  'submenu-items_distance' => 18,
  'submenu-bg_color' => '#ffffff',
  'submenu-bg_opacity' => 97,
  'submenu-bg_width' => 250,
  'submenu-parent_clickable' => false,
  'general-accent_color_mode' => 'color',
  'general-accent_bg_color_gradient' => 
  array (
    0 => '#2578e9',
    1 => '#3fe7d9',
  ),
  'header-left_layout_elements' => 
  array (
    'top_bar_left' => 
    array (
      0 => 'email',
      1 => 'phone',
      2 => 'skype',
    ),
    'top_bar_right' => 
    array (
      0 => 'cart',
      1 => 'login',
      2 => 'social_icons',
    ),
    'nav_area' => 
    array (
      0 => 'search',
    ),
  ),
  'header-center_layout_elements' => 
  array (
    'top_bar_left' => 
    array (
      0 => 'email',
      1 => 'phone',
      2 => 'skype',
    ),
    'nav_area' => 
    array (
      0 => 'social_icons',
      1 => 'cart',
      2 => 'search',
    ),
  ),
  'header-near_logo_font_size' => 'big',
  'header-near_logo_bg_color' => '#3a3a3a',
  'header-classic_layout_elements' => 
  array (
    'top_bar_left' => 
    array (
      0 => 'custom_menu',
    ),
    'top_bar_right' => 
    array (
      0 => 'cart',
      1 => 'login',
    ),
    'logo_area' => 
    array (
      0 => 'address',
      1 => 'phone',
      2 => 'social_icons',
    ),
    'nav_area' => 
    array (
      0 => 'search',
    ),
  ),
  'header-side_paddings' => 40,
  'header-side_position' => 'left',
  'header-side_menu_align' => 'left',
  'header-side_layout_elements' => 
  array (
    'top' => 
    array (
      0 => 'phone',
      1 => 'custom_menu',
    ),
    'bottom' => 
    array (
      0 => 'social_icons',
      1 => 'text_area',
      2 => 'cart',
      3 => 'search',
    ),
  ),
  'header-woocommerce_cart_icon' => '1',
  'header-search_icon' => '1',
  'header-search_caption' => 'Search',
  'header-contact_address' => '8500 Beverly Boulevard Los Angeles, CA 90048',
  'header-contact_address_icon' => '1',
  'header-contact_phone' => '(424) 123-0045',
  'header-contact_phone_icon' => '1',
  'header-contact_email' => 'sales@yoursite.com',
  'header-contact_email_icon' => '1',
  'header-contact_skype' => 'Your_Skype',
  'header-contact_skype_icon' => '1',
  'header-contact_clock' => 'Mon. – Fri. 10 AM – 8 PM',
  'header-contact_clock_icon' => '1',
  'header-contact_info' => '',
  'header-contact_info_icon' => '1',
  'header-text' => 'The7 will become a reliable foundation for your new website!',
  'header-left_layout_fullwidth' => false,
  'header-woocommerce_cart_caption' => 'Cart',
  'header-woocommerce_counter_bg_mode' => 'accent',
  'header-woocommerce_counter_bg_color' => '#6aa1ec',
  'header-woocommerce_counter_bg_color_gradient' => 
  array (
    0 => '#dd3333',
    1 => '#81d742',
  ),
  'header-login_icon' => '1',
  'header-login_caption' => 'Login',
  'header-soc_icon_color' => '#3a3a3a',
  'header-soc_icon_hover_mode' => 'color',
  'header-soc_icon_hover_color' => '#ffffff',
  'header-soc_icon_color_gradient' => 
  array (
    0 => '#81d742',
    1 => '#000000',
  ),
  'header-soc_icons' => 
  array (
    3 => 
    array (
      'icon' => 'pinterest',
      'url' => 'http://www.pinterest.com/dreamtheme/',
    ),
    1 => 
    array (
      'icon' => 'facebook',
      'url' => 'https://www.facebook.com/WordPress.Premium.Theme',
    ),
    2 => 
    array (
      'icon' => 'twitter',
      'url' => 'https://twitter.com/premium_theme',
    ),
    4 => 
    array (
      'icon' => 'instagram',
      'url' => 'http://instagram.com/dream_theme_photo',
    ),
  ),
  'header-logo_padding_top' => 36,
  'header-logo_padding_bottom' => 36,
  'header-soc_icon_hover_color_mode' => 'color',
  'float_menu-height' => 70,
  'float_menu-transparency' => 100,
  'header-side_menu_width' => '280px',
  'header-side_menu_lines' => '0',
  'header-side_menu_lines_color' => '#eeeeee',
  'header-left_menu_bg_mode' => 'content_line',
  'header-left_menu_bg_color' => '#ffffff',
  'header-classic_menu_bg_mode' => 'fullwidth_line',
  'header-classic_menu_bg_color' => '#dcdcdc',
  'header-center_menu_bg_mode' => 'content_line',
  'header-center_menu_bg_color' => '#ededed',
  'header-soc_icon_bg_color_mode' => 'color',
  'header-soc_icon_bg_color' => '#ffffff',
  'header-soc_icon_bg_color_gradient' => 
  array (
    0 => '#8224e3',
    1 => '#43d8c7',
  ),
  'header-soc_icon_hover_bg_color_mode' => 'accent',
  'header-soc_icon_hover_bg_color' => '#ededed',
  'header-soc_icon_hover_bg_color_gradient' => 
  array (
    0 => '#ef5689',
    1 => '#a6ff16',
  ),
  'general-title_size' => 'h2',
  'general-title_height' => 130,
  'general-title_bg_mode' => 'background',
  'general-title_bg_color' => '#f5f5f5',
  'general-breadcrumbs_color' => '#3a3a3a',
  'general-breadcrumbs_bg_color' => 'disabled',
  'general-title_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin16r.general-title-bg-image.gif',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'general-title_bg_fullscreen' => false,
  'general-title_bg_fixed' => false,
  'general-title_bg_parallax' => '',
  'buttons-style' => '3d',
  'buttons-color_mode' => 'accent',
  'buttons-color' => '#81d742',
  'buttons-color_gradient' => 
  array (
    0 => '#dd3333',
    1 => '#3a892a',
  ),
  'buttons-s_border_radius' => 3,
  'buttons-m_border_radius' => 3,
  'buttons-l_border_radius' => 3,
  'general-style' => 'ios7',
  'general-title_color' => '#3a3a3a',
  'general-post_type_portfolio_slug' => 'project',
  'general-rel_projects_appearance' => 'slider',
  'image_hover-style' => 'none',
  'image_hover-color_mode' => 'color',
  'image_hover-color' => '#292929',
  'image_hover-color_gradient' => 
  array (
    0 => '#000000',
    1 => '#303030',
  ),
  'image_hover-opacity' => 15,
  'general-next_prev_in_album' => '1',
  'general-show_back_button_in_album' => '1',
  'general-album_back_button_target_page_id' => 16237,
  'general-album_meta_on' => '1',
  'general-album_meta_date' => '1',
  'general-album_meta_author' => false,
  'general-album_meta_categories' => '1',
  'general-album_meta_comments' => false,
  'general-boxed_bg_fixed' => '1',
  'sidebar-width' => 30,
  'sidebar-vertical_distance' => 84,
  'sidebar-divider-vertical' => '1',
  'sidebar-divider-horizontal' => '1',
  'header-mobile-first_switch-after' => 1280,
  'header-mobile-first_switch-logo' => 'mobile',
  'header-mobile-second_switch-after' => 600,
  'header-mobile-second_switch-logo' => 'mobile',
  'header-mobile-menu_color' => 'accent',
  'header-mobile-menu_color-background' => '#f94dda',
  'header-mobile-menu_color-text' => '#000000',
  'general-mobile_logo-regular' => 
  array (
    0 => '/inc/presets/images/full/skin17b.general-mobile-logo-regular.png?w=41&h=64',
    1 => 0,
  ),
  'general-mobile_logo-hd' => 
  array (
    0 => '/inc/presets/images/full/skin17b.general-mobile-logo-hd.png?w=82&h=128',
    1 => 0,
  ),
  'general-mobile_logo-padding_top' => '25',
  'general-mobile_logo-padding_bottom' => '25',
  'footer-style' => 'solid_background',
  'footer-slide-out-mode' => '0',
  'footer-paddings-top-bottom' => 50,
  'bottom-bar-style' => 'solid_background',
  'footer-paddings-columns' => 25,
  'bottom_bar-style' => 'solid_background',
  'footer-collapse_after' => 768,
  'gallery-responsiveness-treshold' => 900,
  'header-background' => 'normal',
  'header-menu_text_color' => 'light',
  'header-menu_hover_color' => 'light',
  'header-menu_top_bar_color' => 'theme',
  'header-menu_text_color_mode' => 'light',
  'header-menu_hover_color_mode' => 'light',
  'header-menu_top_bar_color_mode' => 'light',
  'header-bg_opacity' => 100,
  'header-bg_fullscreen' => false,
  'header-bg_fixed' => false,
  'header-center_menu_bg_opacity' => 100,
  'header-classic_menu_bg_opacity' => 55,
  'header-side_menu_lines_opacity' => 100,
  'general-bg_fixed' => false,
  'header-style' => 'solid_background',
  'general-responsiveness-treshold' => 970,
  'woocommerce_show_details_icon' => '1',
  'woocommerce_shop_template_fullwidth' => false,
  'header-side_menu_dropdown_style' => 'side',
  'header-login_url' => 'http://dream-dev.net/the7/pages/login/',
  'header-decoration' => 'line',
  'header-decoration_color' => '#e9e9e9',
  'header-soc_icon_custom_color_outline' => '1',
  'sidebar-visual_style' => 'with_dividers',
  'general-post_type_gallery_slug' => 'dt_gallery',
  'float_menu-bg_color_mode' => 'header_color',
  'float_menu-bg_color' => '#ffffff',
  'header-floating_menu_animation' => 'fade',
  'header-side_menu_visibility' => 'always_visible',
  'header-mobile-top_bar_position' => 'closed',
  'header-logout_caption' => 'Logout',
  'woocommerce_rel_products_max' => 4,
  'general-content_boxes_bg_mode' => 'transparent',
  'general-content_boxes_solid_bg_color' => '#ffffff',
  'general-icons_style' => 'bold',
  'header-left_layout_elements_visibility' => 'show',
  'header-center_layout_elements_visibility' => 'show',
  'header-classic_layout_elements_visibility' => 'show',
  'header-side_layout_elements_visibility' => 'show',
  'header-woocommerce_show_cart_subtotal' => '1',
  'header-woocommerce_show_counter' => 'allways',
  'header-woocommerce_counter_color' => '#ffffff',
  'stripes-stripe_1_content_boxes_bg_mode' => 'transparent',
  'stripes-stripe_1_content_boxes_solid_bg_color' => '#ffffff',
  'stripes-stripe_2_content_boxes_bg_mode' => 'transparent',
  'stripes-stripe_2_content_boxes_solid_bg_color' => '#ffffff',
  'stripes-stripe_3_content_boxes_bg_mode' => 'transparent',
  'stripes-stripe_3_content_boxes_solid_bg_color' => '#ffffff',
  'general-title_bg_gradient' => 
  array (
    0 => '#4a66d6',
    1 => '#12b4ea',
  ),
  'image_hover-default_icon' => 'big_center',
  'social_buttons-visibility' => 'allways',
  'image_hover-project_rollover_opacity' => 80,
  'general-content_boxes_bg_color' => '#f5f5f5',
  'general-content_boxes_bg_opacity' => 100,
  'general-content_boxes_decoration' => 'none',
  'general-content_boxes_decoration_outline_color' => '#000000',
  'general-content_boxes_decoration_outline_opacity' => 0,
  'general-filter_style' => 'material',
  'general-filter-font-family' => 'Roboto Slab:700',
  'general-filter-font-size' => 14,
  'general-filter_ucase' => '1',
  'general-filter-padding-top' => 8,
  'general-filter-padding-right' => 0,
  'general-filter-padding-bottom' => 8,
  'general-filter-padding-left' => 0,
  'general-filter-margin-top' => 0,
  'general-filter-margin-right' => 15,
  'general-filter-margin-bottom' => 0,
  'general-filter-margin-left' => 15,
  'general-contact_form_style' => 'minimal',
  'general-fancy_date_size' => 'big',
  'general-slideshow_bullets_style' => 'transparent',
  'general-fullscreen_overlay_color_mode' => 'color',
  'general-fullscreen_overlay_color' => '#ffffff',
  'general-fullscreen_overlay_gradient' => 
  array (
    0 => '#8224e3',
    1 => '#dd3333',
  ),
  'general-fullscreen_overlay_opacity' => 100,
  'general-spinner_color' => '#88cccf',
  'general-spinner_opacity' => 100,
  'general-loader_style' => 'double_circles',
  'top_bar-font-family' => 'Open Sans',
  'top_bar-font-size' => 13,
  'top_bar-font-is_capitalized' => false,
  'top_bar-font-color' => '#aaaeb5',
  'top_bar-paddings-top' => 5,
  'top_bar-paddings-bottom' => 6,
  'top_bar-paddings-horizontal' => 0,
  'top_bar-bg-style' => 'fullwidth_line',
  'top_bar-bg-color' => '#878d94',
  'top_bar-bg-opacity' => 18,
  'top_bar-bg-image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-bg-color' => '#2b2b2b',
  'header-bg-opacity' => 100,
  'header-bg-image' => 
  array (
    'image' => '/inc/presets/images/full/skin16r.header-bg-image.gif',
    'repeat' => 'repeat',
    'position_x' => 'left',
    'position_y' => 'top',
  ),
  'header-bg-is_fullscreen' => false,
  'header-bg-is_fixed' => false,
  'header-decoration-color' => '#373737',
  'header-decoration-opacity' => 100,
  'header-classic-menu-bg-style' => 'solid',
  'header-classic-menu-bg-color' => '#000000',
  'header-classic-menu-bg-opacity' => 100,
  'header-menu_icon-color' => '#ffffff',
  'header-menu_icon-bg-color' => '#26282c',
  'header-menu_icon-bg-opacity' => 100,
  'header-menu_icon-hover-color' => '#ffffff',
  'header-menu_icon-hover-bg-color' => '#ffffff',
  'header-menu_icon-hover-bg-opacity' => 18,
  'header-menu_icon-margin-top' => 30,
  'header-menu_icon-margin-bottom' => 30,
  'header-menu_icon-margin-left' => 30,
  'header-menu_icon-margin-right' => 30,
  'header-menu_icon-bg-border-radius' => 0,
  'header-mixed-decoration' => 'shadow',
  'header-mixed-decoration-color' => '#dd9933',
  'header-mixed-decoration-opacity' => 100,
  'header-mixed-bg-color' => '#ffffff',
  'header-mixed-bg-opacity' => 100,
  'header-slide_out-overlay-bg-color-style' => 'color',
  'header-slide_out-overlay-bg-color' => '#ffffff',
  'header-slide_out-overlay-bg-gradient' => 
  array (
    0 => '#cdb7e2',
    1 => '#821482',
  ),
  'header-slide_out-overlay-bg-opacity' => 30,
  'header-slide_out-overlay-blur' => '0',
  'header-slide_out-overlay-x_cursor' => '1',
  'header-slide_out-overlay-x_cursor-color' => '#2b2b2b',
  'header-slide_out-overlay-x_cursor-opacity' => 100,
  'header-show_floating_navigation' => '1',
  'header-floating_navigation-style' => 'sticky',
  'header-floating_navigation-show_after' => 120,
  'header-floating_navigation-height' => 70,
  'header-floating_navigation-bg-color' => '#81d742',
  'header-floating_navigation-bg-opacity' => 9,
  'header-floating_navigation-decoration' => 'line',
  'header-floating_navigation-decoration-color' => '#8224e3',
  'header-floating_navigation-decoration-opacity' => 100,
  'header-menu-font-family' => 'Roboto Slab',
  'header-menu-font-size' => 18,
  'header-menu-font-is_capitalized' => '1',
  'header-menu-subtitle-font-family' => 'Arial:400italic',
  'header-menu-subtitle-font-size' => 12,
  'header-menu-font-color' => '#ffffff',
  'header-menu-hover-font-color-style' => 'accent',
  'header-menu-hover-font-color' => '#ffffff',
  'header-menu-hover-font-gradient' => 
  array (
    0 => '#8224e3',
    1 => '#751257',
  ),
  'header-menu-active_item-font-color-style' => 'accent',
  'header-menu-active_item-font-color' => '#ffffff',
  'header-menu-active_item-font-gradient' => 
  array (
    0 => '#ffffff',
    1 => '#000000',
  ),
  'header-menu-icon-size' => 14,
  'header-menu-show_next_lvl_icons' => '1',
  'header-menu-item-padding-top' => 14,
  'header-menu-item-padding-right' => 0,
  'header-menu-item-padding-bottom' => 14,
  'header-menu-item-padding-left' => 0,
  'header-menu-item-margin-top' => 0,
  'header-menu-item-margin-right' => 50,
  'header-menu-item-margin-bottom' => 0,
  'header-menu-item-margin-left' => 0,
  'header-menu-item-surround_margins-style' => 'regular',
  'header-menu-item-surround_margins-custom-margin' => 30,
  'header-menu-decoration-other-links-is_justified' => '1',
  'header-menu-show_dividers' => '0',
  'header-menu-dividers-height-style' => 'full',
  'header-menu-dividers-height' => 80,
  'header-menu-dividers-surround' => '1',
  'header-menu-dividers-color' => '#ffffff',
  'header-menu-dividers-opacity' => 12,
  'header-menu-decoration-style' => 'underline',
  'header-menu-decoration-underline-direction' => 'left_to_right',
  'header-menu-decoration-underline-color-style' => 'accent',
  'header-menu-decoration-underline-color' => '#ffffff',
  'header-menu-decoration-underline-gradient' => 
  array (
    0 => '#ffffff',
    1 => '#000000',
  ),
  'header-menu-decoration-other-hover-style' => 'background',
  'header-menu-decoration-other-hover-color-style' => 'accent',
  'header-menu-decoration-other-hover-color' => '#ffffff',
  'header-menu-decoration-other-hover-gradient' => 
  array (
    0 => '#ffffff',
    1 => '#000000',
  ),
  'header-menu-decoration-other-opacity' => 15,
  'header-menu-decoration-other-hover-line' => '0',
  'header-menu-decoration-other-hover-line-color-style' => 'gradient',
  'header-menu-decoration-other-hover-line-color' => '#dd3333',
  'header-menu-decoration-other-hover-line-gradient' => 
  array (
    0 => '#ffffff',
    1 => '#000000',
  ),
  'header-menu-decoration-other-hover-line-opacity' => 23,
  'header-menu-decoration-other-active-style' => 'background',
  'header-menu-decoration-other-active-color-style' => 'accent',
  'header-menu-decoration-other-active-color' => '#ffffff',
  'header-menu-decoration-other-active-gradient' => 
  array (
    0 => '#ffffff',
    1 => '#000000',
  ),
  'header-menu-decoration-other-active-opacity' => 15,
  'header-menu-decoration-other-active-line' => '0',
  'header-menu-decoration-other-active-line-color-style' => 'color',
  'header-menu-decoration-other-active-line-color' => '#8224e3',
  'header-menu-decoration-other-active-line-gradient' => 
  array (
    0 => '#dd3333',
    1 => '#81d742',
  ),
  'header-menu-decoration-other-active-line-opacity' => 30,
  'header-menu-decoration-other-click_decor' => '1',
  'header-menu-decoration-other-click_decor-color-style' => 'accent',
  'header-menu-decoration-other-click_decor-color' => '#ffffff',
  'header-menu-decoration-other-click_decor-gradient' => 
  array (
    0 => '#ffffff',
    1 => '#000000',
  ),
  'header-menu-decoration-other-click_decor-opacity' => 20,
  'header-menu-decoration-other-border-radius' => 3,
  'header-menu-submenu-font-family' => 'Open Sans',
  'header-menu-submenu-font-size' => 13,
  'header-menu-submenu-font-is_uppercase' => false,
  'header-menu-submenu-subtitle-font-family' => 'Arial:400italic',
  'header-menu-submenu-subtitle-font-size' => 10,
  'header-menu-submenu-font-color' => '#ffffff',
  'header-menu-submenu-hover-font-color-style' => 'accent',
  'header-menu-submenu-hover-font-color' => '#ffffff',
  'header-menu-submenu-hover-font-gradient' => 
  array (
    0 => '#81d742',
    1 => '#eeee22',
  ),
  'header-menu-submenu-active-font-color-style' => 'accent',
  'header-menu-submenu-active-font-color' => '#ffffff',
  'header-menu-submenu-active-font-gradient' => 
  array (
    0 => '#ffffff',
    1 => '#000000',
  ),
  'header-menu-submenu-icon-size' => 12,
  'header-menu-submenu-show_next_lvl_icons' => '1',
  'header-menu-submenu-item-padding-top' => 9,
  'header-menu-submenu-item-padding-right' => 12,
  'header-menu-submenu-item-padding-bottom' => 9,
  'header-menu-submenu-item-padding-left' => 12,
  'header-menu-submenu-item-margin-top' => 0,
  'header-menu-submenu-item-margin-right' => 0,
  'header-menu-submenu-item-margin-bottom' => 0,
  'header-menu-submenu-item-margin-left' => 0,
  'header-menu-submenu-bg-color' => '#333333',
  'header-menu-submenu-bg-opacity' => 97,
  'header-menu-submenu-bg-width' => 260,
  'header-menu-submenu-bg-hover' => 'none',
  'header-side-menu-submenu-position' => 'side',
  'header-elements-near_menu-font_family' => 'Open Sans',
  'header-elements-near_menu-font_size' => 13,
  'header-elements-near_menu-font_color' => '#ffffff',
  'header-elements-near_logo-font_family' => 'Open Sans',
  'header-elements-near_logo-font_size' => 13,
  'header-elements-near_logo-font_color' => '#ffffff',
  'header-elements-woocommerce_cart-caption' => '',
  'header-elements-woocommerce_cart-icon' => '1',
  'header-elements-woocommerce_cart-mobile-layout' => 'in_menu',
  'header-elements-woocommerce_cart-show_subtotal' => false,
  'header-elements-woocommerce_cart-show_counter' => 'allways',
  'header-elements-woocommerce_cart-counter-style' => 'rectangular',
  'header-elements-woocommerce_cart-counter-color' => '#ffffff',
  'header-elements-woocommerce_cart-counter-bg' => 'accent',
  'header-elements-woocommerce_cart-counter-bg-color' => '#000000',
  'header-elements-woocommerce_cart-counter-bg-gradient' => 
  array (
    0 => '#ffffff',
    1 => '#000000',
  ),
  'header-elements-search-caption' => '',
  'header-elements-search-icon' => '1',
  'header-elements-search-mobile-layout' => 'near_logo',
  'header-elements-contact-address-caption' => '8500 Beverly Boulevard Los Angeles, CA 90048',
  'header-elements-contact-address-icon' => '1',
  'header-elements-contact-address-mobile-layout' => 'in_menu',
  'header-elements-contact-phone-caption' => '011 322 44 56',
  'header-elements-contact-phone-icon' => '1',
  'header-elements-contact-phone-mobile-layout' => 'in_menu',
  'header-elements-contact-email-caption' => 'sales@yoursite.com',
  'header-elements-contact-email-icon' => '1',
  'header-elements-contact-email-mobile-layout' => 'in_menu',
  'header-elements-contact-skype-caption' => 'Your_Skype',
  'header-elements-contact-skype-icon' => '1',
  'header-elements-contact-skype-mobile-layout' => 'in_menu',
  'header-elements-contact-clock-caption' => 'Monday – Friday 10 AM – 8 PM',
  'header-elements-contact-clock-icon' => '1',
  'header-elements-contact-clock-mobile-layout' => 'in_menu',
  'header-elements-login-caption' => 'Login',
  'header-elements-logout-caption' => 'Logout',
  'header-elements-login-icon' => '1',
  'header-elements-login-mobile-layout' => 'in_menu',
  'header-elements-login-url' => 'http://themeforest.net',
  'header-elements-text-mobile-layout' => 'in_menu',
  'header-elements-text' => 'Some call to action text goes here!',
  'header-elements-menu-mobile-layout' => 'hidden',
  'header-elements-soc_icons-mobile-layout' => 'hidden',
  'header-elements-soc_icons-color' => '#ffffff',
  'header-elements-soc_icons-bg' => 'accent',
  'header-elements-soc_icons-bg-color' => '#ffffff',
  'header-elements-soc_icons-bg-gradient' => 
  array (
    0 => '#ffffff',
    1 => '#000000',
  ),
  'header-elements-soc_icons-hover-color' => '#99d3d6',
  'header-elements-soc_icons-hover-bg' => 'color',
  'header-elements-soc_icons-hover-bg-color' => '#ffffff',
  'header-elements-soc_icons-hover-bg-gradient' => 
  array (
    0 => '#ffffff',
    1 => '#000000',
  ),
  'header-elements-soc_icons' => 
  array (
    1 => 
    array (
      'icon' => 'facebook',
      'url' => 'https://www.facebook.com/WordPress.Premium.Theme/',
    ),
    2 => 
    array (
      'icon' => 'twitter',
      'url' => 'https://twitter.com/premium_theme',
    ),
    5 => 
    array (
      'icon' => 'pinterest',
      'url' => 'https://www.pinterest.com/dreamtheme/',
    ),
    6 => 
    array (
      'icon' => 'instagram',
      'url' => 'https://www.instagram.com/dream_theme_photo/',
    ),
  ),
  'header-classic-show_elements' => '1',
  'header-classic-elements' => 
  array (
    'near_menu_right' => 
    array (
      0 => 'social_icons',
    ),
    'near_logo_left' => 
    array (
      0 => 'address',
    ),
    'near_logo_right' => 
    array (
      0 => 'phone',
      1 => 'email',
      2 => 'cart',
    ),
  ),
  'header-classic-elements-near_menu_right-padding-right' => 0,
  'header-classic-elements-near_menu_right-padding-left' => 40,
  'header-classic-elements-near_logo_left-padding-right' => 0,
  'header-classic-elements-near_logo_left-padding-left' => 0,
  'header-classic-elements-near_logo_right-padding-right' => 0,
  'header-classic-elements-near_logo_right-padding-left' => 0,
  'header-classic-logo-position' => 'left',
  'header-classic-menu-position' => 'left',
  'header-classic-height' => 180,
  'header-classic-is_fullwidth' => '0',
  'header-inline-show_elements' => '1',
  'header-inline-elements' => 
  array (
    'near_menu_right' => 
    array (
      0 => 'search',
      1 => 'cart',
    ),
  ),
  'header-inline-elements-near_menu_right-padding-right' => 0,
  'header-inline-elements-near_menu_right-padding-left' => 2,
  'header-inline-menu-position' => 'justify',
  'header-inline-height' => 120,
  'header-inline-is_fullwidth' => '0',
  'header-split-show_elements' => '1',
  'header-split-elements' => 
  array (
    'near_menu_left' => 
    array (
      0 => 'search',
    ),
    'near_menu_right' => 
    array (
      0 => 'cart',
    ),
  ),
  'header-split-elements-near_menu_left-padding-right' => 20,
  'header-split-elements-near_menu_left-padding-left' => 20,
  'header-split-elements-near_menu_right-padding-right' => 20,
  'header-split-elements-near_menu_right-padding-left' => 20,
  'header-split-menu-position' => 'outside',
  'header-split-height' => 100,
  'header-split-is_fullwidth' => '0',
  'header-side-show_elements' => '1',
  'header-side-elements' => 
  array (
    'below_menu' => 
    array (
      0 => 'social_icons',
    ),
  ),
  'header-side-elements-below_menu-padding-top' => 40,
  'header-side-elements-below_menu-padding-right' => 44,
  'header-side-elements-below_menu-padding-bottom' => 33,
  'header-side-elements-below_menu-padding-left' => 0,
  'header-side-position' => 'left',
  'header-side-width' => '300px',
  'header-side-content-width' => '100%',
  'header-side-content-position' => 'left',
  'header-side-content-padding-top' => 0,
  'header-side-content-padding-right' => 0,
  'header-side-content-padding-bottom' => 0,
  'header-side-content-padding-left' => 44,
  'header-side-menu-position' => 'v_top',
  'header-side-logo-position' => 'inside',
  'header-side-menu-padding-top' => 0,
  'header-side-menu-padding-bottom' => 0,
  'header-side-menu-items_alignment' => 'left',
  'header-side-menu-items_link' => 'fullwidth',
  'header-slide_out-show_elements' => '1',
  'header-slide_out-elements' => 
  array (
    'side_top_line' => 
    array (
      0 => 'phone',
      1 => 'email',
      2 => 'skype',
    ),
  ),
  'header-slide_out-elements-top_line-padding-right' => 0,
  'header-slide_out-elements-top_line-padding-left' => 0,
  'header-slide_out-elements-side_line-padding-top' => 0,
  'header-slide_out-elements-side_line-padding-bottom' => 0,
  'header-slide_out-elements-below_menu-padding-top' => 20,
  'header-slide_out-elements-below_menu-padding-right' => 50,
  'header-slide_out-elements-below_menu-padding-bottom' => 40,
  'header-slide_out-elements-below_menu-padding-left' => 50,
  'header-slide_out-layout' => 'top_line',
  'header-slide_out-layout-menu_icon-show_floating_logo' => '1',
  'header-slide_out-layout-top_line-height' => 100,
  'header-slide_out-layout-top_line-is_fullwidth' => '0',
  'header-slide_out-layout-top_line-logo-position' => 'center',
  'header-slide_out-layout-side_line-width' => 60,
  'header-slide_out-layout-side_line-position' => 'under',
  'header-slide_out-position' => 'right',
  'header-slide_out-overlay-animation' => 'slide',
  'header-slide_out-width' => '33%',
  'header-slide_out-content-width' => '100%',
  'header-slide_out-content-position' => 'left',
  'header-slide_out-content-padding-top' => 0,
  'header-slide_out-content-padding-right' => 0,
  'header-slide_out-content-padding-bottom' => 0,
  'header-slide_out-content-padding-left' => 0,
  'header-slide_out-menu-position' => 'v_top',
  'header-slide_out-logo-position' => 'inside',
  'header-slide_out-menu-padding-top' => 30,
  'header-slide_out-menu-padding-bottom' => 0,
  'header-slide_out-menu-items_alignment' => 'left',
  'header-slide_out-menu-items_link' => 'textwidth',
  'header-overlay-show_elements' => '1',
  'header-overlay-elements' => 
  array (
    'below_menu' => 
    array (
      0 => 'search',
      1 => 'cart',
    ),
    'side_top_line' => 
    array (
      0 => 'social_icons',
      1 => 'text_area',
      2 => 'phone',
    ),
  ),
  'header-overlay-elements-top_line-padding-right' => 0,
  'header-overlay-elements-top_line-padding-left' => 0,
  'header-overlay-elements-side_line-padding-top' => 0,
  'header-overlay-elements-side_line-padding-bottom' => 0,
  'header-overlay-elements-below_menu-padding-top' => 0,
  'header-overlay-elements-below_menu-padding-right' => 0,
  'header-overlay-elements-below_menu-padding-bottom' => 40,
  'header-overlay-elements-below_menu-padding-left' => 0,
  'header-overlay-layout' => 'menu_icon',
  'header-overlay-layout-menu_icon-show_floating_logo' => '1',
  'header-overlay-layout-top_line-height' => 80,
  'header-overlay-layout-top_line-is_fullwidth' => '0',
  'header-overlay-layout-top_line-logo-position' => 'center',
  'header-overlay-layout-side_line-width' => 60,
  'header-overlay-content-width' => '320px',
  'header-overlay-content-position' => 'center',
  'header-overlay-content-padding-top' => 0,
  'header-overlay-content-padding-right' => 0,
  'header-overlay-content-padding-bottom' => 0,
  'header-overlay-content-padding-left' => 0,
  'header-overlay-menu-position' => 'v_center',
  'header-overlay-logo-position' => 'inside',
  'header-overlay-menu-padding-top' => 40,
  'header-overlay-menu-padding-bottom' => 40,
  'header-overlay-menu-items_alignment' => 'left',
  'header-overlay-menu-items_link' => 'fullwidth',
  'header-mobile-first_switch-layout' => 'left_center',
  'header-mobile-first_switch-height' => 60,
  'header-mobile-second_switch-layout' => 'left_center',
  'header-mobile-second_switch-height' => 60,
  'header-mobile-floating_navigation' => 'sticky',
  'header-mobile-menu-font-family' => 'Roboto Slab',
  'header-mobile-menu-font-size' => 18,
  'header-mobile-menu-font-is_capitalized' => '1',
  'header-mobile-submenu-font-family' => 'Open Sans',
  'header-mobile-submenu-font-size' => 14,
  'header-mobile-submenu-font-is_capitalized' => false,
  'header-mobile-menu-font-color' => '#ffffff',
  'header-mobile-menu-font-hover-color-style' => 'accent',
  'header-mobile-menu-font-hover-color' => '#3c3e45',
  'header-mobile-menu-font-hover-gradient' => 
  array (
    0 => '#b78ce2',
    1 => '#1e73be',
  ),
  'header-mobile-menu-bg-color' => '#2b2b2b',
  'header-mobile-menu-bg-opacity' => 100,
  'header-mobile-menu-bg-width' => 330,
  'header-mobile-menu-align' => 'left',
  'header-logo-padding-top' => 65,
  'header-logo-padding-right' => 0,
  'header-logo-padding-bottom' => 55,
  'header-logo-padding-left' => 0,
  'header-style-transparent-logo_regular' => 
  array (
    0 => '',
    1 => 0,
  ),
  'header-style-transparent-logo_hd' => 
  array (
    0 => '',
    1 => 0,
  ),
  'header-style-transparent-logo-padding-top' => 0,
  'header-style-transparent-logo-padding-right' => 0,
  'header-style-transparent-logo-padding-bottom' => 0,
  'header-style-transparent-logo-padding-left' => 0,
  'header-style-mixed-logo_regular' => 
  array (
    0 => '',
    1 => 0,
  ),
  'header-style-mixed-logo_hd' => 
  array (
    0 => '',
    1 => 0,
  ),
  'header-style-mixed-logo-padding-top' => 0,
  'header-style-mixed-logo-padding-right' => 0,
  'header-style-mixed-logo-padding-bottom' => 0,
  'header-style-mixed-logo-padding-left' => 0,
  'header-style-floating-choose_logo' => 'custom',
  'header-style-floating-logo_regular' => 
  array (
    0 => '',
    1 => 0,
  ),
  'header-style-floating-logo_hd' => 
  array (
    0 => '',
    1 => 0,
  ),
  'header-style-floating-logo-padding-top' => 0,
  'header-style-floating-logo-padding-right' => 0,
  'header-style-floating-logo-padding-bottom' => 0,
  'header-style-floating-logo-padding-left' => 0,
  'header-style-mobile-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin16r.header-style-mobile-logo-regular.png?w=180&h=31',
    1 => 0,
  ),
  'header-style-mobile-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin16r.header-style-mobile-logo-hd.png?w=360&h=62',
    1 => 0,
  ),
  'header-style-mobile-logo-padding-top' => 0,
  'header-style-mobile-logo-padding-right' => 0,
  'header-style-mobile-logo-padding-bottom' => 2,
  'header-style-mobile-logo-padding-left' => 0,
  'bottom_bar-logo-padding-top' => 0,
  'bottom_bar-logo-padding-right' => 0,
  'bottom_bar-logo-padding-bottom' => 0,
  'bottom_bar-logo-padding-left' => 0,
  'stripes-stripe_1_outline' => 'hide',
  'stripes-stripe_1_outline_color' => '#FFFFFF',
  'stripes-stripe_1_outline_opacity' => 100,
  'stripes-stripe_1_content_boxes_bg_color' => '#FFFFFF',
  'stripes-stripe_1_content_boxes_bg_opacity' => 100,
  'stripes-stripe_1_content_boxes_decoration' => 'shadow',
  'stripes-stripe_1_content_boxes_decoration_outline_color' => '#FFFFFF',
  'stripes-stripe_1_content_boxes_decoration_outline_opacity' => 100,
  'stripes-stripe_2_outline' => 'hide',
  'stripes-stripe_2_outline_color' => '#FFFFFF',
  'stripes-stripe_2_outline_opacity' => 100,
  'stripes-stripe_2_content_boxes_bg_color' => '#373737',
  'stripes-stripe_2_content_boxes_bg_opacity' => 100,
  'stripes-stripe_2_content_boxes_decoration' => 'none',
  'stripes-stripe_2_content_boxes_decoration_outline_color' => '#FFFFFF',
  'stripes-stripe_2_content_boxes_decoration_outline_opacity' => 14,
  'stripes-stripe_3_outline' => 'hide',
  'stripes-stripe_3_outline_color' => '#FFFFFF',
  'stripes-stripe_3_outline_opacity' => 100,
  'stripes-stripe_3_content_boxes_bg_color' => '#FFFFFF',
  'stripes-stripe_3_content_boxes_bg_opacity' => 100,
  'stripes-stripe_3_content_boxes_decoration' => 'shadow',
  'stripes-stripe_3_content_boxes_decoration_outline_color' => '#FFFFFF',
  'stripes-stripe_3_content_boxes_decoration_outline_opacity' => 100,
  'sidebar-decoration' => 'none',
  'sidebar-decoration_outline_color' => '#000000',
  'sidebar-decoration_outline_opacity' => 6,
  'footer-decoration' => 'none',
  'footer-decoration_outline_color' => '#81d742',
  'footer-decoration_outline_opacity' => 96,
  'page_title-padding-top' => 0,
  'page_title-padding-bottom' => 0,
  'page_title-background-style-transparent-color_scheme' => 'from_options',
  'general-title_bg_opacity' => 100,
  'general-title_decoration' => 'none',
  'general-title_decoration_outline_color' => '#1e73be',
  'general-title_decoration_outline_opacity' => 0,
  'buttons-hover_color_mode' => 'color',
  'buttons-hover_color' => '#99d3d6',
  'buttons-hover_color_gradient' => 
  array (
    0 => '#cc4789',
    1 => '#e57544',
  ),
  'buttons-text_color_mode' => 'color',
  'buttons-text_color' => '#ffffff',
  'buttons-text_hover_color_mode' => 'color',
  'buttons-text_hover_color' => '#ffffff',
  'image_hover-onclick_animation' => '1',
  'image_hover-project_icons_style' => 'accent',
  'image_hover-album_miniatures_style' => 'style_2',
  'image_hover-project_rollover_color_mode' => 'color',
  'image_hover-project_rollover_color' => '#292929',
  'image_hover-project_rollover_color_gradient' => 
  array (
    0 => '#6ae5e6',
    1 => '#1190c9',
  ),
  'woocommerce_add_to_cart_position' => 'below_image',
  'general-custom_loader' => '',
  'header-elements-woocommerce_cart-show_sub_cart' => '1',
  'footer-padding-top' => 60,
  'footer-padding-bottom' => 0,
  'header-elements-text-2-mobile-layout' => 'in_menu',
  'header-elements-text-2' => 'Some call to action text goes here!',
  'header-elements-text-3-mobile-layout' => 'in_menu',
  'header-elements-text-3' => 'Some call to action text goes here!',
  'header-elements-soc_icons-bg-opacity' => 100,
  'header-elements-soc_icons-bg-hover-opacity' => 100,
  'header-elements-menu-style' => 'list',
  'general-images_lazy_loading' => '1',
  'modules-portfolio-status' => 'enabled',
  'modules-testimonials-status' => 'enabled',
  'modules-team-status' => 'enabled',
  'modules-logos-status' => 'enabled',
  'modules-benefits-status' => 'enabled',
  'modules-albums-status' => 'enabled',
  'modules-slideshow-status' => 'enabled',
  'bottom_bar-enabled' => '1',
  'header-elements-woocommerce_cart-on-desktops' => 'show',
  'header-elements-woocommerce_cart-first-header-switch' => 'near_logo',
  'header-elements-woocommerce_cart-second-header-switch' => 'in_menu',
  'header-elements-search-on-desktops' => 'show',
  'header-elements-search-first-header-switch' => 'near_logo',
  'header-elements-search-second-header-switch' => 'near_logo',
  'header-elements-contact-address-on-desktops' => 'show',
  'header-elements-contact-address-first-header-switch' => 'near_logo',
  'header-elements-contact-address-second-header-switch' => 'in_menu',
  'header-elements-contact-phone-on-desktops' => 'show',
  'header-elements-contact-phone-first-header-switch' => 'near_logo',
  'header-elements-contact-phone-second-header-switch' => 'in_menu',
  'header-elements-contact-email-on-desktops' => 'show',
  'header-elements-contact-email-first-header-switch' => 'near_logo',
  'header-elements-contact-email-second-header-switch' => 'in_menu',
  'header-elements-contact-skype-on-desktops' => 'show',
  'header-elements-contact-skype-first-header-switch' => 'near_logo',
  'header-elements-contact-skype-second-header-switch' => 'in_menu',
  'header-elements-contact-clock-on-desktops' => 'show',
  'header-elements-contact-clock-first-header-switch' => 'near_logo',
  'header-elements-contact-clock-second-header-switch' => 'in_menu',
  'header-elements-login-on-desktops' => 'show',
  'header-elements-login-first-header-switch' => 'near_logo',
  'header-elements-login-second-header-switch' => 'in_menu',
  'header-elements-text-on-desktops' => 'show',
  'header-elements-text-first-header-switch' => 'near_logo',
  'header-elements-text-second-header-switch' => 'in_menu',
  'header-elements-text-2-on-desktops' => 'show',
  'header-elements-text-2-first-header-switch' => 'near_logo',
  'header-elements-text-2-second-header-switch' => 'in_menu',
  'header-elements-text-3-on-desktops' => 'show',
  'header-elements-text-3-first-header-switch' => 'near_logo',
  'header-elements-text-3-second-header-switch' => 'in_menu',
  'header-elements-menu-on-desktops' => 'show',
  'header-elements-menu-first-header-switch' => 'near_logo',
  'header-elements-menu-second-header-switch' => 'hidden',
  'header-elements-soc_icons-on-desktops' => 'show',
  'header-elements-soc_icons-first-header-switch' => 'near_logo',
  'header-elements-soc_icons-second-header-switch' => 'hidden',
  'general-side_content_paddings' => 50,
  'general-switch_content_paddings' => 768,
  'general-mobile_side_content_paddings' => 20,
  'header-classic-elements-near_menu_right-padding-top' => 0,
  'header-classic-elements-near_menu_right-padding-bottom' => 0,
  'header-classic-elements-near_logo_left-padding-top' => 0,
  'header-classic-elements-near_logo_left-padding-bottom' => 0,
  'header-classic-elements-near_logo_right-padding-top' => 0,
  'header-classic-elements-near_logo_right-padding-bottom' => 0,
  'header-inline-elements-near_menu_right-padding-top' => 0,
  'header-inline-elements-near_menu_right-padding-bottom' => 0,
  'header-split-elements-near_menu_left-padding-top' => 0,
  'header-split-elements-near_menu_left-padding-bottom' => 0,
  'header-split-elements-near_menu_right-padding-top' => 0,
  'header-split-elements-near_menu_right-padding-bottom' => 0,
  'header-slide_out-elements-top_line-padding-top' => 0,
  'header-slide_out-elements-top_line-padding-bottom' => 0,
  'header-overlay-elements-top_line-padding-top' => 0,
  'header-overlay-elements-top_line-padding-bottom' => 0,
  'header-classic-menu-margin-top' => 0,
  'header-classic-menu-margin-bottom' => 0,
  'general-page_content_vertical_margins' => 50,
  'general-template_content_vertical_margins' => 60,
  'header-elements-language-on-desktops' => 'show',
  'header-elements-language-first-header-switch' => 'near_logo',
  'header-elements-language-second-header-switch' => 'in_menu',
  'general-filter_style-minimal-border_radius' => 100,
  'general-filter_style-material-line_size' => 2,
  'dividers-color' => '#434343',
  'dividers-opacity' => 12,
  'content-secondary_text_color' => '#bababa',
  'header-classic-icons_style' => 'bold',
  'header-inline-icons_style' => 'bold',
  'header-split-icons_style' => 'bold',
  'header-side-icons_style' => 'bold',
  'header-slide_out-icons_style' => 'light',
  'header-overlay-icons_style' => 'light',
  'blog-thumbnail_size' => 'resize',
  'blog-thumbnail_proportions' => 
  array (
    'width' => 2,
    'height' => 1,
  ),
  'template_page_id_portfolio_category' => 0,
  'template_page_id_gallery_category' => 0,
  'general-navigation_margin' => 50,
); ?>