<?php
/**
 * Setup PrimaThemes framework
 *
 * WARNING: This file is part of the core PrimaThemes framework.
 * DO NOT edit this file under any circumstances. 
 *
 * Credits (and Inspirations):
 * - Hybrid Core by ThemeHybrid http://themehybrid.com
 *
 * @category   PrimaThemes
 * @package    Framework
 * @subpackage Functions
 * @author     PrimaThemes
 * @link       http://www.primathemes.com
 */

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

/**
 * Show PrimaThemes theme settings page after activate.
 *
 * @since PrimaThemes 2.0
 */
if (is_admin() && isset($_GET['activated'] ) && $pagenow == "themes.php" ) {
	wp_redirect( add_query_arg( array( 'page' => 'primathemes', 'theme-activated' => 'true' ), admin_url( 'themes.php' ) ) );
	exit;
}

/**
 * Class to control PrimaThemes Framework.
 *
 * @since PrimaThemes 2.0
 */
class Prima_Framework {

	/* Constructor */
	public function __construct() {
		$this->constants();
		$this->functions();
		$this->shortcodes();
		$this->themesetup();
		add_action( 'wp_loaded', array( $this, 'admin' ) );
	}
	
	/* Defines the constant paths for use */
	public function constants() {
		/* Define Database Constants */
		if( !defined('PRIMA_THEME_SETTINGS') ) 
			define( 'PRIMA_THEME_SETTINGS', 'primathemes' );
		if( !defined('PRIMA_DESIGN_SETTINGS') ) 
			define( 'PRIMA_DESIGN_SETTINGS', 'primathemes_design' );
		if( !defined('PRIMA_SIDEBAR_SETTINGS') ) 
			define( 'PRIMA_SIDEBAR_SETTINGS', 'primathemes_sidebar' );
			
		/* Define PrimaThemes Framework Version */
		define( 'PRIMATHEMES', '2.0' );
		
		/* Define Parent Theme Constants */
		define( 'PRIMA_DIR', get_template_directory() );
		define( 'PRIMA_URI', get_template_directory_uri() );
		define( 'PRIMA_CORE_DIR', trailingslashit(PRIMA_DIR) . 'core' );
		define( 'PRIMA_CORE_URI', trailingslashit(PRIMA_URI) . 'core' );
		define( 'PRIMA_ADMIN_DIR', trailingslashit(PRIMA_CORE_DIR) . 'admin' );
		define( 'PRIMA_ADMIN_URI', trailingslashit(PRIMA_CORE_URI) . 'admin' );
		define( 'PRIMA_CUSTOM_DIR', trailingslashit(PRIMA_DIR) . 'inc' );
		define( 'PRIMA_CUSTOM_URI', trailingslashit(PRIMA_URI) . 'inc' );

		/* Define Child Theme Constants */
		define( 'THEME_DIR', get_stylesheet_directory() );
		define( 'THEME_URI', get_stylesheet_directory_uri() );
	}
	
	/* Loads the core theme functions. */
	public function functions() {
		$this->include_core ( 'functions/core.php' );
		$this->include_core ( 'functions/layouts.php' );
		$this->include_core ( 'functions/sidebars.php' );
		$this->include_core ( 'functions/images.php' );
		$this->include_core ( 'functions/fonts.php' );
		$this->include_core ( 'functions/widgets.php' );
		$this->include_core ( 'functions/general.php' );
		$this->include_core ( 'functions/customizer.php' );
		if ( !is_admin() ) {
			$this->include_core ( 'functions/frontend.php' );
		}
	}
	
	/* Loads the core theme shortcodes. */
	public function shortcodes() {
		$this->include_core ( 'shortcodes/typography.php' );
		$this->include_core ( 'shortcodes/theme.php' );
		$this->include_core ( 'shortcodes/general.php' );
	}

	/* Load admin files. */
	public function admin() {
		if ( is_admin() ) {
			add_editor_style();
			$this->include_admin ( 'postmeta-settings.php' );
			$this->include_admin ( 'taxmeta-settings.php' );
			$this->include_admin ( 'widget-settings.php' );
			$this->include_admin ( 'theme-settings.php' );
			$this->include_admin ( 'design-settings.php', 'prima-design-settings' );
			$this->include_admin ( 'sidebar-settings.php', 'prima-sidebar-settings' );
		}
	}

	/* Load theme setup files. */
	public function themesetup() {
		$this->include_setup ( 'setup-theme.php' );
	}
	
	public function include_core( $file, $support = '' ) {
		if ( $support )
			require_if_theme_supports( $support, trailingslashit(PRIMA_CORE_DIR) . $file );
		else 
			prima_load( trailingslashit(PRIMA_CORE_DIR) . $file );
	}
	
	public function include_admin( $file, $support = '' ) {
		if ( $support )
			require_if_theme_supports( $support, trailingslashit(PRIMA_ADMIN_DIR) . $file );
		else 
			prima_load( trailingslashit(PRIMA_ADMIN_DIR) . $file );
	}
	
	public function include_setup( $file, $support = '' ) {
		if ( file_exists( trailingslashit(PRIMA_CUSTOM_DIR) . $file ) ) {
			if ( $support )
				require_if_theme_supports( $support, trailingslashit(PRIMA_CUSTOM_DIR) . $file );
			else 
				prima_load( trailingslashit(PRIMA_CUSTOM_DIR) . $file );
		}
	}
	
}

/**
 * Call PrimaThemes Framework
 *
 * @since PrimaThemes 2.0
 */
$_prima = new Prima_Framework;