<?php
/**
 * Functions to handle widgets
 *
 * WARNING: This file is part of the core PrimaThemes framework.
 * DO NOT edit this file under any circumstances. 
 *
 * @category   PrimaThemes
 * @package    Framework
 * @subpackage Widgets
 * @author     PrimaThemes
 * @link       http://www.primathemes.com
 */

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

/**
 * Register widgets.
 *
 * @since PrimaThemes 2.0
 */
add_action( 'widgets_init', 'prima_register_widgets' );
function prima_register_widgets() {
	register_widget('Prima_RecentPosts_Widget');
	register_widget('Prima_RecentComments_Widget');
	register_widget('Prima_SearchForm_Widget');
}

/**
 * Prima Recent Posts Widget class
 *
 * @since PrimaThemes 2.0
 */
class Prima_RecentPosts_Widget extends WP_Widget {
	public function __construct() {
		$widget_ops = array( 'classname' => 'prima_recent_posts', 'description' => __('Display most recent posts', 'primathemes') );
		$control_ops = array( 'id_base' => 'prima-recent-posts' );
		parent::__construct( 'prima-recent-posts', __('Advanced Recent Posts', 'primathemes'), $widget_ops, $control_ops );
		$this->alt_option_name = 'prima_recent_posts';
	}
	public function widget( $args, $instance ) {
		extract( $args );
		$title = apply_filters('widget_title', $instance['title'] );
		$number = (int)$instance['number'];
		$image = $instance['image'] ? '1' : '0';
		$image_width = (int)$instance['image_width'];
		$image_height = (int)$instance['image_height'];
		$postmeta = $instance['postmeta'] ? '1' : '0';
		$postexcerpt = $instance['postexcerpt'] ? '1' : '0';
		$excerpt_length = (int)$instance['excerpt_length'];
 		$output = '';
		$output .= $before_widget;
		if ( $title ) $output .= $before_title . $title . $after_title;
		$args = array(
			'post_type'	=> 'post',
			'ignore_sticky_posts'	=> 1,
			'posts_per_page' => $number
		);
		query_posts($args);
		if (have_posts()) : 
			$output .= '<ul>';
		while (have_posts()) : the_post();
			$output .= '<li>';
			if ( $image )
				$output .= prima_get_image( array ( 'width' => $image_width, 'height' => $image_height ) );
			$output .= '<h3><a href="'.get_permalink().'" title="" rel="bookmark">'.get_the_title().'</a></h3>';
			if ( $postmeta )
				$output .= '<p class="post-meta">'.do_shortcode( __( 'Posted on [post-date]', 'primathemes' ) ).'</p>';
			if ( $postexcerpt )
				$output .= prima_get_excerpt_limit($excerpt_length,false);
			$output .= '</li>';
		endwhile;
			$output .= '</ul>';
		endif;
		wp_reset_query();
		$output .= $after_widget;
		echo $output;
	}
	public function update( $new_instance, $old_instance ) {
		$instance = $old_instance;
		$instance['title'] = strip_tags( $new_instance['title'] );
		$instance['number'] = ( (int)$new_instance['number'] > 0 ? (int)$new_instance['number'] : '3' );
		$instance['image'] = ( isset( $new_instance['image'] ) ? 1 : 0 );
		$instance['image_width'] = ( (int)$new_instance['image_width'] > 0 ? (int)$new_instance['image_width'] : '50' );
		$instance['image_height'] = ( (int)$new_instance['image_height'] > 0 ? (int)$new_instance['image_height'] : '50' );
		$instance['postmeta'] = ( isset( $new_instance['postmeta'] ) ? 1 : 0 );
		$instance['postexcerpt'] = ( isset( $new_instance['postexcerpt'] ) ? 1 : 0 );
		$instance['excerpt_length'] = ( (int)$new_instance['excerpt_length'] > 0 ? (int)$new_instance['excerpt_length'] : '75' );
		return $instance;
	}
	public function form( $instance ) {
		$defaults = array( 'title' => 'Recent Posts', 'number' => 3, 'image' => true, 'image_width' => 50, 'image_height' => 50, 'postmeta' => true, 'postexcerpt' => true, 'excerpt_length' => 75 );
		$instance = wp_parse_args( (array) $instance, $defaults );
		prima_widget_input_text( __('Title:', 'primathemes'), $this->get_field_id( 'title' ), $this->get_field_name( 'title' ), $instance['title'] );
		prima_widget_input_text_small( __('Number of posts to show:', 'primathemes'), $this->get_field_id( 'number' ), $this->get_field_name( 'number' ), $instance['number'] );
		prima_widget_input_checkbox( __( 'Show image', 'primathemes' ), $this->get_field_id( 'image' ), $this->get_field_name( 'image' ), checked( $instance['image'], true, false ) );
		prima_widget_input_text_small( __('Image width (px):', 'primathemes'), $this->get_field_id( 'image_width' ), $this->get_field_name( 'image_width' ), $instance['image_width'] );
		prima_widget_input_text_small( __('Image height (px):', 'primathemes'), $this->get_field_id( 'image_height' ), $this->get_field_name( 'image_height' ), $instance['image_height'] );
		prima_widget_input_checkbox( __( 'Show post meta', 'primathemes' ), $this->get_field_id( 'postmeta' ), $this->get_field_name( 'postmeta' ), checked( $instance['postmeta'], true, false ) );
		prima_widget_input_checkbox( __( 'Show post excerpt', 'primathemes' ), $this->get_field_id( 'postexcerpt' ), $this->get_field_name( 'postexcerpt' ), checked( $instance['postexcerpt'], true, false ) );
		prima_widget_input_text_small( __('Post excerpt length:', 'primathemes'), $this->get_field_id( 'excerpt_length' ), $this->get_field_name( 'excerpt_length' ), $instance['excerpt_length'] );
	}
}

/**
 * Prima Recent Comments Widget class
 *
 * @since PrimaThemes 2.0
 */
class Prima_RecentComments_Widget extends WP_Widget {
	public function __construct() {
		$widget_ops = array( 'classname' => 'prima_recent_comments', 'description' => __('Display most recent comments', 'primathemes') );
		$control_ops = array( 'id_base' => 'prima-recent-comments' );
		parent::__construct( 'prima-recent-comments', __('Advanced Recent Comments', 'primathemes'), $widget_ops, $control_ops );
		$this->alt_option_name = 'prima_recent_comments';
		add_action( 'comment_post', array(&$this, 'flush_widget_cache') );
		add_action( 'transition_comment_status', array(&$this, 'flush_widget_cache') );
	}
	public function flush_widget_cache() {
		wp_cache_delete('prima_recent_comments', 'widget');
	}
	public function widget( $args, $instance ) {
		global $comments, $comment;
		$cache = wp_cache_get('prima_recent_comments', 'widget');
		if ( ! is_array( $cache ) )
			$cache = array();
		if ( isset( $cache[$args['widget_id']] ) ) {
			echo $cache[$args['widget_id']];
			return;
		}
		extract( $args );
		$title = apply_filters('widget_title', $instance['title'] );
		$number = (int)$instance['number'];
		$avatar = $instance['avatar'] ? '1' : '0';
		$avatar_size = (int)$instance['avatar_size'];
		$excerpt_length = (int)$instance['excerpt_length'];
 		$output = '';
		$output .= $before_widget;
		if ( $title ) $output .= $before_title . $title . $after_title;
		$comments = get_comments(array( 'number' => $number, 'status' => 'approve', 'type' => 'comment' ));
		if ($comments) {
			$output .= '<ul>';
			foreach ($comments as $comment) :
				$comment_link = get_comment_link($comment->comment_ID);
				$output .= ( $avatar ? '<li class="comment-with-avatar">' : '<li class="group">' );
				if ( $avatar ) $output .= '<a href="'. $comment_link.'">'.get_avatar($comment, $size=$avatar_size).'</a>';
				$output .= '<a href="'.$comment_link.'"><strong>'.$comment->comment_author.'</strong>:</a> '.substr(get_comment_excerpt( $comment->comment_ID ), 0, $excerpt_length).'&hellip;';
				$output .= '</li>'; 
			endforeach;
			$output .= '</ul>';
		}
		else {
			$output .= __( 'No comments were found', 'primathemes' );
		}
		$output .= $after_widget;
		echo $output;
		$cache[$args['widget_id']] = $output;
		wp_cache_set('prima_recent_comments', $cache, 'widget');
	}
	public function update( $new_instance, $old_instance ) {
		$instance = $old_instance;
		$instance['title'] = strip_tags( $new_instance['title'] );
		$instance['number'] = ( (int)$new_instance['number'] > 0 ? (int)$new_instance['number'] : '3' );
		$instance['avatar'] = ( isset( $new_instance['avatar'] ) ? 1 : 0 );
		$instance['avatar_size'] = ( (int)$new_instance['avatar_size'] > 0 ? (int)$new_instance['avatar_size'] : '48' );
		$instance['excerpt_length'] = ( (int)$new_instance['excerpt_length'] > 0 ? (int)$new_instance['excerpt_length'] : '75' );
		return $instance;
	}
	public function form( $instance ) {
		$defaults = array( 'title' => 'Recent Comments', 'number' => 3, 'avatar' => true, 'avatar_size' => 48, 'excerpt_length' => 75 );
		$instance = wp_parse_args( (array) $instance, $defaults );
		prima_widget_input_text( __('Title:', 'primathemes'), $this->get_field_id( 'title' ), $this->get_field_name( 'title' ), $instance['title'] );
		prima_widget_input_text_small( __('Number of comments to show:', 'primathemes'), $this->get_field_id( 'number' ), $this->get_field_name( 'number' ), $instance['number'] );
		prima_widget_input_checkbox( __( 'Show avatar', 'primathemes' ), $this->get_field_id( 'avatar' ), $this->get_field_name( 'avatar' ), checked( $instance['avatar'], true, false ) );
		prima_widget_input_text_small( __('Avatar size (px):', 'primathemes'), $this->get_field_id( 'avatar_size' ), $this->get_field_name( 'avatar_size' ), $instance['avatar_size'] );
		prima_widget_input_text_small( __('Comment excerpt length:', 'primathemes'), $this->get_field_id( 'excerpt_length' ), $this->get_field_name( 'excerpt_length' ), $instance['excerpt_length'] );
	}
}

/**
 * Prima Search Forms Widget class
 *
 * @since PrimaThemes 2.0
 */
class Prima_SearchForm_Widget extends WP_Widget {
	public function __construct() {
		$widget_ops = array( 'classname' => 'prima_searchform', 'description' => __('Display search form', 'primathemes') );
		$control_ops = array( 'id_base' => 'prima-searchform' );
		parent::__construct( 'prima-searchform', __('Advanced Search Form', 'primathemes'), $widget_ops, $control_ops );
	}
	public function widget( $args, $instance ) {
		extract( $args );
		$title = apply_filters('widget_title', $instance['title'] );
		echo $before_widget;
		if ( $title ) echo $before_title . $title . $after_title;
		$attr = array( 'search_text' => $instance['search_text'], 'button_text' => $instance['button_text'], 'echo' => true );
		prima_search_form( $attr );
		echo $after_widget;
	}
	public function update( $new_instance, $old_instance ) {
		$instance = $old_instance;
		$instance['title'] = strip_tags( $new_instance['title'] );
		$instance['search_text'] = strip_tags( $new_instance['search_text'] );
		$instance['button_text'] = strip_tags( $new_instance['button_text'] );
		return $instance;
	}
	public function form( $instance ) {
		$defaults = array( 'title' => '', 'search_text' => __('Search this website&hellip;', 'primathemes'), 'button_text' => __( 'Search', 'primathemes' ) );
		$instance = wp_parse_args( (array) $instance, $defaults );
		prima_widget_input_text( __('Title:', 'primathemes'), $this->get_field_id( 'title' ), $this->get_field_name( 'title' ), $instance['title'] );
		prima_widget_input_text( __('Input text:', 'primathemes'), $this->get_field_id( 'search_text' ), $this->get_field_name( 'search_text' ), $instance['search_text'] );
		prima_widget_input_text( __('Button text:', 'primathemes'), $this->get_field_id( 'button_text' ), $this->get_field_name( 'button_text' ), $instance['button_text'] );
	}
}
