
<!-- admin styles -->

<style>
div.updated{display:inline-block;position:absolute;top:12px;right:12px;border-bottom:0}h2 .nav-tab{font-size:16px}#icon-themes{display:none}#optionsframework{border:none;max-width:none}#optionsframework h3{display:none}#optionsframework mark{padding:0 3px;background:#d4e7f9}#optionsframework-submit{-moz-border-radius:3px;-webkit-border-radius:3px;border-radius:3px;border:solid 1px #ddd}#optionsframework .group{overflow:hidden}#optionsframework .section{padding:10px 0 25px 0;margin:0 10px;min-height:20px;border-top:solid 1px #eee;margin-top:-1px}#optionsframework .section .option{position:relative;top:10px;margin-left:160px}#optionsframework .section .heading{border:0;font-size:14px;display:inline-block;width:140px;line-height:1.25em;position:absolute}#optionsframework .section .controls{margin-bottom:5px;width:inherit}#optionsframework .section .controls input.upload_button{float:none}#optionsframework .section .explain{clear:both;max-width:550px}#optionsframework .controls input:focus,#optionsframework .controls textarea:focus{border-color:#d4e7f9}#optionsframework .sub.section:not(.result){border:0;margin-top:-20px}#optionsframework .sub.section:not(.result) h4{display:none}#search-field{font-size:13px;-webkit-border-radius:20px;-moz-border-radius:20px;border-radius:20px;margin-right:10px;border:solid 1px #ddd;float:left;margin-top:5px;padding:2px 10px;outline:0;width:130px;font-family:"HelveticaNeue-Light","Helvetica Neue Light","Helvetica Neue",Helvetica,Arial,sans-serif}#search-field:focus{border-color:#d4e7f9;-webkit-box-shadow:0 0 4px #379;-moz-box-shadow:0 0 4px #379;box-shadow:0 0 4px #379}#optionsframework.filtered .group{display:block !important}#optionsframework.filtered .section{display:none}#optionsframework.filtered .section.result{display:block}
</style>

<!-- admin scripts -->

<script>
; (function($){jQuery.noConflict();var d=null;$(document).ready(function(){d=$('#optionsframework');$('.autoselect input[type="text"]',d).click(function(){this.select();return false});e.init()});var e={autoFocus:true,timeout:350,defaultTitle:'Search options…',$s:null,sections:[],firstSearch:true,activeTabClass:'nav-tab-active',$activeTab:null,init:function(){this.$s=$('<input/>',{id:'search-field','placeholder':this.defaultTitle,'class':'code'});$('h2.nav-tab-wrapper').prepend(this.$s);this.$s.siblings('a').click(this.tabClick);var c=null,handleSearch=function(a){var b=function(){if(e.firstSearch&&!e.$s.val())return;e.changed(e.$s.val().toLowerCase())};clearTimeout(c);c=setTimeout(b,e.timeout)};this.fillSections();this.$s.keyup(handleSearch);this.$s[0].onclick=function(){this.select()};if(this.autoFocus)this.$s.focus()},tabClick:function(a){a.stopPropagation();if(e.firstSearch)return;e.updActiveTab();e.$s.click();a.stopPropagation()},fillSections:function(){d.find('.section').each(function(i,s){var a=$(s);e.sections.push({obj:a,txt:a.text().toLowerCase()})})},changed:function(a){if(this.firstSearch)this.prepareEnv();a=jQuery.trim(a);if(!a)this.clearEnv();else this.search(a)},search:function(a){this.clearResults();var b=0;for(var i=this.sections.length-1;i>=0;i--){var s=this.sections[i],ind=s.txt.indexOf(a);if(ind>-1){s.obj.addClass('result');s.obj.find('h4').contents().wrap('<mark/>');b++}};if(!b)this.clearEnv()},updActiveTab:function(){this.$activeTab=$('h2 .'+this.activeTabClass).removeClass(this.activeTabClass)},prepareEnv:function(){this.firstSearch=false;this.updActiveTab();d.addClass('filtered')},clearResults:function(){d.find('.section.result').removeClass('result').find('h4 mark').contents().unwrap()},clearEnv:function(a){this.clearResults();this.firstSearch=true;d.removeClass('filtered');this.$activeTab.trigger('click')}}})(jQuery);
</script>

<!-- /end of admin scripts & styles -->
