<?php

// Earth
$earth = array(
	"alt"		=> "Earth", 
	"img"		=> trailingslashit( get_template_directory_uri() ) ."inc/redux-framework/images/earth.jpg",
	"presets"   => array(
		
		"preloader-bg-color" => "#000000",
		"preloader-color" => "#b1986a",
		"lightbox-background-color" => "#000000",
		"lightbox-arrow-color" => "#b1986a",
		"media-player-time-bar" => "#ffffff",
		"nav-bg-color" => array( "color" => "#000000", "alpha" => "1", "rgba" => "rgba(0,0,0,1)" ),
		"nav-text-color" => "#b1986a",
		"nav-text-hover-color" => "#70513c",
		"panel-bg-color" => "#000000",
		"panel-link-color" => "#b1986a",
		"panel-link-hover-color" => "#70513c",
		"panel-link-bg-hover-color" => "transparent",
		"panel-submenu-bg-color" => "#FFFFFF",
		"panel-submenu-link-color" => "#b1986a",
		"panel-submenu-link-hover-color" => "#70513c",
		"panel-submenu-link-bg-hover-color" => "transparent",
		"pagination-border-color" => array( "color" => "#b1986a", "alpha" => "1", "rgba" => "rgba(177,152,106,1)" ),
		"pagination-fill-color" => "#b1986a",
		"pagination-text-color" => "#b1986a",
		
		"scheme-1-label" => "Content",
		"scheme-1-accent-color" => "#b1986a",
		"scheme-1-background-color" => "#0f0f0f",
		"scheme-1-page-label-color" => array( "color" => "#ffffff", "alpha" => "1", "rgba" => "rgba(255,255,255,1)" ),
		"scheme-1-page-title-color" => "#ffffff",
		"scheme-1-page-subtitle-color" => array( "color" => "#ffffff", "alpha" => "0.6", "rgba" => "rgba(255,255,255,0.6)" ),
		"scheme-1-h1-color" => "#b1986a",
		"scheme-1-h2-color" => "#b1986a",
		"scheme-1-h3-color" => "#b1986a",
		"scheme-1-h4-color" => "#b1986a",
		"scheme-1-h5-color" => "#b1986a",
		"scheme-1-h6-color" => "#b1986a",
		"scheme-1-text-color" => array( "color" => "#afafaf", "alpha" => "1", "rgba" => "rgba(175,175,175,1)" ),
		"scheme-1-subtext-color" => array( "color" => "#afafaf", "alpha" => "0.7", "rgba" => "rgba(175,175,175,0.7)" ),
		"scheme-1-link-color" => "#b1986a",
		"scheme-1-link-hover-color" => "#70513c",
		"scheme-1-slider-arrow-color" => array( "color" => "#ffffff", "alpha" => "0.35", "rgba" => "rgba(255,255,255,0.35)" ),
		"scheme-1-slider-arrow-border-color" => array( "color" => "#ffffff", "alpha" => "0.2", "rgba" => "rgba(255,255,255,0.2)" ),
		"scheme-1-slider-pagination-border-color" => array( "color" => "#b1986a", "alpha" => "1", "rgba" => "rgba(177,152,106,1)" ),
		"scheme-1-slider-pagination-fill-color" => "#ffffff",
		"scheme-1-table-header-color" => "#000000",
		"scheme-1-table-header-text-color" => "#ffffff",
		"scheme-1-table-bg-color" => "#000000",
		"scheme-1-table-text-color" => "#afafaf",
		"scheme-1-input-text-color" => array( "color" => "#afafaf", "alpha" => "1", "rgba" => "rgba(175,175,175,1)" ),
		"scheme-1-input-border-color" => array( "color" => "#ffffff", "alpha" => "0.2", "rgba" => "rgba(255,255,255,0.2)" ),
		"scheme-1-input-border-focused-color" => array( "color" => "#b1986a", "alpha" => "1", "rgba" => "rgba(177,152,106,1)" ),
		"scheme-1-divider-color" => array( "color" => "#ffffff", "alpha" => "0.2", "rgba" => "rgba(255,255,255,0.2)" ),
		"scheme-1-divider-text-color" => array( "color" => "#b1986a", "alpha" => "1", "rgba" => "rgba(177,152,106,1)" ),
		"scheme-1-gallery-caption-bg-color" => "#000000",
		"scheme-1-gallery-caption-icon-color" => "#b1986a",
		"scheme-1-gallery-caption-text-color" => "#ffffff",
		"scheme-1-button-color" => "#b1986a",
		"scheme-1-button-text-hover-color" => "#FFFFFF",
		"scheme-1-secondary-button-color" => "#999999",
		"scheme-1-secondary-button-text-hover-color" => "#ffffff",
		"scheme-1-quote-color" => array( "color" => "#afafaf", "alpha" => "1", "rgba" => "rgba(175,175,175,1)" ),
		"scheme-1-scroll-button-color" => "#b1986a",
		"scheme-1-tta-background-color" => "#000000",
		"scheme-1-tta-title-color" => "#ffffff",
		"scheme-1-tta-title-hover-color" => "#afafaf",
		"scheme-1-tta-text-color" => "#afafaf",
		"scheme-1-comments-navigation-arrow-color" => array( "color" => "#ffffff", "alpha" => "0.15", "rgba" => "rgba(255,255,255,0.15)" ),
		"scheme-1-comments-navigation-border-color" => array( "color" => "#ffffff", "alpha" => "0.1", "rgba" => "rgba(255,255,255,0.1)" ),
		"scheme-1-comments-navigation-arrow-hover-color" => "#ffffff",
		"scheme-1-comments-navigation-background-color" => "#000000",
		"scheme-1-comments-alt-background" => array( "color" => "#000000", "alpha" => "0.5", "rgba" => "rgba(0,0,0,0.5)" ),
		"scheme-2-label" => "Content Alt",
		
		"scheme-2-accent-color" => "#b1986a",
		"scheme-2-background-color" => "#000000",
		"scheme-2-page-label-color" => array( "color" => "#ffffff", "alpha" => "1", "rgba" => "rgba(255,255,255,1)" ),
		"scheme-2-page-title-color" => "#ffffff",
		"scheme-2-page-subtitle-color" => array( "color" => "#ffffff", "alpha" => "0.6", "rgba" => "rgba(255,255,255,0.6)" ),
		"scheme-2-h1-color" => "#b1986a",
		"scheme-2-h2-color" => "#b1986a",
		"scheme-2-h3-color" => "#b1986a",
		"scheme-2-h4-color" => "#b1986a",
		"scheme-2-h5-color" => "#b1986a",
		"scheme-2-h6-color" => "#b1986a",
		"scheme-2-text-color" => array( "color" => "#afafaf", "alpha" => "1", "rgba" => "rgba(175,175,175,1)" ),
		"scheme-2-subtext-color" => array( "color" => "#afafaf", "alpha" => "0.7", "rgba" => "rgba(175,175,175,0.7)" ),
		"scheme-2-link-color" => "#b1986a",
		"scheme-2-link-hover-color" => "#70513c",
		"scheme-2-slider-arrow-color" => array( "color" => "#ffffff", "alpha" => "0.35", "rgba" => "rgba(255,255,255,0.35)" ),
		"scheme-2-slider-arrow-border-color" => array( "color" => "#ffffff", "alpha" => "0.2", "rgba" => "rgba(255,255,255,0.2)" ),
		"scheme-2-slider-pagination-border-color" => array( "color" => "#b1986a", "alpha" => "1", "rgba" => "rgba(177,152,106,1)" ),
		"scheme-2-slider-pagination-fill-color" => "#ffffff",
		"scheme-2-table-header-color" => "#0f0f0f",
		"scheme-2-table-header-text-color" => "#ffffff",
		"scheme-2-table-bg-color" => "#0f0f0f",
		"scheme-2-table-text-color" => "#afafaf",
		"scheme-2-input-text-color" => array( "color" => "#afafaf", "alpha" => "1", "rgba" => "rgba(175,175,175,1)" ),
		"scheme-2-input-border-color" => array( "color" => "#ffffff", "alpha" => "0.2", "rgba" => "rgba(255,255,255,0.2)" ),
		"scheme-2-input-border-focused-color" => array( "color" => "#b1986a", "alpha" => "1", "rgba" => "rgba(177,152,106,1)" ),
		"scheme-2-divider-color" => array( "color" => "#ffffff", "alpha" => "0.2", "rgba" => "rgba(255,255,255,0.2)" ),
		"scheme-2-divider-text-color" => array( "color" => "#b1986a", "alpha" => "1", "rgba" => "rgba(177,152,106,1)" ),
		"scheme-2-gallery-caption-bg-color" => "#0f0f0f",
		"scheme-2-gallery-caption-icon-color" => "#b1986a",
		"scheme-2-gallery-caption-text-color" => "#ffffff",
		"scheme-2-button-color" => "#b1986a",
		"scheme-2-button-text-hover-color" => "#FFFFFF",
		"scheme-2-secondary-button-color" => "#999999",
		"scheme-2-secondary-button-text-hover-color" => "#ffffff",
		"scheme-2-quote-color" => array( "color" => "#afafaf", "alpha" => "1", "rgba" => "rgba(175,175,175,1)" ),
		"scheme-2-scroll-button-color" => "#b1986a",
		"scheme-2-tta-background-color" => "#0f0f0f",
		"scheme-2-tta-title-color" => "#ffffff",
		"scheme-2-tta-title-hover-color" => "#afafaf",
		"scheme-2-tta-text-color" => "#afafaf",
		"scheme-2-comments-navigation-arrow-color" => array( "color" => "#ffffff", "alpha" => "0.15", "rgba" => "rgba(255,255,255,0.15)" ),
		"scheme-2-comments-navigation-border-color" => array( "color" => "#ffffff", "alpha" => "0.1", "rgba" => "rgba(255,255,255,0.1)" ),
		"scheme-2-comments-navigation-arrow-hover-color" => "#ffffff",
		"scheme-2-comments-navigation-background-color" => "#0f0f0f",
		"scheme-2-comments-alt-background" => array( "color" => "#ffffff", "alpha" => "0.1", "rgba" => "rgba(255,255,255,0.1)" ),
		
		"scheme-3-label" => "Headers",
		"scheme-3-accent-color" => "#b1986a",
		"scheme-3-background-color" => "#000000",
		"scheme-3-page-label-color" => array( "color" => "#ffffff", "alpha" => "1", "rgba" => "rgba(255,255,255,1)" ),
		"scheme-3-page-title-color" => "#ffffff",
		"scheme-3-page-subtitle-color" => array( "color" => "#ffffff", "alpha" => "0.6", "rgba" => "rgba(255,255,255,0.6)" ),
		"scheme-3-h1-color" => "#ffffff",
		"scheme-3-h2-color" => "#ffffff",
		"scheme-3-h3-color" => "#ffffff",
		"scheme-3-h4-color" => "#ffffff",
		"scheme-3-h5-color" => "#ffffff",
		"scheme-3-h6-color" => "#ffffff",
		"scheme-3-text-color" => array( "color" => "#afafaf", "alpha" => "1", "rgba" => "rgba(175,175,175,1)" ),
		"scheme-3-subtext-color" => array( "color" => "#afafaf", "alpha" => "0.7", "rgba" => "rgba(175,175,175,0.7)" ),
		"scheme-3-link-color" => "#b1986a",
		"scheme-3-link-hover-color" => "#70513c",
		"scheme-3-slider-arrow-color" => array( "color" => "#ffffff", "alpha" => "0.35", "rgba" => "rgba(255,255,255,0.35)" ),
		"scheme-3-slider-arrow-border-color" => array( "color" => "#ffffff", "alpha" => "0.2", "rgba" => "rgba(255,255,255,0.2)" ),
		"scheme-3-slider-pagination-border-color" => array( "color" => "#b1986a", "alpha" => "1", "rgba" => "rgba(177,152,106,1)" ),
		"scheme-3-slider-pagination-fill-color" => "#ffffff",
		"scheme-3-table-header-color" => "#0f0f0f",
		"scheme-3-table-header-text-color" => "#ffffff",
		"scheme-3-table-bg-color" => "#0f0f0f",
		"scheme-3-table-text-color" => "#afafaf",
		"scheme-3-input-text-color" => array( "color" => "#afafaf", "alpha" => "1", "rgba" => "rgba(175,175,175,1)" ),
		"scheme-3-input-border-color" => array( "color" => "#ffffff", "alpha" => "0.2", "rgba" => "rgba(255,255,255,0.2)" ),
		"scheme-3-input-border-focused-color" => array( "color" => "#b1986a", "alpha" => "1", "rgba" => "rgba(177,152,106,1)" ),
		"scheme-3-divider-color" => array( "color" => "#ffffff", "alpha" => "0.2", "rgba" => "rgba(255,255,255,0.2)" ),
		"scheme-3-divider-text-color" => array( "color" => "#b1986a", "alpha" => "1", "rgba" => "rgba(177,152,106,1)" ),
		"scheme-3-gallery-caption-bg-color" => "#0f0f0f",
		"scheme-3-gallery-caption-icon-color" => "#b1986a",
		"scheme-3-gallery-caption-text-color" => "#ffffff",
		"scheme-3-button-color" => "#b1986a",
		"scheme-3-button-text-hover-color" => "#FFFFFF",
		"scheme-3-secondary-button-color" => "#999999",
		"scheme-3-secondary-button-text-hover-color" => "#ffffff",
		"scheme-3-quote-color" => array( "color" => "#afafaf", "alpha" => "1", "rgba" => "rgba(175,175,175,1)" ),
		"scheme-3-scroll-button-color" => "#b1986a",
		"scheme-3-tta-background-color" => "#0f0f0f",
		"scheme-3-tta-title-color" => "#ffffff",
		"scheme-3-tta-title-hover-color" => "#afafaf",
		"scheme-3-tta-text-color" => "#afafaf",
		"scheme-3-comments-navigation-arrow-color" => array( "color" => "#ffffff", "alpha" => "0.15", "rgba" => "rgba(255,255,255,0.15)" ),
		"scheme-3-comments-navigation-border-color" => array( "color" => "#ffffff", "alpha" => "0.1", "rgba" => "rgba(255,255,255,0.1)" ),
		"scheme-3-comments-navigation-arrow-hover-color" => "#ffffff",
		"scheme-3-comments-navigation-background-color" => "#0f0f0f",
		"scheme-3-comments-alt-background" => array( "color" => "#ffffff", "alpha" => "0.1", "rgba" => "rgba(255,255,255,0.1)" ),
		
		"scheme-4-label" => "Archives",
		"scheme-4-accent-color" => "#b1986a",
		"scheme-4-background-color" => "#000000",
		"scheme-4-page-label-color" => array( "color" => "#ffffff", "alpha" => "1", "rgba" => "rgba(255,255,255,1)" ),
		"scheme-4-page-title-color" => "#ffffff",
		"scheme-4-page-subtitle-color" => array( "color" => "#ffffff", "alpha" => "0.6", "rgba" => "rgba(255,255,255,0.6)" ),
		"scheme-4-h1-color" => "#ffffff",
		"scheme-4-h2-color" => "#ffffff",
		"scheme-4-h3-color" => "#ffffff",
		"scheme-4-h4-color" => "#ffffff",
		"scheme-4-h5-color" => "#ffffff",
		"scheme-4-h6-color" => "#ffffff",
		"scheme-4-text-color" => array( "color" => "#afafaf", "alpha" => "1", "rgba" => "rgba(175,175,175,1)" ),
		"scheme-4-subtext-color" => array( "color" => "#afafaf", "alpha" => "0.7", "rgba" => "rgba(175,175,175,0.7)" ),
		"scheme-4-link-color" => "#b1986a",
		"scheme-4-link-hover-color" => "#70513c",
		"scheme-4-slider-arrow-color" => array( "color" => "#ffffff", "alpha" => "0.35", "rgba" => "rgba(255,255,255,0.35)" ),
		"scheme-4-slider-arrow-border-color" => array( "color" => "#ffffff", "alpha" => "0.2", "rgba" => "rgba(255,255,255,0.2)" ),
		"scheme-4-slider-pagination-border-color" => array( "color" => "#b1986a", "alpha" => "1", "rgba" => "rgba(177,152,106,1)" ),
		"scheme-4-slider-pagination-fill-color" => "#ffffff",
		"scheme-4-table-header-color" => "#0f0f0f",
		"scheme-4-table-header-text-color" => "#ffffff",
		"scheme-4-table-bg-color" => "#0f0f0f",
		"scheme-4-table-text-color" => "#afafaf",
		"scheme-4-input-text-color" => array( "color" => "#afafaf", "alpha" => "1", "rgba" => "rgba(175,175,175,1)" ),
		"scheme-4-input-border-color" => array( "color" => "#ffffff", "alpha" => "0.2", "rgba" => "rgba(255,255,255,0.2)" ),
		"scheme-4-input-border-focused-color" => array( "color" => "#b1986a", "alpha" => "1", "rgba" => "rgba(177,152,106,1)" ),
		"scheme-4-divider-color" => array( "color" => "#ffffff", "alpha" => "0.2", "rgba" => "rgba(255,255,255,0.2)" ),
		"scheme-4-divider-text-color" => array( "color" => "#b1986a", "alpha" => "1", "rgba" => "rgba(177,152,106,1)" ),
		"scheme-4-gallery-caption-bg-color" => "#0f0f0f",
		"scheme-4-gallery-caption-icon-color" => "#b1986a",
		"scheme-4-gallery-caption-text-color" => "#ffffff",
		"scheme-4-button-color" => "#b1986a",
		"scheme-4-button-text-hover-color" => "#FFFFFF",
		"scheme-4-secondary-button-color" => "#999999",
		"scheme-4-secondary-button-text-hover-color" => "#ffffff",
		"scheme-4-quote-color" => array( "color" => "#afafaf", "alpha" => "1", "rgba" => "rgba(175,175,175,1)" ),
		"scheme-4-scroll-button-color" => "#b1986a",
		"scheme-4-tta-background-color" => "#0f0f0f",
		"scheme-4-tta-title-color" => "#ffffff",
		"scheme-4-tta-title-hover-color" => "#afafaf",
		"scheme-4-tta-text-color" => "#afafaf",
		"scheme-4-comments-navigation-arrow-color" => array( "color" => "#ffffff", "alpha" => "0.15", "rgba" => "rgba(255,255,255,0.15)" ),
		"scheme-4-comments-navigation-border-color" => array( "color" => "#ffffff", "alpha" => "0.1", "rgba" => "rgba(255,255,255,0.1)" ),
		"scheme-4-comments-navigation-arrow-hover-color" => "#ffffff",
		"scheme-4-comments-navigation-background-color" => "#0f0f0f",
		"scheme-4-comments-alt-background" => array( "color" => "#ffffff", "alpha" => "0.1", "rgba" => "rgba(255,255,255,0.1)" ),
		
		"footer-bg-color" => "#0f0f0f",
		"footer-border-color" => array( "color" => "#ffffff", "alpha" => "0.01", "rgba" => "rgba(255,255,255,0.01)" ),
		"footer-widget-title-color" => "#b1986a",
		"footer-text-color" => "#444444",
		"footer-link-color" => "#b1986a",
		"footer-link-hover-color" => "#70513c",
		"footer-top-link-color" => array( "color" => "#ffffff", "alpha" => "0.15", "rgba" => "rgba(255,255,255,0.15)" ),
		"footer-top-link-border-color" => array( "color" => "#ffffff", "alpha" => "0.1", "rgba" => "rgba(255,255,255,0.1)" ),
		"footer-top-link-hover-color" => "#ffffff",
		"footer-top-link-background-hover-color" => "#b1986a",
		"footer-input-text-color" => array( "color" => "#444444", "alpha" => "1", "rgba" => "rgba(68,68,68,1)" ),
		"footer-input-border-color" => array( "color" => "#ffffff", "alpha" => "0.2", "rgba" => "rgba(255,255,255,0.2)" ),
		"footer-input-border-focus-color" => array( "color" => "#b1986a", "alpha" => "1", "rgba" => "rgba(177,152,106,1)" ),
		
		"blog-transparent-nav-text-color"		=> "#b1986a",
		"search-transparent-nav-text-color"		=> "#b1986a",
		"portfolio-transparent-nav-text-color"	=> "#b1986a",
		"404-transparent-nav-text-color"		=> "#b1986a",
		
	)
);