<?php
/*
 * This file belongs to the YIT Framework.
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE (GPL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 */

return array(

    'border-1-top'    => '#header.skin3 #nav,
                         .blog.small .yit_post_meta,
                         .blog.masonry .yit_post_meta,
                         .single-product.woocommerce div.product div.summary form.cart,
                         .single-product.woocommerce div.product div.summary div[itemprop="description"],
                         .single-product.woocommerce div.product div.summary p.price,
                         .arrow-down:before,
                         .woocommerce table.shop_table.cart thead,
                         #payment,
                         #footer,
                         #inquiry-form,
                         #copyright .border,
                          .yit_shortcodes.recent-post .blog.small .yit_post_meta,
                         #yith-wcwl-form table.shop_table thead,
                         .woocommerce table.shop_table.order_details tfoot tr:last-child,
                         .woocommerce-page table.shop_table.my_account_orders thead,
                         .woocommerce .login-form-checkout,
                         .testimonials-slider,
                         #bbpress-forums div.bbp-reply-author .bbp-reply-ip',


    'border-1-bottom' => '#header-container .container .header-wrapper, #header.skin3 #nav,
                          .arrow:before,
                          .woocommerce #header-sidebar > div.yit_cart_widget .product_list_widget li,
                          #header-sidebar > div.yit_cart_widget .product_list_widget li,
                          .blog.big.single .yit_post_content.title,
                          .woocommerce-tabs ul.tabs,
                          #header.skin1 #header-row .header-wrapper,
                          .woocommerce-tabs #comments ol.commentlist li .comment-text,
                          .woocommerce table.shop_table.cart thead,
                          .woocommerce table.shop_table.cart tbody,
                          .woocommerce .cart-collaterals .cart_totals tbody tr.shipping,
                          #product-box .border.group p.price,
                          #my-account-sidebar ul li,
                          nav.woocommerce-MyAccount-navigation ul li,
                          #payment li,
                          .contact-info ul li,
                          .testimonials-slider,
                          #order_review table tbody,
                          .widget.contact-info ul li,
                          #order_review table tfoot tr.shipping,
                          #inquiry-form,
                          #product-box form.cart,
                          #yith-wcwl-form table.shop_table thead,
                          #yith-wcwl-form table.shop_table tbody,
                          .woocommerce table.shop_table.order_details thead,
                          .woocommerce table.shop_table.order_details tbody,
                          .widget.yit_products_category ul.product_list_widget li:after,
                          .widget.yit_products_category ul.product_list_widget li:before,
                          .woocommerce ul.product_list_widget li:after,
                          p.comment_arrow:after,
                          .woocommerce ul.cart_list.product_list_widget li:hover,
                          .widget.testimonial-widget .testimonial-description,
                          .woocommerce ul.product_list_widget li:before,
                          .woocommerce-page ul.product_list_widget li:after,
                          .woocommerce-page ul.product_list_widget li:before,
                          .woocommerce-page table.shop_table.my_account_orders thead,
                          .widget.yit-recent-comments div.comment,
                          .woocommerce .login-form-checkout,
                          .sidebar .widget.yit_text_image .clearfix.widget-wrap,
                          .widget_product_categories ul.product-categories > li,
                          .widget.widget_categories > ul > li,
                          .widget.yit_toggle_menu ul.menu > li,
                          .tabs-container ul.tabs,
                          .sidebar .widget.widget_nav_menu ul.menu > li,
                          .yit_post_quote,
                          #bbpress-forums li.bbp-body ul.forum,
                          #bbpress-forums li.bbp-body ul.topic,
                          #bbpress-forums li.bbp-body div.hentry,
                          #bbpress-forums #bbp-single-user-details #bbp-user-navigation li,
                          #buddypress div.item-list-tabs ul:after,
                          #buddypress div.item-list-tabs ul li a,
                          #buddypress div.item-list-tabs ul li span,
                          #buddypress #settings-form table tbody tr,
                          #buddypress table.notifications tbody tr,
                          #buddypress table#message-threads tr td,
                          #buddypress table#message-threads tr.read td,
                          #buddypress table#message-threads tr.unread td,
                          #buddypress table#message-threads tr.alt td,
                          .widget.widget_display_stats dt:after,
                          .widget.widget_display_replies ul li:after,
                          .widget.widget_display_topics ul li:after,
                          .widget.yit_recent_reviews .review-content,
                          .products-slider-wrapper h3.products-slider-title,
                          .st-menu ul li,
                          .widget.woocommerce.widget_layered_nav ul.yith-wcan-list li,
                          .widget.widget_recent_entries ul li,
                          .widget.widget_recent_comments ul li,
                          .woocommerce .coupon-form-checkout',

    'border-1-all'    => '.blog.big .thumbnail,
                          .blog.small .post-wrapper,
                          .blog.masonry .post-wrapper,
                          .blog input[type="password"],
                          #primary .owl-next i.fa.fa-angle-right,
                          #primary .owl-prev i.fa.fa-angle-left,
                          .blog.big.single .yit_post_meta.last_block,
                          .post.no-featured:not(.format-quote) .blog.big .yit_post_content,
                          .woocommerce ul.products li.product .product-wrapper,
                          .nav > ul > li div.submenu ul.sub-menu,
                          .nav > ul > li.bigmenu > div.submenu > ul > li,
                          #lang_sel > ul > li > ul,
                          .widget_search_mini .search_mini_content label.search_mini_label,
                          .yit_shortcodes.recent-post .blog.small .post-wrapper,
                          ul.products li.product .product-actions-wrapper .product-other-action.buttons_2 > div:first-child,
                          ul.products li.product .product-actions-wrapper .product-other-action.buttons_3 > div:first-child,
                          ul.products li.product .product-actions-wrapper .product-other-action.buttons_3 > div:last-child,
                          ul.products li.product .thumb-wrapper.zoom .attachments-thumbnail .single-attachment-thumbnail,
                          .woocommerce ul.product_list_widget li,
                          .post.format-quote .blog.big .yit_post_content,
                          .format-quote .blog.big .yit_the_content:after,
                          #comments ol li .content,
                          input[type="password"],
                          input[type="text"],
                          #comments ol li .avatar img,
                          #primary .testimonials-slider ul.testimonial-content div.owl-prev,
                          #primary .testimonials-slider ul.testimonial-content div.owl-next,
                          #commentform input:not([type=submit]),
                          #commentform .comment-form-comment #comment,
                          #header-sidebar > div.yit_cart_widget .product_list_widget img,
                          .woocommerce #header-sidebar > div.yit_cart_widget .product_list_widget img,
                          #header-row .yit-custom-megamenu ul.yit-cm > li > div.submenu > ul.sub-menu > li > div.submenu > ul.sub-menu,
                          #header-row .yit-custom-megamenu ul.yit-cm > li > div.submenu  ul.sub-menu,
                          .yit-vertical-megamenu .nav > ul > li div.submenu > ul.sub-menu > li > div.submenu > ul.sub-menu,
                          .yit-vertical-megamenu .nav > ul > li div.submenu  ul.sub-menu,
                          .yit-vertical-megamenu .nav,
                          #header-row .header-wrapper div.header-row-right .widget.yit_text_image,
                          #header-row .header-wrapper div.header-row-right .widget.widget_text,
                          #welcome-menu-login .login-box,
                          .woocommerce  #welcome-menu-login input[type="text"],
                          .woocommerce  #welcome-menu-login input[type="email"],
                          .woocommerce  #welcome-menu-login input[type="password"],
                          #header-row .select-wrapper,
                          #welcome-menu-login .login-box.with_registration .customer-login-box.customer-login-box1,
                          .widget_search_mini .nav-searchfield,
                          .widget_search_mini .search_mini_content label,
                          #popupWrap .product-share,
                          .wpb_column.border-right,
                          .widget.last-tweets p.arrow-left,
                          .woocommerce-tabs #comments ol.commentlist li,
                          .woocommerce-tabs #review_form_wrapper,
                          .woocommerce-tabs #review_form .comment-form-rating,
                          .woocommerce-page #product-nav > a,
                          .woocommerce .cart-collaterals,
                          .sidebar .widget_shopping_cart,
                          .sidebar .woocommerce .product_list_widget .mini-cart-thumb img,
                          .widget.yit-recent-posts .recent-post .hentry-post div.text,
                          #product-box,
                          .sbHolder .sbSelector,
                          .sbHolder .sbOptions,
                          .woocommerce input.input-text,
                          .woocommerce-page input.input-text,
                          #my-account-sidebar div.user-profile,
                          #my-account-sidebar ul,
                          nav.woocommerce-MyAccount-navigation div.user-profile,
                          nav.woocommerce-MyAccount-navigation ul,
                          div.widget.teaser .teaser-wrapper,
                          #my-account-sidebar .user-profile div.user-image,
                          nav.woocommerce-MyAccount-navigation .user-profile div.user-image,
                          .woocommerce form .form-row a.chosen-single,
                          .woocommerce form .form-row div.chosen-drop,
                          #review-order-wrapper,
                          .testimonial-wrapper,
                          .widget.widget_search #searchform,.woocommerce-product-search,
                          .woocommerce ul.order_details li,
                          .widget.widget_search #searchform #s,.woocommerce-product-search input[type="search"],
                          .widget .newsletter-widget ul,
                          #faqs-container .faq-wrapper,
                          #faqs-container .faq-icon,
                          .filters.faq li a,
                          .team-section .member,
                          .team-section .member-social,
                          .filters-container ul.filters li a,
                          #show-category-product ul.products li a.product-category-link,
                          .categories-slider ul.products li a.product-category-link,
                          .error-404-container .error-404-search input[type="text"],
                          #portfolio_big li,
                          #portfolio_big li .info .portfolio_meta:before,
                          #portfolio_small li .info,
                          .single-product.woocommerce div.product div.images > a > img,
                          .single-product.woocommerce div.product div.images .yith_magnifier_zoom_wrap > a > img,
                          .woocommerce form .form-row textarea,
                          .yit_quick_contact,
                          .widget.widget_price_filter #min_price,
                          .widget.widget_price_filter #max_price,
                          .contact-form li div.input-prepend input[type=text],
                          .contact-form li div.input-prepend input[type=password],
                          .contact-form li div.input-prepend select,
                          .contact-form li.textarea-field div.input-prepend textarea,
                          .woocommerce.widget.widget_product_search #searchform,.woocommerce-product-search,
                          #portfolio_content .portfolio_meta:after,
                          #portfolio_content .the_content.with-border:after,
                          #portfolio_content .testimonial-box.with-border:after,
                          .sidebar .widget.newsletter-form .newsletter-section form input[type="text"],
                          .widget.newsletter-form.with-border,
                          #portfolio_nav .prev a[rel=prev],
                          .arrow-left:before,
                          #portfolio_nav .next a[rel=next],
                          #portfolio_nav,
                          #portfolio_small li .info .portfolio-overlay:before,
                          .widget.yit_products_category ul.product_list_widget li,
                          .blog-section-wrapper ul.blog_posts li div.blog_post,
                          #bbp-search-form,
                          #bbpress-forums input[type="text"],
                          .bbp_widget_login input[type="text"],
                          .bbp_widget_login input[type="password"],
                          #bbpress-forums div.bbp-the-content-wrapper,
                          #bbpress-forums li.bbp-body div.bbp-reply-content,
                          #bbpress-forums div.bbp-reply-author img.avatar,
                          #bbpress-forums #bbp-single-user-details #bbp-user-avatar img.avatar,
                          #bbpress-forums li.bbp-body div.bbp-reply-content:before,
                          #bbpress-forums #bbp-single-user-details,
                          .price-table,
                          #buddypress div.dir-search label input[type="text"],
                          #buddypress div.item-list-tabs ul li.current a,
                          #buddypress div.item-list-tabs ul li.selected a,
                          #buddypress ul li .item-container,
                          #buddypress form#whats-new-form textarea,
                          #buddypress #search-message-form label input[type="text"],
                          form.variations_form.cart td.value .select_option,
                          .call-to-action-two,
                          .call-three,
                          .newsletter_form_email input.email-field,
                          .toggle,
                          .toggle .toggle-title span.fa.fa-plus.closed,
                          .toggle .toggle-title span.fa.fa-minus.opened,
                          .widget.yith-woo-ajax-navigation ul.yith-wcan-color li a,
                          .widget.yith-woo-ajax-navigation ul.yith-wcan-label li a,
                          .logos-slider .list_carousel,
                          #show-category-product div.category-count:before,
                          .features-tab-container ul.features-tab-labels li,
                          .features-tab-container ul.features-tab-labels,
                          .widget.yit-recent-posts .recent-post .hentry-post,
                          .categories-slider div.category-count:before,
                          .wpb_widgetised_column .widget.newsletter-form .newsletter-section form input[type="text"],
                          .widget.newsletter-form.with-border,
                          .single-product.woocommerce div.product div.images .thumbnails a img,
                          #buddypress div.activity-comments form .ac-textarea,
                          .woocommerce-checkout .select2-container .select2-choice,.woocommerce-checkout .select2-drop-active,
                          .woocommerce-cart #calc_shipping_country,.woocommerce-cart #calc_shipping_state,.select2-drop.select2-drop-above.select2-drop-active,
                          .select2-dropdown-open.select2-drop-above .select2-choice, .select2-dropdown-open.select2-drop-above .select2-choices,
                          .select2-drop.select2-drop-above.select2-drop-active',

    'border-2-bottom' => '.parallaxeos_outer,
                           .woocommerce ul.product_list_widget li:hover:after,
                          .woocommerce ul.product_list_widget li:hover:before,
                          .woocommerce-page ul.product_list_widget li:hover:after,
                          .woocommerce-page ul.product_list_widget li:hover:before,
                          .features-tab-container ul.features-tab-labels li:hover,
                          .features-tab-container ul.features-tab-labels li.current-feature,
                          #bbpress-forums li.bbp-header,
                          #buddypress div.item-list-tabs#subnav > ul,
                          #buddypress #profile-edit-form ul.button-nav li.current a,
                          #buddypress #settings-form table thead tr,
                          #buddypress table.notifications thead tr',

    'border-2-top'    => '#welcome-menu-login .login-box, .yit_post_quote',

    'border-2-all'    => 'ul.products li.product .thumb-wrapper.zoom .attachments-thumbnail .single-attachment-thumbnail.active,
                          #comments ol li .avatar.is_author img,
                          #commentform input:not([type=submit]):focus,
                          #commentform .comment-form-comment #comment:focus,
                          #primary .testimonials-slider ul.testimonial-content div.owl-next:hover,
                          #primary .testimonials-slider ul.testimonial-content div.owl-prev:hover,
                          #product-nav > a:hover,
                          #portfolio_nav .prev a[rel=prev]:hover,
                          #portfolio_nav .next a[rel=next]:hover,
                          .filters.faq li a:hover,
                          .filters.faq li a.active,
                          .filters-container ul.filters li a:hover,
                          .filters-container ul.filters li a.active,
                          .dropcap,
                          .post.sticky .blog.big .yit_post_content,
                          .post.sticky.no-featured:not(.format-quote) .blog.big .yit_post_content,
                          .post.sticky .blog.small .post-wrapper,
                          form.variations_form.cart td.value .select_option:hover,
                          form.variations_form.cart td.value .select_option.selected,
                          .widget.yith-woo-ajax-navigation ul.yith-wcan-color li a:hover,
                          .widget.yith-woo-ajax-navigation ul.yith-wcan-label li a:hover,
                          .widget.yith-woo-ajax-navigation ul.yith-wcan-color li.chosen a,
                          .widget.yith-woo-ajax-navigation ul.yith-wcan-label li.chosen a,
                          .widget.yit_recent_reviews span.entypo:hover,
                          .single-product.woocommerce div.product div.images .thumbnails a img:hover',

    'a-tag'           => 'a,
                          a:visited,
                          #header #welcome-menu-login .lost_password a,
                          .nav  span.highlight,
                          .box-content a h2,
                          .woocommerce .login-form-checkout .woocommerce-info a,
                          .testimonials-slider ul.testimonial-content li p.meta a',

    'a-tag-hover'     => 'a:hover, a:active,
                        .product-actions-wrapper .product-other-action .yith-wcwl-add-to-wishlist:hover a,
                        .testimonials-slider ul.testimonial-content li p.meta a:hover,
                        .box-content a h2:hover,
                        .toggle .toggle-title h4:hover,
                        .toggle .toggle-title.tab-opened h4,
                        .toggle .toggle-title span.fa.fa-minus.opened:before,
                        #primary .testimonials-slider ul.testimonial-content div.owl-next:hover i:before,
                        #primary .testimonials-slider ul.testimonial-content div.owl-prev:hover i:before,
                        .product-actions-wrapper .product-other-action .compare-button:hover a,
                        .product-actions-wrapper .product-other-action .share-button:hover a,
                        #product-box .product-actions .compare-button:hover a,
                        #product-box .product-actions .yith-wcwl-add-to-wishlist:hover a,
                        .single-product.woocommerce div.product div.summary .product-actions div.yith-wcwl-add-to-wishlist:hover a,
                        .single-product.woocommerce div.product div.summary .product-actions div.compare-button:hover a,
                        .woocommerce .cart-collaterals .cart_totals h3,
                        #header #welcome-menu-login .lost_password a:hover,
                        .woocommerce table.cart td.product-name div.product-name-price div.product-name a:hover,
                        #product-nav > a:hover span.fa,
                        #my-account-sidebar ul li > a:hover,
                        #my-account-sidebar ul li > a.active,
                        nav.woocommerce-MyAccount-navigation ul li > a:hover,
                        nav.woocommerce-MyAccount-navigation ul li.is-active > a,
                        #order_review_heading,
                        #payment h3,
                        .widget.yit-recent-posts .recent-post span.num-comments a:hover,
                        .widget.yit-recent-posts .recent-post span.author a:hover,
                        #inquiry-form .product-inquiry:hover h4,
                        #yith-wcwl-form table.shop_table td.product-name a:hover,
                        table.shop_table.my_account_orders tbody td.order-number a:hover,
                        table.shop_table.order_details tr.order_item td.product-name a:hover,
                        nav.woocommerce-pagination li a:hover,
                        nav.woocommerce-pagination li span.current,
                        .products-slider-wrapper .es-nav span.fa:hover,
                        .categories-slider-wrapper .es-nav > *:hover span.fa,
                        #list-or-grid a.active i,
                        #list-or-grid a:hover i,
                        #number-of-products a.active,
                        #number-of-products a:hover,
                         .comments-info-wrapper span.author a,
                        .woocommerce ul.product_list_widget li:hover a span.product_title,
                        .widget.yit-recent-posts .recent-post .text > div.post-content > a.title:hover,
                        form.variations_form.cart a.reset_variations:hover,
                        #faqs-container .faq-wrapper .faq-title:hover h4,
                        #faqs-container .faq-wrapper .faq-title:hover span.entypo,
                        #faqs-container .faq-wrapper .faq-title.active span.entypo,
                        .widget.woocommerce.widget_recent_reviews ul.product_list_widget li:hover a,
                        .widget.woocommerce.widget_recent_reviews ul.product_list_widget li a:hover,
                        #faqs-container .faq-wrapper .faq-title.active h4,
                        #show-category-product a.product-category-link:hover h4,
                        .products-slider.categories a.product-category-link:hover h4,
                        #portfolio_big li .info h2.title a:hover,
                        #portfolio_nav .title .categories a:hover,
                        #portfolio_big li .info .categories a:hover,
                        #portfolio_small li .info .categories a:hover,
                        #portfolio_big li .info .portfolio_meta .meta_content a:hover,
                        #portfolio_content .portfolio_meta .meta_content a:hover,
                        #portfolio_nav div a[rel=prev]:hover .glyphicon,
                        #portfolio_nav div a[rel=next]:hover .glyphicon,
                        #portfolio_content .content-style-social a:hover,
                        #portfolio_small li .info h2.title a.title_link:hover,
                        .widget.testimonial-widget .ms-skin-default .ms-nav-next:hover,
                        .widget.testimonial-widget .ms-skin-default .ms-nav-prev:hover,
                        .woocommerce .login-form-checkout .woocommerce-info a:hover,
                        .widget.contact-info ul li:hover .info-container .contact_info_email h5,
                        .widget.yith-woo-ajax-navigation ul.yith-wcan-label li a:hover,
                        .widget.yith-woo-ajax-navigation ul.yith-wcan-label li.chosen a,
                        .widget.yith-woo-ajax-navigation ul.yith-wcan-list li:hover > *,
                        .widget.yith-woo-ajax-navigation ul.yith-wcan-list li.chosen > *,
                        .widget_product_categories ul a:hover,
                        #featured-slider .ms-nav-next:hover:after,
                        #featured-slider .ms-nav-prev:hover:after,
                        .widget_categories ul a:hover,
                        .widget_archive ul a:hover,
                        .widget_nav_menu ul a:hover,
                        .widget.widget_meta ul a:hover,
                        .widget_pages ul a:hover,
                        .widget.yit_products_category li:hover a span.product_title,
                        .widget.yit_toggle_menu ul.sub-menu li a:hover,
                        .widget.yit_toggle_menu ul.menu > li:hover > a,
                        .widget.yit_toggle_menu ul.menu > li.opened > a,
                        ul.blog_posts li div.blog_post .yit_post_meta span.info a:hover,
                        ul.blog_posts li div.blog_post .yit_post_meta span.title a:hover,
                        #bbpress-forums li.bbp-body ul li a:hover,
                        #bbpress-forums li.bbp-body ul.forum li.bbp-forum-info > a:hover,
                        #bbpress-forums li.bbp-body ul.topic li.bbp-topic-title > a:hover,
                        span.bbp-admin-links a:hover,
                        .bbp-reply-header a.bbp-reply-permalink:hover,
                        #bbpress-forums div.bbp-reply-author a.bbp-author-name:hover,
                        #bbpress-forums div.bbp-template-notice a:hover,
                        #bbp-user-navigation li a:hover,
                        #bbp-user-navigation li.current a,
                        a:hover[class^=eg-portfolio-masonry],
                        #buddypress div.item-list-tabs ul li.current a:hover,
                        #buddypress #activity-stream .activity-comments a:hover,
                        #buddypress #activity-stream p a:hover,
                        #buddypress #activity-stream p a:hover,
                        #buddypress #activity-stream .activity-comments .acomment-meta a:hover,
                        #buddypress ul li .item-container .item .item-username a:hover,
                        #buddypress ul#friend-list li .item .item-title a:hover,
                        #buddypress #message-recipients span a:hover,
                        #buddypress table.notifications tbody tr td a:hover,
                        #buddypress table#message-threads tr td.thread-info p:first-child a:hover,
                        #buddypress div.item-list-tabs ul li a:not(.sbToggle):hover,
                        #buddypress #item-nav div.item-list-tabs ul li.selected a,
                        #buddypress #item-nav div.item-list-tabs ul li.current a,
                        #buddypress #item-body div.item-list-tabs ul li.selected a,
                        #buddypress #item-body div.item-list-tabs ul li.current a,
                        .widget.widget_bp_core_members_widget.buddypress.widget .item-options a:hover,
                        .widget.widget_bp_groups_widget.buddypress.widget .item-options a:hover,
                        .widget.widget_bp_core_friends_widget.buddypress.widget .item-options a:hover,
                        .buddypress.widget ul li.vcard a:hover,
                        .buddypress.widget ul li.bp-single-group a:hover,
                        .widget.buddypress .bp-login-widget-user-links > div.bp-login-widget-user-link a:hover,
                        .widget a.bbp-author-name:hover,
                        .widget a.bbp-forum-title:hover,
                        .widget a.bbp-view-title:hover,
                        .widget a.bbp-reply-topic-title:hover,
                        .widget a.bbp-forum-title:hover,
                        .woocommerce ul.product_list_widget li a:hover,
                        .bbp-logged-in h4 a:hover,
                        .widget.testimonial-widget .ms-skin-default .ms-nav-next:hover:after,
                        .widget.testimonial-widget .ms-skin-default .ms-nav-prev:hover:after,
                        .widget.featured-products .flex-direction-nav li a:hover,
                        #product-nav a:hover span.glyphicon,
                        .modal-shortcode .modal-opener a:hover,
                        #primary .testimonials-slider ul.testimonial-content li p.meta span,
                        .widget.yit_recent_reviews .review-meta-avatar a:hover,
                        .widget.yit_recent_reviews span.entypo:hover,
                        .images-slider-sc .flex-direction-nav li a:hover:before,
                        .product-meta h3.product-name a:hover,
                        .woocommerce-product-rating a.woocommerce-review-link:hover,
                        .features-tab-container ul.features-tab-labels li.current-feature h4 a,
                        .features-tab-container ul.features-tab-labels li.current-feature:hover h4 a,
                        .features-tab-container ul.features-tab-labels li:hover h4 a,
                        .features-tab-container ul.features-tab-labels li h4 a:hover,
                        .sitemap a:hover,
                        .yith-woocompare-widget ul.products-list li a.title:hover,
                        .yith-woocompare-widget a.clear-all:hover,
                        .contact-info ul li:hover .info-container .contact_info_email h5,
                        .widget.widget_recent_entries ul li a:hover,
                        .widget h3 a.rsswidget:hover,
                        .widget.widget_rss ul li a.rsswidget:hover,
                        .widget_yith-wcwl-lists ul.dropdown > li.dropdown-section a:hover',

    'p-tag'           => 'p, body, time, dt, dd, td, th, address, .sbHolder a, #welcome-menu-login .lost_password a,
                          .testimonial-wrapper .testimonial-smallquote,
                          .nav span.highlight, .nav span.highlight-inverse,
                          table.shop_table.my_account_orders tbody td.order-number a,
                          .team-section .member-name,
                          .widget.testimonial-widget .ms-skin-default .ms-nav-next,
                          .widget.testimonial-widget .ms-skin-default .ms-nav-prev,
                          table.shop_table.order_details tr.order_item td.product-name a,
                          form.variations_form.cart a.reset_variations,
                          .filters-container ul.filters li .filter-category,
                          #portfolio_big li .info .categories a,
                          #portfolio_small li .info .categories a,
                          #portfolio_nav .title .categories a,
                          #portfolio_big li .info .portfolio_meta .meta_content a,
                          #portfolio_content .portfolio_meta .meta_content a,
                          #portfolio_nav div a .info .next_terms,
                          #portfolio_nav div a .info .prev_terms,
                          #portfolio_content .title,
                          #portfolio_content .content-style-social a,
                          #ship-to-different-address label,
                          .widget.widget_price_filter #min_price,
                          .widget.widget_price_filter #max_price,
                          .widget_price_filter .price_slider_amount .price_label,
                          .widget.widget_layered_nav ul li a,
                          ul.yith-wcan-list li a,
                          ul.yith-wcan-list li small,
                          .widget_product_categories ul a,
                          .widget_product_categories ul span,
                          #wp-calendar tfoot a,
                          .widget_categories ul a,
                          .widget_archive ul a,
                          .widget_nav_menu ul a,
                          .widget.widget_meta ul a,
                          .widget_pages ul a,
                          ul.short li,
                          ul.blog_posts li div.blog_post .yit_post_meta span.info a,
                          #bbpress-forums li.bbp-body ul li a,
                          #bbpress-forums .bbp-forum-info .bbp-forum-content,
                          .bbp-reply-post-date,
                          .bbp-author-role,
                          #bbpress-forums li.bbp-body .bbp-topic-voice-count,
                          #bbpress-forums li.bbp-body .bbp-topic-reply-count,
                          #bbpress-forums li.bbp-body .bbp-forum-reply-count,
                          #bbpress-forums li.bbp-body .bbp-forum-topic-count,
                          #buddypress div.dir-search label input[type="text"],
                          #buddypress #members-order-select a,
                          #buddypress #activity-stream p a,
                          #buddypress #activity-stream .activity-comments .acomment-meta a,
                          #buddypress #latest-update,
                          #buddypress div.item-list-tabs ul li .sbHolder a,
                          #buddypress .groups-members-search form label input[type="text"],
                          #buddypress #activity-stream li .activity-meta a.fav,
                          #buddypress #activity-stream li .activity-meta a.unfav,
                          #buddypress #message-recipients span,
                          #buddypress #message-recipients span a,
                          #buddypress table.notifications tbody tr td a,
                          #buddypress #search-message-form label input[type="text"],
                          #buddypress span.activity,
                          #buddypress div#message.info p,
                          #buddypress div#message.updated p,
                          #buddypress div#message p,
                          #sitewide-notice p,
                          #buddypress div#message.error p,
                          .widget.widget_bp_core_members_widget.buddypress.widget .item-options a,
                          .widget.widget_bp_groups_widget.buddypress.widget .item-options a,
                          .widget.widget_bp_core_friends_widget.buddypress.widget .item-options a,
                          .widget a.bbp-forum-title,
                          .widget a.bbp-view-title,
                          .widget a.bbp-reply-topic-title,
                          .widget a.bbp-forum-title,
                          .cx-form .cx-lead, .cx-form input, .cx-form textarea, .cx-form input:focus, .cx-form textarea:focus, .cx-widget .cx-line .cx-title,
                          .modal-shortcode .modal-opener a,
                          .widget.yit_recent_reviews .review-meta-avatar a,
                          .sitemap a,
                          .woocommerce-product-rating a.woocommerce-review-link,
                          .yith-woocompare-widget ul.products-list li a.title,
                          .yith-woocompare-widget a.clear-all,
                          .widget_yith-wcwl-lists ul.dropdown > li.dropdown-section a,
                          .woocommerce-tabs .ywsl-label,
                          #reviews #comments ol.commentlist li .comment-text > div.star-rating span'
);