<?php

class PGL_Widget_Categories extends WP_Widget_Categories
{
    function __construct() {
        $this->id_base = strtolower(_PREFIX_ . 'categories');
        $this->name = __('PixelGeekLabs Categories', PGL);
        $this->option_name = 'widget_' . $this->id_base;
        $this->widget_options = array( 'classname' => _PREFIX_ . 'widget_categories', 'description' => __( "A list or dropdown of categories ", PGL ) );
        $this->control_options = wp_parse_args( array(), array( 'id_base' => $this->id_base ) );
    }

    function widget( $args, $instance ) {
        $args['before_widget'] = '<div class="sidebar-box posts_by categorybox">';
        $args['before_title']  = '<h6 class="widget-title">';
        $args['after_title']   = '</h6>';
        parent::widget( $args, $instance ); // TODO: Change the autogenerated stub
    }
}

?>
