// Generated by CoffeeScript 1.4.0

(function($) {
  return $.fn.saChosen = function(settings, callback, chosenOptions) {
    var chosenXhr, defaultOptions, options, select;
    if (settings == null) {
      settings = {};
    }
    if (callback == null) {
      callback = {};
    }
    if (chosenOptions == null) {
      chosenOptions = function() {};
    }
    defaultOptions = {
        
    };
    select = this;
    chosenXhr = null;
    options = $.extend({}, defaultOptions, $(select).data(), settings);
    
    this.chosen(chosenOptions ? chosenOptions : {});
    return this.each(function() {
         //console.debug(select.data().chosen);
        select.trigger("liszt:updated");
        select.data().chosen.results_update_field();
        //lert(select.find('option').length);  
      
    });
  };
})(jQuery);
