<?php

$styles =  array(
															
	'Blue' => array(	
						'style'									=> 'background-color:#2d5c88;',
						'default_font' 							=> 'Helvetica-Neue,Helvetica-websave',
						'google_webfont' 						=> 'Open Sans',
						'color_scheme'							=> 'Blue',
						
						// header
						'colorset-header_color-bg'				=>'#ffffff',
						'colorset-header_color-bg2'				=>'#f8f8f8',
						'colorset-header_color-primary'			=>'#2d5c88',
						'colorset-header_color-secondary'		=>'#4686c2',
						'colorset-header_color-color'			=>'#333333',
						'colorset-header_color-border'			=>'#e1e1e1',
						'colorset-header_color-img'				=>'',
						'colorset-header_color-customimage'		=>'',
						'colorset-header_color-pos' 			=> 'center center',
						'colorset-header_color-repeat' 			=> 'repeat',
						'colorset-header_color-attach' 			=> 'scroll',
						
						// main
						'colorset-main_color-bg'				=>'#ffffff',
						'colorset-main_color-bg2'				=>'#f8f8f8',
						'colorset-main_color-primary'			=>'#2d5c88',
						'colorset-main_color-secondary'			=>'#4686c2',
						'colorset-main_color-color'				=>'#666666',
						'colorset-main_color-border'			=>'#e1e1e1',
						'colorset-main_color-img'				=>'',
						'colorset-main_color-customimage'		=>'',
						'colorset-main_color-pos' 				=> 'center center',
						'colorset-main_color-repeat' 			=> 'repeat',
						'colorset-main_color-attach' 			=> 'scroll',
						
						// alternate
						'colorset-alternate_color-bg'			=>'#f8f8f8',
						'colorset-alternate_color-bg2'			=>'#ffffff',
						'colorset-alternate_color-primary'		=>'#2d5c88',
						'colorset-alternate_color-secondary'	=>'#4686c2',
						'colorset-alternate_color-color'		=>'#888888',
						'colorset-alternate_color-border'		=>'#e1e1e1',
						'colorset-alternate_color-img'			=>'',
						'colorset-alternate_color-customimage'	=>'',
						'colorset-alternate_color-pos' 			=> 'center center',
						'colorset-alternate_color-repeat' 		=> 'repeat',
						'colorset-alternate_color-attach' 		=> 'scroll',
						
						// Slideshow
						'colorset-slideshow_color-bg'			=>'#fcfcfc',
						'colorset-slideshow_color-bg2'			=>'#f8f8f8',
						'colorset-slideshow_color-primary'		=>'#2d5c88',
						'colorset-slideshow_color-secondary'	=>'#4686c2',
						'colorset-slideshow_color-color'		=>'#666666',
						'colorset-slideshow_color-border'		=>'#e1e1e1',
						'colorset-slideshow_color-img'			=>'',
						'colorset-slideshow_color-customimage'	=>'',
						'colorset-slideshow_color-pos' 			=> 'center center',
						'colorset-slideshow_color-repeat' 		=> 'repeat',
						'colorset-slideshow_color-attach' 		=> 'scroll',
						
						// Footer
						'colorset-footer_color-bg'				=>'#333333',
						'colorset-footer_color-bg2'				=>'#222222',
						'colorset-footer_color-primary'			=>'#2d5c88',
						'colorset-footer_color-secondary'		=>'#4686c2',
						'colorset-footer_color-color'			=>'#aaaaaa',
						'colorset-footer_color-border'			=>'#555555',
						'colorset-footer_color-img'				=>'',
						'colorset-footer_color-customimage'		=>'',
						'colorset-footer_color-pos' 			=> 'center center',
						'colorset-footer_color-repeat' 			=> 'repeat',
						'colorset-footer_color-attach' 			=> 'scroll',
						
						// Socket
						'colorset-socket_color-bg'				=>'#111111',
						'colorset-socket_color-bg2'				=>'#000000',
						'colorset-socket_color-primary'			=>'#ffffff',
						'colorset-socket_color-secondary'		=>'#eeeeee',
						'colorset-socket_color-color'			=>'#eeeeee',
						'colorset-socket_color-border'			=>'#333333',
						'colorset-socket_color-img'				=>'',
						'colorset-socket_color-customimage'		=>'',
						'colorset-socket_color-pos' 			=> 'center center',
						'colorset-socket_color-repeat' 			=> 'repeat',
						'colorset-socket_color-attach' 			=> 'scroll',
						
						//body bg
						'color-body_style'						=>'stretched',
						'color-body_color'						=>'#ebebeb',
						'color-body_attach'						=>'scroll',
						'color-body_repeat'						=>'repeat',
						'color-body_pos'						=>'center center',
						'color-body_img'						=>'',
						'color-body_customimage'				=>'',
						),
	
	'Dark Orange' => array(	
						'style'									=> 'background-color:#f0591a;',
						'default_font' 							=> 'Open Sans',
						'google_webfont' 						=> 'Open Sans',
						'color_scheme'							=> 'Dark Orange',
						
						// header
						'colorset-header_color-bg'				=>'#ffffff',
						'colorset-header_color-bg2'				=>'#f8f8f8',
						'colorset-header_color-primary'			=>'#f0591a',
						'colorset-header_color-secondary'		=>'#ff7237',
						'colorset-header_color-color'			=>'#333333',
						'colorset-header_color-border'			=>'#e1e1e1',
						'colorset-header_color-img'				=>'',
						'colorset-header_color-customimage'		=>'',
						'colorset-header_color-pos' 			=> 'center center',
						'colorset-header_color-repeat' 			=> 'repeat',
						'colorset-header_color-attach' 			=> 'scroll',
						
						// main
						'colorset-main_color-bg'				=>'#ffffff',
						'colorset-main_color-bg2'				=>'#f8f8f8',
						'colorset-main_color-primary'			=>'#f0591a',
						'colorset-main_color-secondary'			=>'#f0591a',
						'colorset-main_color-color'				=>'#666666',
						'colorset-main_color-border'			=>'#e1e1e1',
						'colorset-main_color-img'				=>'',
						'colorset-main_color-customimage'		=>'',
						'colorset-main_color-pos' 				=> 'center center',
						'colorset-main_color-repeat' 			=> 'repeat',
						'colorset-main_color-attach' 			=> 'scroll',
						
						// alternate
						'colorset-alternate_color-bg'			=>'#f8f8f8',
						'colorset-alternate_color-bg2'			=>'#ffffff',
						'colorset-alternate_color-primary'		=>'#f0591a',
						'colorset-alternate_color-secondary'	=>'#f0591a',
						'colorset-alternate_color-color'		=>'#888888',
						'colorset-alternate_color-border'		=>'#e1e1e1',
						'colorset-alternate_color-img'			=>'',
						'colorset-alternate_color-customimage'	=>'',
						'colorset-alternate_color-pos' 			=> 'center center',
						'colorset-alternate_color-repeat' 		=> 'repeat',
						'colorset-alternate_color-attach' 		=> 'scroll',
						
						// Slideshow
						'colorset-slideshow_color-bg'			=>'#333333',
						'colorset-slideshow_color-bg2'			=>'#f8f8f8',
						'colorset-slideshow_color-primary'		=>'#f0591a',
						'colorset-slideshow_color-secondary'	=>'#f0591a',
						'colorset-slideshow_color-color'		=>'#ffffff',
						'colorset-slideshow_color-border'		=>'#e1e1e1',
						'colorset-slideshow_color-img'			=> AVIA_BASE_URL.'images/background-images/grain_bottom.png',	
						'colorset-slideshow_color-customimage'	=>'',
						'colorset-slideshow_color-pos' 			=> 'bottom center',
						'colorset-slideshow_color-repeat' 		=> 'repeat-x',
						'colorset-slideshow_color-attach' 		=> 'scroll',
						
						// Footer
						'colorset-footer_color-bg'				=>'#333333',
						'colorset-footer_color-bg2'				=>'#222222',
						'colorset-footer_color-primary'			=>'#f0591a',
						'colorset-footer_color-secondary'		=>'#f0591a',
						'colorset-footer_color-color'			=>'#aaaaaa',
						'colorset-footer_color-border'			=>'#555555',
						'colorset-footer_color-img'				=>AVIA_BASE_URL.'images/background-images/grain_top.png',
						'colorset-footer_color-customimage'		=>'',
						'colorset-footer_color-pos' 			=> 'top center',
						'colorset-footer_color-repeat' 			=> 'repeat-x',
						'colorset-footer_color-attach' 			=> 'scroll',
						
						// Socket
						'colorset-socket_color-bg'				=>'#111111',
						'colorset-socket_color-bg2'				=>'#000000',
						'colorset-socket_color-primary'			=>'#ffffff',
						'colorset-socket_color-secondary'		=>'#eeeeee',
						'colorset-socket_color-color'			=>'#eeeeee',
						'colorset-socket_color-border'			=>'#161616',
						'colorset-socket_color-img'				=>'',
						'colorset-socket_color-customimage'		=>'',
						'colorset-socket_color-pos' 			=> 'center center',
						'colorset-socket_color-repeat' 			=> 'repeat',
						'colorset-socket_color-attach' 			=> 'scroll',
						

						//body bg
						'color-body_style'						=>'stretched',
						'color-body_color'						=>'#ebebeb',
						'color-body_attach'						=>'scroll',
						'color-body_repeat'						=>'repeat',
						'color-body_pos'						=>'center center',
						'color-body_img'						=>'',
						'color-body_customimage'				=>'',
						),
						
						
								
						
	'Gradients Grey' => array(	
						'style'=>'background-color:#777777;',
						'default_font' => 'Open Sans',
						'google_webfont' => 'Open Sans',
						'color_scheme'	=>'Gradients Grey',
						
						// header
						'colorset-header_color-bg'				=>'#eeeeee',
						'colorset-header_color-bg2'				=>'#ffffff',
						'colorset-header_color-primary'			=>'#444444',
						'colorset-header_color-secondary'		=>'#4686c2',
						'colorset-header_color-color'			=>'#333333',
						'colorset-header_color-border'			=>'#e1e1e1',
						'colorset-header_color-img'				=>AVIA_BASE_URL.'images/background-images/gradient-top-light.png',
						'colorset-header_color-customimage'		=>'',
						'colorset-header_color-pos' 			=> 'top center',
						'colorset-header_color-repeat' 			=> 'repeat-x',
						'colorset-header_color-attach' 			=> 'scroll',
						
						// main
						'colorset-main_color-bg'				=>'#f8f8f8',
						'colorset-main_color-bg2'				=>'#eeeeee',
						'colorset-main_color-primary'			=>'#444444',
						'colorset-main_color-secondary'			=>'#4686c2',
						'colorset-main_color-color'				=>'#666666',
						'colorset-main_color-border'			=>'#e1e1e1',
						'colorset-main_color-img'				=>AVIA_BASE_URL.'images/background-images/gradient-top-light.png',
						'colorset-main_color-customimage'		=>'',
						'colorset-main_color-pos' 				=> 'top center',
						'colorset-main_color-repeat' 			=> 'repeat-x',
						'colorset-main_color-attach' 			=> 'scroll',
						
						// alternate
						'colorset-alternate_color-bg'			=>'#eeeeee',
						'colorset-alternate_color-bg2'			=>'#ffffff',
						'colorset-alternate_color-primary'		=>'#444444',
						'colorset-alternate_color-secondary'	=>'#4686c2',
						'colorset-alternate_color-color'		=>'#888888',
						'colorset-alternate_color-border'		=>'#e1e1e1',
						'colorset-alternate_color-img'			=> AVIA_BASE_URL.'images/background-images/gradient-top-light.png',
						'colorset-alternate_color-customimage'	=>'',
						'colorset-alternate_color-pos' 			=> 'top center',
						'colorset-alternate_color-repeat' 		=> 'repeat-x',
						'colorset-alternate_color-attach' 		=> 'scroll',
						
						// Slideshow
						'colorset-slideshow_color-bg'			=>'#333333',
						'colorset-slideshow_color-bg2'			=>'#f8f8f8',
						'colorset-slideshow_color-primary'		=>'#444444',
						'colorset-slideshow_color-secondary'	=>'#4686c2',
						'colorset-slideshow_color-color'		=>'#ffffff',
						'colorset-slideshow_color-border'		=>'#e1e1e1',
						'colorset-slideshow_color-img'			=>AVIA_BASE_URL.'images/background-images/gradient-bottom-light.png',
						'colorset-slideshow_color-customimage'	=>'',
						'colorset-slideshow_color-pos' 			=> 'bottom center',
						'colorset-slideshow_color-repeat' 		=> 'repeat-x',
						'colorset-slideshow_color-attach' 		=> 'scroll',
						
						// Footer
						'colorset-footer_color-bg'				=>'#333333',
						'colorset-footer_color-bg2'				=>'#222222',
						'colorset-footer_color-primary'			=>'#2d5c88',
						'colorset-footer_color-secondary'		=>'#4686c2',
						'colorset-footer_color-color'			=>'#aaaaaa',
						'colorset-footer_color-border'			=>'#555555',
						'colorset-footer_color-img'				=>AVIA_BASE_URL.'images/background-images/gradient-top-dark.png',
						'colorset-footer_color-customimage'		=>'',
						'colorset-footer_color-pos' 			=> 'top center',
						'colorset-footer_color-repeat' 			=> 'repeat-x',
						'colorset-footer_color-attach' 			=> 'scroll',
						
						// Socket
						'colorset-socket_color-bg'				=>'#111111',
						'colorset-socket_color-bg2'				=>'#000000',
						'colorset-socket_color-primary'			=>'#ffffff',
						'colorset-socket_color-secondary'		=>'#eeeeee',
						'colorset-socket_color-color'			=>'#eeeeee',
						'colorset-socket_color-border'			=>'#333333',
						'colorset-socket_color-img'				=>'',
						'colorset-socket_color-customimage'		=>'',
						'colorset-socket_color-pos' 			=> 'center center',
						'colorset-socket_color-repeat' 			=> 'repeat',
						'colorset-socket_color-attach' 			=> 'scroll',
						
						//body bg
						'color-body_style'						=>'streched',
						'color-body_color'						=>'',
						'color-body_attach'						=>'scroll',
						'color-body_repeat'						=>'repeat',
						'color-body_pos'						=>'center center',
						'color-body_img'						=>'',
						'color-body_customimage'				=>'',
						),			
	
					
	'Green' => array(	
						'style'=>'background-color:#719430;',
						'default_font' => 'Open Sans',
						'google_webfont' => 'Open Sans',
						'color_scheme'	=>'Green',
						
						// header
						'colorset-header_color-bg'				=>'#ffffff',
						'colorset-header_color-bg2'				=>'#f8f8f8',
						'colorset-header_color-primary'			=>'#719430',
						'colorset-header_color-secondary'		=>'#82a83d',
						'colorset-header_color-color'			=>'#333333',
						'colorset-header_color-border'			=>'#e1e1e1',
						'colorset-header_color-img'				=>'',
						'colorset-header_color-customimage'		=>'',
						'colorset-header_color-pos' 			=> 'center center',
						'colorset-header_color-repeat' 			=> 'repeat',
						'colorset-header_color-attach' 			=> 'scroll',
						
						// main
						'colorset-main_color-bg'				=>'#ffffff',
						'colorset-main_color-bg2'				=>'#f8f8f8',
						'colorset-main_color-primary'			=>'#719430',
						'colorset-main_color-secondary'			=>'#82a83d',
						'colorset-main_color-color'				=>'#666666',
						'colorset-main_color-border'			=>'#e1e1e1',
						'colorset-main_color-img'				=>'',
						'colorset-main_color-customimage'		=>'',
						'colorset-main_color-pos' 				=> 'center center',
						'colorset-main_color-repeat' 			=> 'repeat',
						'colorset-main_color-attach' 			=> 'scroll',
						
						// alternate
						'colorset-alternate_color-bg'			=>'#f8f8f8',
						'colorset-alternate_color-bg2'			=>'#ffffff',
						'colorset-alternate_color-primary'		=>'#719430',
						'colorset-alternate_color-secondary'	=>'#82a83d',
						'colorset-alternate_color-color'		=>'#888888',
						'colorset-alternate_color-border'		=>'#e1e1e1',
						'colorset-alternate_color-img'			=>'',
						'colorset-alternate_color-customimage'	=>'',
						'colorset-alternate_color-pos' 			=> 'center center',
						'colorset-alternate_color-repeat' 		=> 'repeat',
						'colorset-alternate_color-attach' 		=> 'scroll',
						
						// Slideshow
						'colorset-slideshow_color-bg'			=>'#333333',
						'colorset-slideshow_color-bg2'			=>'#f8f8f8',
						'colorset-slideshow_color-primary'		=>'#719430',
						'colorset-slideshow_color-secondary'	=>'#82a83d',
						'colorset-slideshow_color-color'		=>'#ffffff',
						'colorset-slideshow_color-border'		=>'#e1e1e1',
						'colorset-slideshow_color-img'			=> AVIA_BASE_URL.'images/background-images/grain_bottom.png',	
						'colorset-slideshow_color-customimage'	=>'',
						'colorset-slideshow_color-pos' 			=> 'bottom center',
						'colorset-slideshow_color-repeat' 		=> 'repeat-x',
						'colorset-slideshow_color-attach' 		=> 'scroll',
						
						// Footer
						'colorset-footer_color-bg'				=>'#333333',
						'colorset-footer_color-bg2'				=>'#222222',
						'colorset-footer_color-primary'			=>'#719430',
						'colorset-footer_color-secondary'		=>'#82a83d',
						'colorset-footer_color-color'			=>'#aaaaaa',
						'colorset-footer_color-border'			=>'#555555',
						'colorset-footer_color-img'				=>AVIA_BASE_URL.'images/background-images/grain_top.png',
						'colorset-footer_color-customimage'		=>'',
						'colorset-footer_color-pos' 			=> 'top center',
						'colorset-footer_color-repeat' 			=> 'repeat-x',
						'colorset-footer_color-attach' 			=> 'scroll',
						
						// Socket
						'colorset-socket_color-bg'				=>'#111111',
						'colorset-socket_color-bg2'				=>'#000000',
						'colorset-socket_color-primary'			=>'#ffffff',
						'colorset-socket_color-secondary'		=>'#eeeeee',
						'colorset-socket_color-color'			=>'#eeeeee',
						'colorset-socket_color-border'			=>'#161616',
						'colorset-socket_color-img'				=>'',
						'colorset-socket_color-customimage'		=>'',
						'colorset-socket_color-pos' 			=> 'center center',
						'colorset-socket_color-repeat' 			=> 'repeat',
						'colorset-socket_color-attach' 			=> 'scroll',
						
						//body bg
						'color-body_style'						=>'boxed',
						'color-body_color'						=>'#ebebeb',
						'color-body_attach'						=>'scroll',
						'color-body_repeat'						=>'repeat',
						'color-body_pos'						=>'center center',
						'color-body_img'						=>AVIA_BASE_URL.'images/background-images/floral-dark.png',
						'color-body_customimage'				=>'',
						),
						
		
	'Navy' => array(	
						'style'=>'background-color:#435960;',
						'default_font' => 'Arial-websave',
						'google_webfont' => 'Terminal Dosis',
						'color_scheme'	=>'Navy',
						
						// header
						'colorset-header_color-bg'				=>'#ffffff',
						'colorset-header_color-bg2'				=>'#f8f8f8',
						'colorset-header_color-primary'			=>'#435960',
						'colorset-header_color-secondary'		=>'#88bbc8',
						'colorset-header_color-color'			=>'#333333',
						'colorset-header_color-border'			=>'#e1e1e1',
						'colorset-header_color-img'				=>'',
						'colorset-header_color-customimage'		=>'',
						'colorset-header_color-pos' 			=> 'center center',
						'colorset-header_color-repeat' 			=> 'repeat',
						'colorset-header_color-attach' 			=> 'scroll',
						
						// main
						'colorset-main_color-bg'				=>'#ffffff',
						'colorset-main_color-bg2'				=>'#f8f8f8',
						'colorset-main_color-primary'			=>'#435960',
						'colorset-main_color-secondary'			=>'#88bbc8',
						'colorset-main_color-color'				=>'#666666',
						'colorset-main_color-border'			=>'#e1e1e1',
						'colorset-main_color-img'				=>'',
						'colorset-main_color-customimage'		=>'',
						'colorset-main_color-pos' 				=> 'center center',
						'colorset-main_color-repeat' 			=> 'repeat',
						'colorset-main_color-attach' 			=> 'scroll',
						
						// alternate
						'colorset-alternate_color-bg'			=>'#f8f8f8',
						'colorset-alternate_color-bg2'			=>'#ffffff',
						'colorset-alternate_color-primary'		=>'#435960',
						'colorset-alternate_color-secondary'	=>'#88bbc8',
						'colorset-alternate_color-color'		=>'#888888',
						'colorset-alternate_color-border'		=>'#e1e1e1',
						'colorset-alternate_color-img'			=>'',
						'colorset-alternate_color-customimage'	=>'',
						'colorset-alternate_color-pos' 			=> 'center center',
						'colorset-alternate_color-repeat' 		=> 'repeat',
						'colorset-alternate_color-attach' 		=> 'scroll',
						
						// Slideshow
						'colorset-slideshow_color-bg'			=>'#435960',
						'colorset-slideshow_color-bg2'			=>'#f8f8f8',
						'colorset-slideshow_color-primary'		=>'#4f9db0',
						'colorset-slideshow_color-secondary'	=>'#88bbc8',
						'colorset-slideshow_color-color'		=>'#ffffff',
						'colorset-slideshow_color-border'		=>'#e1e1e1',
						'colorset-slideshow_color-img'			=>AVIA_BASE_URL.'images/background-images/diagonal-bold-light.png',
						'colorset-slideshow_color-customimage'	=>'',
						'colorset-slideshow_color-pos' 			=> 'center center',
						'colorset-slideshow_color-repeat' 		=> 'repeat',
						'colorset-slideshow_color-attach' 		=> 'scroll',
						
						// Footer
						'colorset-footer_color-bg'				=>'#000000',
						'colorset-footer_color-bg2'				=>'#222222',
						'colorset-footer_color-primary'			=>'#ffffff',
						'colorset-footer_color-secondary'		=>'#ffffff',
						'colorset-footer_color-color'			=>'#aaaaaa',
						'colorset-footer_color-border'			=>'#555555',
						'colorset-footer_color-img'				=>'',
						'colorset-footer_color-customimage'		=>'',
						'colorset-footer_color-pos' 			=> 'top center',
						'colorset-footer_color-repeat' 			=> 'repeat-x',
						'colorset-footer_color-attach' 			=> 'scroll',
						
						// Socket
						'colorset-socket_color-bg'				=>'#435960',
						'colorset-socket_color-bg2'				=>'#000000',
						'colorset-socket_color-primary'			=>'#ffffff',
						'colorset-socket_color-secondary'		=>'#eeeeee',
						'colorset-socket_color-color'			=>'#eeeeee',
						'colorset-socket_color-border'			=>'#161616',
						'colorset-socket_color-img'				=>'',
						'colorset-socket_color-customimage'		=>'',
						'colorset-socket_color-pos' 			=> 'center center',
						'colorset-socket_color-repeat' 			=> 'repeat',
						'colorset-socket_color-attach' 			=> 'scroll',
						
						//body bg
						'color-body_style'						=>'boxed',
						'color-body_color'						=>'#eeeeee',
						'color-body_attach'						=>'scroll',
						'color-body_repeat'						=>'repeat',
						'color-body_pos'						=>'center center',
						'color-body_img'						=>AVIA_BASE_URL.'images/background-images/dots-for-light-background.png',
						'color-body_customimage'				=>'',
						

						),

	'Red' => array(	
						'style'=>'background-color:#a81010;',
						'default_font' => 'Arial-websave',
						'google_webfont' => 'Terminal Dosis',
						'color_scheme'	=>'Red',
						
						// header
						'colorset-header_color-bg'				=>'#ffffff',
						'colorset-header_color-bg2'				=>'#f8f8f8',
						'colorset-header_color-primary'			=>'#a81010',
						'colorset-header_color-secondary'		=>'#eb3b3b',
						'colorset-header_color-color'			=>'#333333',
						'colorset-header_color-border'			=>'#e1e1e1',
						'colorset-header_color-img'				=>'',
						'colorset-header_color-customimage'		=>'',
						'colorset-header_color-pos' 			=> 'center center',
						'colorset-header_color-repeat' 			=> 'repeat',
						'colorset-header_color-attach' 			=> 'scroll',
						
						// main
						'colorset-main_color-bg'				=>'#ffffff',
						'colorset-main_color-bg2'				=>'#f8f8f8',
						'colorset-main_color-primary'			=>'#a81010',
						'colorset-main_color-secondary'			=>'#eb3b3b',
						'colorset-main_color-color'				=>'#666666',
						'colorset-main_color-border'			=>'#e1e1e1',
						'colorset-main_color-img'				=>'',
						'colorset-main_color-customimage'		=>'',
						'colorset-main_color-pos' 				=> 'center center',
						'colorset-main_color-repeat' 			=> 'repeat',
						'colorset-main_color-attach' 			=> 'scroll',
						
						// alternate
						'colorset-alternate_color-bg'			=>'#f8f8f8',
						'colorset-alternate_color-bg2'			=>'#ffffff',
						'colorset-alternate_color-primary'		=>'#a81010',
						'colorset-alternate_color-secondary'	=>'#eb3b3b',
						'colorset-alternate_color-color'		=>'#888888',
						'colorset-alternate_color-border'		=>'#e1e1e1',
						'colorset-alternate_color-img'			=>'',
						'colorset-alternate_color-customimage'	=>'',
						'colorset-alternate_color-pos' 			=> 'center center',
						'colorset-alternate_color-repeat' 		=> 'repeat',
						'colorset-alternate_color-attach' 		=> 'scroll',
						
						// Slideshow
						'colorset-slideshow_color-bg'			=>'#111111',
						'colorset-slideshow_color-bg2'			=>'#f8f8f8',
						'colorset-slideshow_color-primary'		=>'#a81010',
						'colorset-slideshow_color-secondary'	=>'#eb3b3b',
						'colorset-slideshow_color-color'		=>'#ffffff',
						'colorset-slideshow_color-border'		=>'#e1e1e1',
						'colorset-slideshow_color-img'			=> AVIA_BASE_URL.'images/background-images/dashed-cross-light.png',	
						'colorset-slideshow_color-customimage'	=>'',
						'colorset-slideshow_color-pos' 			=> 'bottom center',
						'colorset-slideshow_color-repeat' 		=> 'repeat',
						'colorset-slideshow_color-attach' 		=> 'scroll',
						
						// Footer
						'colorset-footer_color-bg'				=>'#111111',
						'colorset-footer_color-bg2'				=>'#222222',
						'colorset-footer_color-primary'			=>'#a81010',
						'colorset-footer_color-secondary'		=>'#eb3b3b',
						'colorset-footer_color-color'			=>'#aaaaaa',
						'colorset-footer_color-border'			=>'#555555',
						'colorset-footer_color-img'				=>AVIA_BASE_URL.'images/background-images/grain_top.png',
						'colorset-footer_color-customimage'		=>'',
						'colorset-footer_color-pos' 			=> 'top center',
						'colorset-footer_color-repeat' 			=> 'repeat-x',
						'colorset-footer_color-attach' 			=> 'scroll',
						
						// Socket
						'colorset-socket_color-bg'				=>'#000000',
						'colorset-socket_color-bg2'				=>'#111111',
						'colorset-socket_color-primary'			=>'#ffffff',
						'colorset-socket_color-secondary'		=>'#eeeeee',
						'colorset-socket_color-color'			=>'#eeeeee',
						'colorset-socket_color-border'			=>'#161616',
						'colorset-socket_color-img'				=>'',
						'colorset-socket_color-customimage'		=>'',
						'colorset-socket_color-pos' 			=> 'center center',
						'colorset-socket_color-repeat' 			=> 'repeat',
						'colorset-socket_color-attach' 			=> 'scroll',
						

						//body bg
						'color-body_style'						=>'stretched',
						'color-body_color'						=>'#ebebeb',
						'color-body_attach'						=>'scroll',
						'color-body_repeat'						=>'repeat',
						'color-body_pos'						=>'center center',
						'color-body_img'						=>'',
						'color-body_customimage'				=>'',
						),
						
	'Purple' => array(	
						'style'									=>'background-color:#46424f;',
						'default_font' 							=> 'Helvetica-Neue,Helvetica-websave',
						'google_webfont' 						=> 'Muli',
						'color_scheme'							=>'Purple',
						
						// header
						'colorset-header_color-bg'				=>'#ffffff',
						'colorset-header_color-bg2'				=>'#f8f8f8',
						'colorset-header_color-primary'			=>'#46424f',
						'colorset-header_color-secondary'		=>'#594d75',
						'colorset-header_color-color'			=>'#333333',
						'colorset-header_color-border'			=>'#e1e1e1',
						'colorset-header_color-img'				=>'',
						'colorset-header_color-customimage'		=>'',
						'colorset-header_color-pos' 			=> 'center center',
						'colorset-header_color-repeat' 			=> 'repeat',
						'colorset-header_color-attach' 			=> 'scroll',
						
						// main
						'colorset-main_color-bg'				=>'#ffffff',
						'colorset-main_color-bg2'				=>'#f8f8f8',
						'colorset-main_color-primary'			=>'#46424f',
						'colorset-main_color-secondary'			=>'#594d75',
						'colorset-main_color-color'				=>'#666666',
						'colorset-main_color-border'			=>'#e1e1e1',
						'colorset-main_color-img'				=>'',
						'colorset-main_color-customimage'		=>'',
						'colorset-main_color-pos' 				=> 'center center',
						'colorset-main_color-repeat' 			=> 'repeat',
						'colorset-main_color-attach' 			=> 'scroll',
						
						// alternate
						'colorset-alternate_color-bg'			=>'#f8f8f8',
						'colorset-alternate_color-bg2'			=>'#ffffff',
						'colorset-alternate_color-primary'		=>'#46424f',
						'colorset-alternate_color-secondary'	=>'#594d75',
						'colorset-alternate_color-color'		=>'#888888',
						'colorset-alternate_color-border'		=>'#e1e1e1',
						'colorset-alternate_color-img'			=>'',
						'colorset-alternate_color-customimage'	=>'',
						'colorset-alternate_color-pos' 			=> 'center center',
						'colorset-alternate_color-repeat' 		=> 'repeat',
						'colorset-alternate_color-attach' 		=> 'scroll',
						
						// Slideshow
						'colorset-slideshow_color-bg'			=>'#fcfcfc',
						'colorset-slideshow_color-bg2'			=>'#f8f8f8',
						'colorset-slideshow_color-primary'		=>'#46424f',
						'colorset-slideshow_color-secondary'	=>'#594d75',
						'colorset-slideshow_color-color'		=>'#666666',
						'colorset-slideshow_color-border'		=>'#e1e1e1',
						'colorset-slideshow_color-img'			=>'',
						'colorset-slideshow_color-customimage'	=>'',
						'colorset-slideshow_color-pos' 			=> 'center center',
						'colorset-slideshow_color-repeat' 		=> 'repeat',
						'colorset-slideshow_color-attach' 		=> 'scroll',
						// Footer
						'colorset-footer_color-bg'				=>'#333333',
						'colorset-footer_color-bg2'				=>'#222222',
						'colorset-footer_color-primary'			=>'#46424f',
						'colorset-footer_color-secondary'		=>'#82a83d',
						'colorset-footer_color-color'			=>'#aaaaaa',
						'colorset-footer_color-border'			=>'#555555',
						'colorset-footer_color-img'				=>'',
						'colorset-footer_color-customimage'		=>'',
						'colorset-footer_color-pos' 			=> 'top center',
						'colorset-footer_color-repeat' 			=> 'repeat-x',
						'colorset-footer_color-attach' 			=> 'scroll',
						
						// Socket
						'colorset-socket_color-bg'				=>'#111111',
						'colorset-socket_color-bg2'				=>'#000000',
						'colorset-socket_color-primary'			=>'#ffffff',
						'colorset-socket_color-secondary'		=>'#eeeeee',
						'colorset-socket_color-color'			=>'#eeeeee',
						'colorset-socket_color-border'			=>'#161616',
						'colorset-socket_color-img'				=>'',
						'colorset-socket_color-customimage'		=>'',
						'colorset-socket_color-pos' 			=> 'center center',
						'colorset-socket_color-repeat' 			=> 'repeat',
						'colorset-socket_color-attach' 			=> 'scroll',
						
						//body bg
						'color-body_style'						=>'boxed',
						'color-body_color'						=>'#f8f8f8',
						'color-body_attach'						=>'scroll',
						'color-body_repeat'						=>'repeat',
						'color-body_pos'						=>'center center',
						'color-body_img'						=>AVIA_BASE_URL.'images/background-images/grunge-dark.png',
						'color-body_customimage'				=>'',
						),
						
							
											
	
						
	'Yellow' => array(	
						'style'=>'background-color:#f0b70c;',
						'default_font' => 'Open Sans',
						'google_webfont' => 'Oswald',
						'color_scheme'	=>'Yellow',
						
						// header
						'colorset-header_color-bg'				=>'#444444',
						'colorset-header_color-bg2'				=>'#333333',
						'colorset-header_color-primary'			=>'#f0b70c',
						'colorset-header_color-secondary'		=>'#f0950c',
						'colorset-header_color-color'			=>'#ffffff',
						'colorset-header_color-border'			=>'#555555',
						'colorset-header_color-img'				=>'',
						'colorset-header_color-customimage'		=>'',
						'colorset-header_color-pos' 			=> 'center center',
						'colorset-header_color-repeat' 			=> 'repeat',
						'colorset-header_color-attach' 			=> 'scroll',
						
						// main
						'colorset-main_color-bg'				=>'#ffffff',
						'colorset-main_color-bg2'				=>'#f8f8f8',
						'colorset-main_color-primary'			=>'#f0b70c',
						'colorset-main_color-secondary'			=>'#f0950c',
						'colorset-main_color-color'				=>'#666666',
						'colorset-main_color-border'			=>'#e1e1e1',
						'colorset-main_color-img'				=>'',
						'colorset-main_color-customimage'		=>'',
						'colorset-main_color-pos' 				=> 'center center',
						'colorset-main_color-repeat' 			=> 'repeat',
						'colorset-main_color-attach' 			=> 'scroll',
						
						// alternate
						'colorset-alternate_color-bg'			=>'#f8f8f8',
						'colorset-alternate_color-bg2'			=>'#ffffff',
						'colorset-alternate_color-primary'		=>'#f0b70c',
						'colorset-alternate_color-secondary'	=>'#f0950c',
						'colorset-alternate_color-color'		=>'#888888',
						'colorset-alternate_color-border'		=>'#e1e1e1',
						'colorset-alternate_color-img'			=>'',
						'colorset-alternate_color-customimage'	=>'',
						'colorset-alternate_color-pos' 			=> 'center center',
						'colorset-alternate_color-repeat' 		=> 'repeat',
						'colorset-alternate_color-attach' 		=> 'scroll',
						
						// Slideshow
						'colorset-slideshow_color-bg'			=>'#fcfcfc',
						'colorset-slideshow_color-bg2'			=>'#f8f8f8',
						'colorset-slideshow_color-primary'		=>'#f0b70c',
						'colorset-slideshow_color-secondary'	=>'#f0950c',
						'colorset-slideshow_color-color'		=>'#666666',
						'colorset-slideshow_color-border'		=>'#e1e1e1',
						'colorset-slideshow_color-img'			=>'',
						'colorset-slideshow_color-customimage'	=>'',
						'colorset-slideshow_color-pos' 			=> 'center center',
						'colorset-slideshow_color-repeat' 		=> 'repeat',
						'colorset-slideshow_color-attach' 		=> 'scroll',
						
						// Footer
						'colorset-footer_color-bg'				=>'#111111',
						'colorset-footer_color-bg2'				=>'#444444',
						'colorset-footer_color-primary'			=>'#f0b70c',
						'colorset-footer_color-secondary'		=>'#f0950c',
						'colorset-footer_color-color'			=>'#ffffff',
						'colorset-footer_color-border'			=>'#555555',
						'colorset-footer_color-img'				=>'',
						'colorset-footer_color-customimage'		=>'',
						'colorset-footer_color-pos' 			=> 'center center',
						'colorset-footer_color-repeat' 			=> 'repeat',
						'colorset-footer_color-attach' 			=> 'scroll',
						
						// Socket
						'colorset-socket_color-bg'				=>'#111111',
						'colorset-socket_color-bg2'				=>'#000000',
						'colorset-socket_color-primary'			=>'#ffffff',
						'colorset-socket_color-secondary'		=>'#eeeeee',
						'colorset-socket_color-color'			=>'#eeeeee',
						'colorset-socket_color-border'			=>'#161616',
						'colorset-socket_color-img'				=>'',
						'colorset-socket_color-customimage'		=>'',
						'colorset-socket_color-pos' 			=> 'center center',
						'colorset-socket_color-repeat' 			=> 'repeat',
						'colorset-socket_color-attach' 			=> 'scroll',
						
						//body bg
						'color-body_style'						=>'stretched',
						'color-body_color'						=>'#f8f8f8',
						'color-body_attach'						=>'scroll',
						'color-body_repeat'						=>'repeat',
						'color-body_pos'						=>'center center',
						'color-body_img'						=>'',
						'color-body_customimage'				=>'',
						),
						
						
						
						
						
	'Cyan' => array(	
						'style'=>'background-color:#2997ab;',
						'default_font' => 'Arial-websave',
						'google_webfont' => 'Terminal Dosis',
						'color_scheme'	=>'Cyan',
						
						// header
						'colorset-header_color-bg'				=>'#ffffff',
						'colorset-header_color-bg2'				=>'#f8f8f8',
						'colorset-header_color-primary'			=>'#2997ab',
						'colorset-header_color-secondary'		=>'#55adbd',
						'colorset-header_color-color'			=>'#333333',
						'colorset-header_color-border'			=>'#e1e1e1',
						'colorset-header_color-img'				=>'',
						'colorset-header_color-customimage'		=>'',
						'colorset-header_color-pos' 			=> 'center center',
						'colorset-header_color-repeat' 			=> 'repeat',
						'colorset-header_color-attach' 			=> 'scroll',
						
						// main
						'colorset-main_color-bg'				=>'#ffffff',
						'colorset-main_color-bg2'				=>'#f8f8f8',
						'colorset-main_color-primary'			=>'#2997ab',
						'colorset-main_color-secondary'			=>'#55adbd',
						'colorset-main_color-color'				=>'#666666',
						'colorset-main_color-border'			=>'#e1e1e1',
						'colorset-main_color-img'				=>'',
						'colorset-main_color-customimage'		=>'',
						'colorset-main_color-pos' 				=> 'center center',
						'colorset-main_color-repeat' 			=> 'repeat',
						'colorset-main_color-attach' 			=> 'scroll',
						
						// alternate
						'colorset-alternate_color-bg'			=>'#f8f8f8',
						'colorset-alternate_color-bg2'			=>'#ffffff',
						'colorset-alternate_color-primary'		=>'#2997ab',
						'colorset-alternate_color-secondary'	=>'#55adbd',
						'colorset-alternate_color-color'		=>'#888888',
						'colorset-alternate_color-border'		=>'#e1e1e1',
						'colorset-alternate_color-img'			=>'',
						'colorset-alternate_color-customimage'	=>'',
						'colorset-alternate_color-pos' 			=> 'center center',
						'colorset-alternate_color-repeat' 		=> 'repeat',
						'colorset-alternate_color-attach' 		=> 'scroll',
						
						// Slideshow
						'colorset-slideshow_color-bg'			=>'#333333',
						'colorset-slideshow_color-bg2'			=>'#f8f8f8',
						'colorset-slideshow_color-primary'		=>'#2997ab',
						'colorset-slideshow_color-secondary'	=>'#55adbd',
						'colorset-slideshow_color-color'		=>'#ffffff',
						'colorset-slideshow_color-border'		=>'#e1e1e1',
						'colorset-slideshow_color-img'			=> AVIA_BASE_URL.'images/background-images/grain_bottom.png',	
						'colorset-slideshow_color-customimage'	=>'',
						'colorset-slideshow_color-pos' 			=> 'bottom center',
						'colorset-slideshow_color-repeat' 		=> 'repeat-x',
						'colorset-slideshow_color-attach' 		=> 'scroll',
						
						// Footer
						'colorset-footer_color-bg'				=>'#333333',
						'colorset-footer_color-bg2'				=>'#222222',
						'colorset-footer_color-primary'			=>'#2997ab',
						'colorset-footer_color-secondary'		=>'#55adbd',
						'colorset-footer_color-color'			=>'#aaaaaa',
						'colorset-footer_color-border'			=>'#555555',
						'colorset-footer_color-img'				=>AVIA_BASE_URL.'images/background-images/grain_top.png',
						'colorset-footer_color-customimage'		=>'',
						'colorset-footer_color-pos' 			=> 'top center',
						'colorset-footer_color-repeat' 			=> 'repeat-x',
						'colorset-footer_color-attach' 			=> 'scroll',
						
						// Socket
						'colorset-socket_color-bg'				=>'#111111',
						'colorset-socket_color-bg2'				=>'#000000',
						'colorset-socket_color-primary'			=>'#ffffff',
						'colorset-socket_color-secondary'		=>'#eeeeee',
						'colorset-socket_color-color'			=>'#eeeeee',
						'colorset-socket_color-border'			=>'#161616',
						'colorset-socket_color-img'				=>'',
						'colorset-socket_color-customimage'		=>'',
						'colorset-socket_color-pos' 			=> 'center center',
						'colorset-socket_color-repeat' 			=> 'repeat',
						'colorset-socket_color-attach' 			=> 'scroll',
						

						//body bg
						'color-body_style'						=>'stretched',
						'color-body_color'						=>'#ebebeb',
						'color-body_attach'						=>'scroll',
						'color-body_repeat'						=>'repeat',
						'color-body_pos'						=>'center center',
						'color-body_img'						=>'',
						'color-body_customimage'				=>'',
						),
	
	
	'Black' => array(	
						'style'=>'background-color:#000000;',
						'default_font' => 'Open Sans',
						'google_webfont' => 'Open Sans',
						'color_scheme'	=>'Black',

						// header
						'colorset-header_color-bg'				=>'#ffffff',
						'colorset-header_color-bg2'				=>'#f8f8f8',
						'colorset-header_color-primary'			=>'#000000',
						'colorset-header_color-secondary'		=>'#88BBC8',
						'colorset-header_color-color'			=>'#333333',
						'colorset-header_color-border'			=>'#e1e1e1',
						'colorset-header_color-img'				=>'',
						'colorset-header_color-customimage'		=>'',
						'colorset-header_color-pos' 			=> 'center center',
						'colorset-header_color-repeat' 			=> 'repeat',
						'colorset-header_color-attach' 			=> 'scroll',
						
						// main
						'colorset-main_color-bg'				=>'#ffffff',
						'colorset-main_color-bg2'				=>'#f8f8f8',
						'colorset-main_color-primary'			=>'#000000',
						'colorset-main_color-secondary'			=>'#88BBC8',
						'colorset-main_color-color'				=>'#666666',
						'colorset-main_color-border'			=>'#e1e1e1',
						'colorset-main_color-img'				=>'',
						'colorset-main_color-customimage'		=>'',
						'colorset-main_color-pos' 				=> 'center center',
						'colorset-main_color-repeat' 			=> 'repeat',
						'colorset-main_color-attach' 			=> 'scroll',
						
						// alternate
						'colorset-alternate_color-bg'			=>'#f8f8f8',
						'colorset-alternate_color-bg2'			=>'#ffffff',
						'colorset-alternate_color-primary'		=>'#000000',
						'colorset-alternate_color-secondary'	=>'#88BBC8',
						'colorset-alternate_color-color'		=>'#888888',
						'colorset-alternate_color-border'		=>'#e1e1e1',
						'colorset-alternate_color-img'			=>'',
						'colorset-alternate_color-customimage'	=>'',
						'colorset-alternate_color-pos' 			=> 'center center',
						'colorset-alternate_color-repeat' 		=> 'repeat',
						'colorset-alternate_color-attach' 		=> 'scroll',
						
						// Slideshow
						'colorset-slideshow_color-bg'			=>'#fcfcfc',
						'colorset-slideshow_color-bg2'			=>'#f8f8f8',
						'colorset-slideshow_color-primary'		=>'#000000',
						'colorset-slideshow_color-secondary'	=>'#88BBC8',
						'colorset-slideshow_color-color'		=>'#666666',
						'colorset-slideshow_color-border'		=>'#e1e1e1',
						'colorset-slideshow_color-img'			=>'',
						'colorset-slideshow_color-customimage'	=>'',
						'colorset-slideshow_color-pos' 			=> 'center center',
						'colorset-slideshow_color-repeat' 		=> 'repeat',
						'colorset-slideshow_color-attach' 		=> 'scroll',
						
						// Footer
						'colorset-footer_color-bg'				=>'#000000',
						'colorset-footer_color-bg2'				=>'#222222',
						'colorset-footer_color-primary'			=>'#000000',
						'colorset-footer_color-secondary'		=>'#88BBC8',
						'colorset-footer_color-color'			=>'#aaaaaa',
						'colorset-footer_color-border'			=>'#555555',
						'colorset-footer_color-img'				=>'',
						'colorset-footer_color-customimage'		=>'',
						'colorset-footer_color-pos' 			=> 'center center',
						'colorset-footer_color-repeat' 			=> 'repeat',
						'colorset-footer_color-attach' 			=> 'scroll',
						
						// Socket
						'colorset-socket_color-bg'				=>'#333333',
						'colorset-socket_color-bg2'				=>'#000000',
						'colorset-socket_color-primary'			=>'#ffffff',
						'colorset-socket_color-secondary'		=>'#eeeeee',
						'colorset-socket_color-color'			=>'#eeeeee',
						'colorset-socket_color-border'			=>'#333333',
						'colorset-socket_color-img'				=>'',
						'colorset-socket_color-customimage'		=>'',
						'colorset-socket_color-pos' 			=> 'center center',
						'colorset-socket_color-repeat' 			=> 'repeat',
						'colorset-socket_color-attach' 			=> 'scroll',
						
						//body bg
						'color-body_style'						=>'stretched',
						'color-body_color'						=>'#ebebeb',
						'color-body_attach'						=>'scroll',
						'color-body_repeat'						=>'repeat',
						'color-body_pos'						=>'center center',
						'color-body_img'						=>'',
						'color-body_customimage'				=>'',
						),				

	
	'Pink' => array(	
						'style'=>'background-color:#c71c77;',
						'default_font' => 'Arial-websave',
						'google_webfont' => 'Carme',
						'color_scheme'	=>'Pink',
						
						// header
						'colorset-header_color-bg'				=>'#ffffff',
						'colorset-header_color-bg2'				=>'#f8f8f8',
						'colorset-header_color-primary'			=>'#c71c77',
						'colorset-header_color-secondary'		=>'#db519a',
						'colorset-header_color-color'			=>'#333333',
						'colorset-header_color-border'			=>'#e1e1e1',
						'colorset-header_color-img'				=>'',
						'colorset-header_color-customimage'		=>'',
						'colorset-header_color-pos' 			=> 'center center',
						'colorset-header_color-repeat' 			=> 'repeat',
						'colorset-header_color-attach' 			=> 'scroll',
						
						// main
						'colorset-main_color-bg'				=>'#ffffff',
						'colorset-main_color-bg2'				=>'#f8f8f8',
						'colorset-main_color-primary'			=>'#c71c77',
						'colorset-main_color-secondary'			=>'#db519a',
						'colorset-main_color-color'				=>'#666666',
						'colorset-main_color-border'			=>'#e1e1e1',
						'colorset-main_color-img'				=>'',
						'colorset-main_color-customimage'		=>'',
						'colorset-main_color-pos' 				=> 'center center',
						'colorset-main_color-repeat' 			=> 'repeat',
						'colorset-main_color-attach' 			=> 'scroll',
						
						// alternate
						'colorset-alternate_color-bg'			=>'#f8f8f8',
						'colorset-alternate_color-bg2'			=>'#ffffff',
						'colorset-alternate_color-primary'		=>'#c71c77',
						'colorset-alternate_color-secondary'	=>'#db519a',
						'colorset-alternate_color-color'		=>'#888888',
						'colorset-alternate_color-border'		=>'#e1e1e1',
						'colorset-alternate_color-img'			=>'',
						'colorset-alternate_color-customimage'	=>'',
						'colorset-alternate_color-pos' 			=> 'center center',
						'colorset-alternate_color-repeat' 		=> 'repeat',
						'colorset-alternate_color-attach' 		=> 'scroll',
						
						// Slideshow
						'colorset-slideshow_color-bg'			=>'#fcfcfc',
						'colorset-slideshow_color-bg2'			=>'#f8f8f8',
						'colorset-slideshow_color-primary'		=>'#c71c77',
						'colorset-slideshow_color-secondary'	=>'#db519a',
						'colorset-slideshow_color-color'		=>'#666666',
						'colorset-slideshow_color-border'		=>'#e1e1e1',
						'colorset-slideshow_color-img'			=>'',
						'colorset-slideshow_color-customimage'	=>'',
						'colorset-slideshow_color-pos' 			=> 'center center',
						'colorset-slideshow_color-repeat' 		=> 'repeat',
						'colorset-slideshow_color-attach' 		=> 'scroll',
						// Footer
						'colorset-footer_color-bg'				=>'#444444',
						'colorset-footer_color-bg2'				=>'#222222',
						'colorset-footer_color-primary'			=>'#c71c77',
						'colorset-footer_color-secondary'		=>'#db519a',
						'colorset-footer_color-color'			=>'#aaaaaa',
						'colorset-footer_color-border'			=>'#555555',
						'colorset-footer_color-img'				=>'',
						'colorset-footer_color-customimage'		=>'',
						'colorset-footer_color-pos' 			=> 'top center',
						'colorset-footer_color-repeat' 			=> 'repeat-x',
						'colorset-footer_color-attach' 			=> 'scroll',
						
						// Socket
						'colorset-socket_color-bg'				=>'#555555',
						'colorset-socket_color-bg2'				=>'#000000',
						'colorset-socket_color-primary'			=>'#ffffff',
						'colorset-socket_color-secondary'		=>'#eeeeee',
						'colorset-socket_color-color'			=>'#eeeeee',
						'colorset-socket_color-border'			=>'#161616',
						'colorset-socket_color-img'				=>'',
						'colorset-socket_color-customimage'		=>'',
						'colorset-socket_color-pos' 			=> 'center center',
						'colorset-socket_color-repeat' 			=> 'repeat',
						'colorset-socket_color-attach' 			=> 'scroll',
						
						//body bg
						'color-body_style'						=>'boxed',
						'color-body_color'						=>'#222222',
						'color-body_attach'						=>'scroll',
						'color-body_repeat'						=>'repeat',
						'color-body_pos'						=>'center center',
						'color-body_img'						=>AVIA_BASE_URL.'images/background-images/diagonal-bold-light.png',
						'color-body_customimage'				=>'',
						
						),
						
						
	'Wood' => array(	
						'style'=>'background-color:#2e1f06;',
						'default_font' => 'Arial-websave',
						'google_webfont' => 'Open Sans',
						'color_scheme'	=>'Wood',

						// header
						'colorset-header_color-bg'				=>'#ffffff',
						'colorset-header_color-bg2'				=>'#f8f8f8',
						'colorset-header_color-primary'			=>'#2e1f06',
						'colorset-header_color-secondary'		=>'#db519a',
						'colorset-header_color-color'			=>'#333333',
						'colorset-header_color-border'			=>'#e1e1e1',
						'colorset-header_color-img'				=>'',
						'colorset-header_color-customimage'		=>'',
						'colorset-header_color-pos' 			=> 'center center',
						'colorset-header_color-repeat' 			=> 'repeat',
						'colorset-header_color-attach' 			=> 'scroll',
						
						// main
						'colorset-main_color-bg'				=>'#ffffff',
						'colorset-main_color-bg2'				=>'#f8f8f8',
						'colorset-main_color-primary'			=>'#2e1f06',
						'colorset-main_color-secondary'			=>'#db519a',
						'colorset-main_color-color'				=>'#666666',
						'colorset-main_color-border'			=>'#e1e1e1',
						'colorset-main_color-img'				=>'',
						'colorset-main_color-customimage'		=>'',
						'colorset-main_color-pos' 				=> 'center center',
						'colorset-main_color-repeat' 			=> 'repeat',
						'colorset-main_color-attach' 			=> 'scroll',
						
						// alternate
						'colorset-alternate_color-bg'			=>'#f8f8f8',
						'colorset-alternate_color-bg2'			=>'#ffffff',
						'colorset-alternate_color-primary'		=>'#2e1f06',
						'colorset-alternate_color-secondary'	=>'#db519a',
						'colorset-alternate_color-color'		=>'#888888',
						'colorset-alternate_color-border'		=>'#e1e1e1',
						'colorset-alternate_color-img'			=>'',
						'colorset-alternate_color-customimage'	=>'',
						'colorset-alternate_color-pos' 			=> 'center center',
						'colorset-alternate_color-repeat' 		=> 'repeat',
						'colorset-alternate_color-attach' 		=> 'scroll',
						
						// Slideshow
						'colorset-slideshow_color-bg'			=>'#fcfcfc',
						'colorset-slideshow_color-bg2'			=>'#f8f8f8',
						'colorset-slideshow_color-primary'		=>'#2e1f06',
						'colorset-slideshow_color-secondary'	=>'#db519a',
						'colorset-slideshow_color-color'		=>'#666666',
						'colorset-slideshow_color-border'		=>'#e1e1e1',
						'colorset-slideshow_color-img'			=>'',
						'colorset-slideshow_color-customimage'	=>'',
						'colorset-slideshow_color-pos' 			=> 'center center',
						'colorset-slideshow_color-repeat' 		=> 'repeat',
						'colorset-slideshow_color-attach' 		=> 'scroll',
						
						// Footer
						'colorset-footer_color-bg'				=>'#000000',
						'colorset-footer_color-bg2'				=>'#222222',
						'colorset-footer_color-primary'			=>'#ffffff',
						'colorset-footer_color-secondary'		=>'#ffffff',
						'colorset-footer_color-color'			=>'#aaaaaa',
						'colorset-footer_color-border'			=>'#555555',
						'colorset-footer_color-img'				=>'',
						'colorset-footer_color-customimage'		=>'',
						'colorset-footer_color-pos' 			=> 'top center',
						'colorset-footer_color-repeat' 			=> 'repeat-x',
						'colorset-footer_color-attach' 			=> 'scroll',
						
						// Socket
						'colorset-socket_color-bg'				=>'#2e1f06',
						'colorset-socket_color-bg2'				=>'#000000',
						'colorset-socket_color-primary'			=>'#ffffff',
						'colorset-socket_color-secondary'		=>'#eeeeee',
						'colorset-socket_color-color'			=>'#eeeeee',
						'colorset-socket_color-border'			=>'#161616',
						'colorset-socket_color-img'				=>'',
						'colorset-socket_color-customimage'		=>'',
						'colorset-socket_color-pos' 			=> 'center center',
						'colorset-socket_color-repeat' 			=> 'repeat',
						'colorset-socket_color-attach' 			=> 'scroll',
						
						//body bg
						'color-body_style'						=>'boxed',
						'color-body_color'						=>'#2e1f06',
						'color-body_attach'						=>'scroll',
						'color-body_repeat'						=>'repeat',
						'color-body_pos'						=>'center center',
						'color-body_img'						=>AVIA_BASE_URL.'images/background-images/wood-light.png',
						'color-body_customimage'				=>'',
						
						),

						
	'Dark' => array(	
						'style'=>'background-color:#222222;',
						'default_font' => 'Arial-websave',
						'google_webfont' => 'Metrophobic',
						'color_scheme'	=>'Dark',
						
						// header
						'colorset-header_color-bg'				=>'#111111',
						'colorset-header_color-bg2'				=>'#222222',
						'colorset-header_color-primary'			=>'#a81010',
						'colorset-header_color-secondary'		=>'#eb3b3b',
						'colorset-header_color-color'			=>'#ffffff',
						'colorset-header_color-border'			=>'#444444',
						'colorset-header_color-img'				=>'',
						'colorset-header_color-customimage'		=>'',
						'colorset-header_color-pos' 			=> 'center center',
						'colorset-header_color-repeat' 			=> 'repeat',
						'colorset-header_color-attach' 			=> 'scroll',
						
						// main
						'colorset-main_color-bg'				=>'#111111',
						'colorset-main_color-bg2'				=>'#222222',
						'colorset-main_color-primary'			=>'#a81010',
						'colorset-main_color-secondary'			=>'#eb3b3b',
						'colorset-main_color-color'				=>'#ffffff',
						'colorset-main_color-border'			=>'#444444',
						'colorset-main_color-img'				=>'',
						'colorset-main_color-customimage'		=>'',
						'colorset-main_color-pos' 				=> 'center center',
						'colorset-main_color-repeat' 			=> 'repeat',
						'colorset-main_color-attach' 			=> 'scroll',
						
						// alternate
						'colorset-alternate_color-bg'			=>'#222222',
						'colorset-alternate_color-bg2'			=>'#333333',
						'colorset-alternate_color-primary'		=>'#a81010',
						'colorset-alternate_color-secondary'	=>'#eb3b3b',
						'colorset-alternate_color-color'		=>'#ffffff',
						'colorset-alternate_color-border'		=>'#444444',
						'colorset-alternate_color-img'			=>'',
						'colorset-alternate_color-customimage'	=>'',
						'colorset-alternate_color-pos' 			=> 'center center',
						'colorset-alternate_color-repeat' 		=> 'repeat',
						'colorset-alternate_color-attach' 		=> 'scroll',
						
						// Slideshow
						'colorset-slideshow_color-bg'			=>'#333333',
						'colorset-slideshow_color-bg2'			=>'#444444',
						'colorset-slideshow_color-primary'		=>'#a81010',
						'colorset-slideshow_color-secondary'	=>'#eb3b3b',
						'colorset-slideshow_color-color'		=>'#ffffff',
						'colorset-slideshow_color-border'		=>'#444444',
						'colorset-slideshow_color-img'			=>'',
						'colorset-slideshow_color-customimage'	=>'',
						'colorset-slideshow_color-pos' 			=> 'center center',
						'colorset-slideshow_color-repeat' 		=> 'repeat',
						'colorset-slideshow_color-attach' 		=> 'scroll',
						
						// Footer
						'colorset-footer_color-bg'				=>'#111111',
						'colorset-footer_color-bg2'				=>'#222222',
						'colorset-footer_color-primary'			=>'#a81010',
						'colorset-footer_color-secondary'		=>'#eb3b3b',
						'colorset-footer_color-color'			=>'#aaaaaa',
						'colorset-footer_color-border'			=>'#555555',
						'colorset-footer_color-img'				=>'',
						'colorset-footer_color-customimage'		=>'',
						'colorset-footer_color-pos' 			=> 'center center',
						'colorset-footer_color-repeat' 			=> 'repeat',
						'colorset-footer_color-attach' 			=> 'scroll',
						
						// Socket
						'colorset-socket_color-bg'				=>'#333333',
						'colorset-socket_color-bg2'				=>'#000000',
						'colorset-socket_color-primary'			=>'#ffffff',
						'colorset-socket_color-secondary'		=>'#eeeeee',
						'colorset-socket_color-color'			=>'#eeeeee',
						'colorset-socket_color-border'			=>'#333333',
						'colorset-socket_color-img'				=>'',
						'colorset-socket_color-customimage'		=>'',
						'colorset-socket_color-pos' 			=> 'center center',
						'colorset-socket_color-repeat' 			=> 'repeat',
						'colorset-socket_color-attach' 			=> 'scroll',
						
						//body bg
						'color-body_style'						=>'stretched',
						'color-body_color'						=>'#ebebeb',
						'color-body_attach'						=>'scroll',
						'color-body_repeat'						=>'repeat',
						'color-body_pos'						=>'center center',
						'color-body_img'						=>'',
						'color-body_customimage'				=>'',
						
						),	
	
	'Noisy Blue' => array(	
						'style'=>'background-color:#1a324b;',
						'default_font' => 'Arial-websave',
						'google_webfont' => 'Open Sans',
						'color_scheme'	=>'Noisy Blue',
						
						// header
						'colorset-header_color-bg'				=>'#f2f5fa',
						'colorset-header_color-bg2'				=>'#dfe6f0',
						'colorset-header_color-primary'			=>'#2d5c88',
						'colorset-header_color-secondary'		=>'#4686c2',
						'colorset-header_color-color'			=>'#102438',
						'colorset-header_color-border'			=>'#d1def0',
						'colorset-header_color-img'				=>AVIA_BASE_URL.'images/background-images/noise-for-light-background.png',
						'colorset-header_color-customimage'		=>'',
						'colorset-header_color-pos' 			=> 'center center',
						'colorset-header_color-repeat' 			=> 'repeat',
						'colorset-header_color-attach' 			=> 'scroll',
						
						// main
						'colorset-main_color-bg'				=>'#f2f5fa',
						'colorset-main_color-bg2'				=>'#dfe6f0',
						'colorset-main_color-primary'			=>'#2d5c88',
						'colorset-main_color-secondary'			=>'#4686c2',
						'colorset-main_color-color'				=>'#102438',
						'colorset-main_color-border'			=>'#d1def0',
						'colorset-main_color-img'				=>AVIA_BASE_URL.'images/background-images/noise-for-light-background.png',
						'colorset-main_color-customimage'		=>'',
						'colorset-main_color-pos' 				=> 'center center',
						'colorset-main_color-repeat' 			=> 'repeat',
						'colorset-main_color-attach' 			=> 'scroll',
						
						// alternate
						'colorset-alternate_color-bg'			=>'#dfe6f0',
						'colorset-alternate_color-bg2'			=>'#f2f5fa',
						'colorset-alternate_color-primary'		=>'#2d5c88',
						'colorset-alternate_color-secondary'	=>'#4686c2',
						'colorset-alternate_color-color'		=>'#102438',
						'colorset-alternate_color-border'		=>'#d1def0',
						'colorset-alternate_color-img'			=>AVIA_BASE_URL.'images/background-images/noise-for-light-background.png',
						'colorset-alternate_color-customimage'	=>'',
						'colorset-alternate_color-pos' 			=> 'center center',
						'colorset-alternate_color-repeat' 		=> 'repeat',
						'colorset-alternate_color-attach' 		=> 'scroll',
						
						// Slideshow
						'colorset-slideshow_color-bg'			=>'#fcfcfc',
						'colorset-slideshow_color-bg2'			=>'#f8f8f8',
						'colorset-slideshow_color-primary'		=>'#2d5c88',
						'colorset-slideshow_color-secondary'	=>'#4686c2',
						'colorset-slideshow_color-color'		=>'#102438',
						'colorset-slideshow_color-border'		=>'#d1def0',
						'colorset-slideshow_color-img'			=>'',
						'colorset-slideshow_color-customimage'	=>'',
						'colorset-slideshow_color-pos' 			=> 'center center',
						'colorset-slideshow_color-repeat' 		=> 'repeat',
						'colorset-slideshow_color-attach' 		=> 'scroll',
						
						// Footer
						'colorset-footer_color-bg'				=>'#2a4a69',
						'colorset-footer_color-bg2'				=>'#3c5b78',
						'colorset-footer_color-primary'			=>'#ffffff',
						'colorset-footer_color-secondary'		=>'#ffffff',
						'colorset-footer_color-color'			=>'#ffffff',
						'colorset-footer_color-border'			=>'#3c5b78',
						'colorset-footer_color-img'				=>'',
						'colorset-footer_color-customimage'		=>'',
						'colorset-footer_color-pos' 			=> 'center center',
						'colorset-footer_color-repeat' 			=> 'repeat',
						'colorset-footer_color-attach' 			=> 'scroll',
						
						// Socket
						'colorset-socket_color-bg'				=>'#1A324B',
						'colorset-socket_color-bg2'				=>'#000000',
						'colorset-socket_color-primary'			=>'#7D8B99',
						'colorset-socket_color-secondary'		=>'#7D8B99',
						'colorset-socket_color-color'			=>'#7D8B99',
						'colorset-socket_color-border'			=>'#1A324B',
						'colorset-socket_color-img'				=>'',
						'colorset-socket_color-customimage'		=>'',
						'colorset-socket_color-pos' 			=> 'center center',
						'colorset-socket_color-repeat' 			=> 'repeat',
						'colorset-socket_color-attach' 			=> 'scroll',
						
						//body bg
						'color-body_style'						=>'stretched',
						'color-body_color'						=>'#ebebeb',
						'color-body_attach'						=>'scroll',
						'color-body_repeat'						=>'repeat',
						'color-body_pos'						=>'center center',
						'color-body_img'						=>'',
						'color-body_customimage'				=>'',
						),
					
								   
);
