<?php
// Extend Purethemes.net Shortcodes plugin
function centum_shortcodes_list( $pt_shortcodes ) {

    $ptsc_icons = $icon = array(
        'none' => 'No Icon',
        'adjust' => 'adjust',
        'anchor' => 'anchor',
        'archive' => 'archive',
        'arrows' => 'arrows',
        'arrows-h' => 'arrows-h',
        'arrows-v' => 'arrows-v',
        'asterisk' => 'asterisk',
        'automobile' => 'automobile',
        'ban' => 'ban',
        'bank' => 'bank',
        'bar-chart-o' => 'bar-chart-o',
        'barcode' => 'barcode',
        'bars' => 'bars',
        'beer' => 'beer',
        'bell' => 'bell',
        'bell-o' => 'bell-o',
        'bolt' => 'bolt',
        'bomb' => 'bomb',
        'book' => 'book',
        'bookmark' => 'bookmark',
        'bookmark-o' => 'bookmark-o',
        'briefcase' => 'briefcase',
        'bug' => 'bug',
        'building' => 'building',
        'building-o' => 'building-o',
        'bullhorn' => 'bullhorn',
        'bullseye' => 'bullseye',
        'cab' => 'cab',
        'calendar' => 'calendar',
        'calendar-o' => 'calendar-o',
        'camera' => 'camera',
        'camera-retro' => 'camera-retro',
        'car' => 'car',
        'caret-square-o-down' => 'caret-square-o-down',
        'caret-square-o-left' => 'caret-square-o-left',
        'caret-square-o-right' => 'caret-square-o-right',
        'caret-square-o-up' => 'caret-square-o-up',
        'certificate' => 'certificate',
        'check' => 'check',
        'check-circle' => 'check-circle',
        'check-circle-o' => 'check-circle-o',
        'check-square' => 'check-square',
        'check-square-o' => 'check-square-o',
        'child' => 'child',
        'circle' => 'circle',
        'circle-o' => 'circle-o',
        'circle-o-notch' => 'circle-o-notch',
        'circle-thin' => 'circle-thin',
        'clock-o' => 'clock-o',
        'cloud' => 'cloud',
        'cloud-download' => 'cloud-download',
        'cloud-upload' => 'cloud-upload',
        'code' => 'code',
        'code-fork' => 'code-fork',
        'coffee' => 'coffee',
        'cog' => 'cog',
        'cogs' => 'cogs',
        'comment' => 'comment',
        'comment-o' => 'comment-o',
        'comments' => 'comments',
        'comments-o' => 'comments-o',
        'compass' => 'compass',
        'credit-card' => 'credit-card',
        'crop' => 'crop',
        'crosshairs' => 'crosshairs',
        'cube' => 'cube',
        'cubes' => 'cubes',
        'cutlery' => 'cutlery',
        'dashboard' => 'dashboard',
        'database' => 'database',
        'desktop' => 'desktop',
        'dot-circle-o' => 'dot-circle-o',
        'download' => 'download',
        'edit' => 'edit',
        'ellipsis-h' => 'ellipsis-h',
        'ellipsis-v' => 'ellipsis-v',
        'envelope' => 'envelope',
        'envelope-o' => 'envelope-o',
        'envelope-square' => 'envelope-square',
        'eraser' => 'eraser',
        'exchange' => 'exchange',
        'exclamation' => 'exclamation',
        'exclamation-circle' => 'exclamation-circle',
        'exclamation-triangle' => 'exclamation-triangle',
        'external-link' => 'external-link',
        'external-link-square' => 'external-link-square',
        'eye' => 'eye',
        'eye-slash' => 'eye-slash',
        'fax' => 'fax',
        'female' => 'female',
        'fighter-jet' => 'fighter-jet',
        'file-archive-o' => 'file-archive-o',
        'file-audio-o' => 'file-audio-o',
        'file-code-o' => 'file-code-o',
        'file-excel-o' => 'file-excel-o',
        'file-image-o' => 'file-image-o',
        'file-movie-o' => 'file-movie-o',
        'file-pdf-o' => 'file-pdf-o',
        'file-photo-o' => 'file-photo-o',
        'file-picture-o' => 'file-picture-o',
        'file-powerpoint-o' => 'file-powerpoint-o',
        'file-sound-o' => 'file-sound-o',
        'file-video-o' => 'file-video-o',
        'file-word-o' => 'file-word-o',
        'file-zip-o' => 'file-zip-o',
        'film' => 'film',
        'filter' => 'filter',
        'fire' => 'fire',
        'fire-extinguisher' => 'fire-extinguisher',
        'flag' => 'flag',
        'flag-checkered' => 'flag-checkered',
        'flag-o' => 'flag-o',
        'flash' => 'flash',
        'flask' => 'flask',
        'folder' => 'folder',
        'folder-o' => 'folder-o',
        'folder-open' => 'folder-open',
        'folder-open-o' => 'folder-open-o',
        'frown-o' => 'frown-o',
        'gamepad' => 'gamepad',
        'gavel' => 'gavel',
        'gear' => 'gear',
        'gears' => 'gears',
        'gift' => 'gift',
        'glass' => 'glass',
        'globe' => 'globe',
        'graduation-cap' => 'graduation-cap',
        'group' => 'group',
        'hdd-o' => 'hdd-o',
        'headphones' => 'headphones',
        'heart' => 'heart',
        'heart-o' => 'heart-o',
        'history' => 'history',
        'home' => 'home',
        'image' => 'image',
        'inbox' => 'inbox',
        'info' => 'info',
        'info-circle' => 'info-circle',
        'institution' => 'institution',
        'key' => 'key',
        'keyboard-o' => 'keyboard-o',
        'language' => 'language',
        'laptop' => 'laptop',
        'leaf' => 'leaf',
        'legal' => 'legal',
        'lemon-o' => 'lemon-o',
        'level-down' => 'level-down',
        'level-up' => 'level-up',
        'life-bouy' => 'life-bouy',
        'life-ring' => 'life-ring',
        'life-saver' => 'life-saver',
        'lightbulb-o' => 'lightbulb-o',
        'location-arrow' => 'location-arrow',
        'lock' => 'lock',
        'magic' => 'magic',
        'magnet' => 'magnet',
        'mail-forward' => 'mail-forward',
        'mail-reply' => 'mail-reply',
        'mail-reply-all' => 'mail-reply-all',
        'male' => 'male',
        'map-marker' => 'map-marker',
        'meh-o' => 'meh-o',
        'microphone' => 'microphone',
        'microphone-slash' => 'microphone-slash',
        'minus' => 'minus',
        'minus-circle' => 'minus-circle',
        'minus-square' => 'minus-square',
        'minus-square-o' => 'minus-square-o',
        'mobile' => 'mobile',
        'mobile-phone' => 'mobile-phone',
        'money' => 'money',
        'moon-o' => 'moon-o',
        'mortar-board' => 'mortar-board',
        'music' => 'music',
        'navicon' => 'navicon',
        'paper-plane' => 'paper-plane',
        'paper-plane-o' => 'paper-plane-o',
        'paw' => 'paw',
        'pencil' => 'pencil',
        'pencil-square' => 'pencil-square',
        'pencil-square-o' => 'pencil-square-o',
        'phone' => 'phone',
        'phone-square' => 'phone-square',
        'photo' => 'photo',
        'picture-o' => 'picture-o',
        'plane' => 'plane',
        'plus' => 'plus',
        'plus-circle' => 'plus-circle',
        'plus-square' => 'plus-square',
        'plus-square-o' => 'plus-square-o',
        'power-off' => 'power-off',
        'print' => 'print',
        'puzzle-piece' => 'puzzle-piece',
        'qrcode' => 'qrcode',
        'question' => 'question',
        'question-circle' => 'question-circle',
        'quote-left' => 'quote-left',
        'quote-right' => 'quote-right',
        'random' => 'random',
        'recycle' => 'recycle',
        'refresh' => 'refresh',
        'reorder' => 'reorder',
        'reply' => 'reply',
        'reply-all' => 'reply-all',
        'retweet' => 'retweet',
        'road' => 'road',
        'rocket' => 'rocket',
        'rss' => 'rss',
        'rss-square' => 'rss-square',
        'search' => 'search',
        'search-minus' => 'search-minus',
        'search-plus' => 'search-plus',
        'send' => 'send',
        'send-o' => 'send-o',
        'share' => 'share',
        'share-alt' => 'share-alt',
        'share-alt-square' => 'share-alt-square',
        'share-square' => 'share-square',
        'share-square-o' => 'share-square-o',
        'shield' => 'shield',
        'shopping-cart' => 'shopping-cart',
        'sign-in' => 'sign-in',
        'sign-out' => 'sign-out',
        'signal' => 'signal',
        'sitemap' => 'sitemap',
        'sliders' => 'sliders',
        'smile-o' => 'smile-o',
        'sort' => 'sort',
        'sort-alpha-asc' => 'sort-alpha-asc',
        'sort-alpha-desc' => 'sort-alpha-desc',
        'sort-amount-asc' => 'sort-amount-asc',
        'sort-amount-desc' => 'sort-amount-desc',
        'sort-asc' => 'sort-asc',
        'sort-desc' => 'sort-desc',
        'sort-down' => 'sort-down',
        'sort-numeric-asc' => 'sort-numeric-asc',
        'sort-numeric-desc' => 'sort-numeric-desc',
        'sort-up' => 'sort-up',
        'space-shuttle' => 'space-shuttle',
        'spinner' => 'spinner',
        'spoon' => 'spoon',
        'square' => 'square',
        'square-o' => 'square-o',
        'star' => 'star',
        'star-half' => 'star-half',
        'star-half-empty' => 'star-half-empty',
        'star-half-full' => 'star-half-full',
        'star-half-o' => 'star-half-o',
        'star-o' => 'star-o',
        'suitcase' => 'suitcase',
        'sun-o' => 'sun-o',
        'support' => 'support',
        'tablet' => 'tablet',
        'tachometer' => 'tachometer',
        'tag' => 'tag',
        'tags' => 'tags',
        'tasks' => 'tasks',
        'taxi' => 'taxi',
        'terminal' => 'terminal',
        'thumb-tack' => 'thumb-tack',
        'thumbs-down' => 'thumbs-down',
        'thumbs-o-down' => 'thumbs-o-down',
        'thumbs-o-up' => 'thumbs-o-up',
        'thumbs-up' => 'thumbs-up',
        'ticket' => 'ticket',
        'times' => 'times',
        'times-circle' => 'times-circle',
        'times-circle-o' => 'times-circle-o',
        'tint' => 'tint',
        'toggle-down' => 'toggle-down',
        'toggle-left' => 'toggle-left',
        'toggle-right' => 'toggle-right',
        'toggle-up' => 'toggle-up',
        'trash-o' => 'trash-o',
        'tree' => 'tree',
        'trophy' => 'trophy',
        'truck' => 'truck',
        'umbrella' => 'umbrella',
        'university' => 'university',
        'unlock' => 'unlock',
        'unlock-alt' => 'unlock-alt',
        'unsorted' => 'unsorted',
        'upload' => 'upload',
        'user' => 'user',
        'users' => 'users',
        'video-camera' => 'video-camera',
        'volume-down' => 'volume-down',
        'volume-off' => 'volume-off',
        'volume-up' => 'volume-up',
        'warning' => 'warning',
        'wheelchair' => 'wheelchair',
        'wrench' => 'wrench',
        'file' => 'file',
        'file-archive-o' => 'file-archive-o',
        'file-audio-o' => 'file-audio-o',
        'file-code-o' => 'file-code-o',
        'file-excel-o' => 'file-excel-o',
        'file-image-o' => 'file-image-o',
        'file-movie-o' => 'file-movie-o',
        'file-o' => 'file-o',
        'file-pdf-o' => 'file-pdf-o',
        'file-photo-o' => 'file-photo-o',
        'file-picture-o' => 'file-picture-o',
        'file-powerpoint-o' => 'file-powerpoint-o',
        'file-sound-o' => 'file-sound-o',
        'file-text' => 'file-text',
        'file-text-o' => 'file-text-o',
        'file-video-o' => 'file-video-o',
        'file-word-o' => 'file-word-o',
        'file-zip-o' => 'file-zip-o',
        'circle-o-notch' => 'circle-o-notch',
        'cog' => 'cog',
        'gear' => 'gear',
        'refresh' => 'refresh',
        'spinner' => 'spinner',
        'check-square' => 'check-square',
        'check-square-o' => 'check-square-o',
        'circle' => 'circle',
        'circle-o' => 'circle-o',
        'dot-circle-o' => 'dot-circle-o',
        'minus-square' => 'minus-square',
        'minus-square-o' => 'minus-square-o',
        'plus-square' => 'plus-square',
        'plus-square-o' => 'plus-square-o',
        'square' => 'square',
        'square-o' => 'square-o',
        'bitcoin' => 'bitcoin',
        'btc' => 'btc',
        'cny' => 'cny',
        'dollar' => 'dollar',
        'eur' => 'eur',
        'euro' => 'euro',
        'gbp' => 'gbp',
        'inr' => 'inr',
        'jpy' => 'jpy',
        'krw' => 'krw',
        'money' => 'money',
        'rmb' => 'rmb',
        'rouble' => 'rouble',
        'rub' => 'rub',
        'ruble' => 'ruble',
        'rupee' => 'rupee',
        'try' => 'try',
        'turkish-lira' => 'turkish-lira',
        'usd' => 'usd',
        'won' => 'won',
        'yen' => 'yen',
        'align-center' => 'align-center',
        'align-justify' => 'align-justify',
        'align-left' => 'align-left',
        'align-right' => 'align-right',
        'bold' => 'bold',
        'chain' => 'chain',
        'chain-broken' => 'chain-broken',
        'clipboard' => 'clipboard',
        'columns' => 'columns',
        'copy' => 'copy',
        'cut' => 'cut',
        'dedent' => 'dedent',
        'eraser' => 'eraser',
        'file' => 'file',
        'file-o' => 'file-o',
        'file-text' => 'file-text',
        'file-text-o' => 'file-text-o',
        'files-o' => 'files-o',
        'floppy-o' => 'floppy-o',
        'font' => 'font',
        'header' => 'header',
        'indent' => 'indent',
        'italic' => 'italic',
        'link' => 'link',
        'list' => 'list',
        'list-alt' => 'list-alt',
        'list-ol' => 'list-ol',
        'list-ul' => 'list-ul',
        'outdent' => 'outdent',
        'paperclip' => 'paperclip',
        'paragraph' => 'paragraph',
        'paste' => 'paste',
        'repeat' => 'repeat',
        'rotate-left' => 'rotate-left',
        'rotate-right' => 'rotate-right',
        'save' => 'save',
        'scissors' => 'scissors',
        'strikethrough' => 'strikethrough',
        'subscript' => 'subscript',
        'superscript' => 'superscript',
        'table' => 'table',
        'text-height' => 'text-height',
        'text-width' => 'text-width',
        'th' => 'th',
        'th-large' => 'th-large',
        'th-list' => 'th-list',
        'underline' => 'underline',
        'undo' => 'undo',
        'unlink' => 'unlink',
        'angle-double-down' => 'angle-double-down',
        'angle-double-left' => 'angle-double-left',
        'angle-double-right' => 'angle-double-right',
        'angle-double-up' => 'angle-double-up',
        'angle-down' => 'angle-down',
        'angle-left' => 'angle-left',
        'angle-right' => 'angle-right',
        'angle-up' => 'angle-up',
        'arrow-circle-down' => 'arrow-circle-down',
        'arrow-circle-left' => 'arrow-circle-left',
        'arrow-circle-o-down' => 'arrow-circle-o-down',
        'arrow-circle-o-left' => 'arrow-circle-o-left',
        'arrow-circle-o-right' => 'arrow-circle-o-right',
        'arrow-circle-o-up' => 'arrow-circle-o-up',
        'arrow-circle-right' => 'arrow-circle-right',
        'arrow-circle-up' => 'arrow-circle-up',
        'arrow-down' => 'arrow-down',
        'arrow-left' => 'arrow-left',
        'arrow-right' => 'arrow-right',
        'arrow-up' => 'arrow-up',
        'arrows' => 'arrows',
        'arrows-alt' => 'arrows-alt',
        'arrows-h' => 'arrows-h',
        'arrows-v' => 'arrows-v',
        'caret-down' => 'caret-down',
        'caret-left' => 'caret-left',
        'caret-right' => 'caret-right',
        'caret-square-o-down' => 'caret-square-o-down',
        'caret-square-o-left' => 'caret-square-o-left',
        'caret-square-o-right' => 'caret-square-o-right',
        'caret-square-o-up' => 'caret-square-o-up',
        'caret-up' => 'caret-up',
        'chevron-circle-down' => 'chevron-circle-down',
        'chevron-circle-left' => 'chevron-circle-left',
        'chevron-circle-right' => 'chevron-circle-right',
        'chevron-circle-up' => 'chevron-circle-up',
        'chevron-down' => 'chevron-down',
        'chevron-left' => 'chevron-left',
        'chevron-right' => 'chevron-right',
        'chevron-up' => 'chevron-up',
        'hand-o-down' => 'hand-o-down',
        'hand-o-left' => 'hand-o-left',
        'hand-o-right' => 'hand-o-right',
        'hand-o-up' => 'hand-o-up',
        'long-arrow-down' => 'long-arrow-down',
        'long-arrow-left' => 'long-arrow-left',
        'long-arrow-right' => 'long-arrow-right',
        'long-arrow-up' => 'long-arrow-up',
        'toggle-down' => 'toggle-down',
        'toggle-left' => 'toggle-left',
        'toggle-right' => 'toggle-right',
        'toggle-up' => 'toggle-up',
        'arrows-alt' => 'arrows-alt',
        'backward' => 'backward',
        'compress' => 'compress',
        'eject' => 'eject',
        'expand' => 'expand',
        'fast-backward' => 'fast-backward',
        'fast-forward' => 'fast-forward',
        'forward' => 'forward',
        'pause' => 'pause',
        'play' => 'play',
        'play-circle' => 'play-circle',
        'play-circle-o' => 'play-circle-o',
        'step-backward' => 'step-backward',
        'step-forward' => 'step-forward',
        'stop' => 'stop',
        'youtube-play' => 'youtube-play',
        'adn' => 'adn',
        'android' => 'android',
        'apple' => 'apple',
        'behance' => 'behance',
        'behance-square' => 'behance-square',
        'bitbucket' => 'bitbucket',
        'bitbucket-square' => 'bitbucket-square',
        'bitcoin' => 'bitcoin',
        'btc' => 'btc',
        'codepen' => 'codepen',
        'css3' => 'css3',
        'delicious' => 'delicious',
        'deviantart' => 'deviantart',
        'digg' => 'digg',
        'dribbble' => 'dribbble',
        'dropbox' => 'dropbox',
        'drupal' => 'drupal',
        'empire' => 'empire',
        'facebook' => 'facebook',
        'facebook-square' => 'facebook-square',
        'flickr' => 'flickr',
        'foursquare' => 'foursquare',
        'ge' => 'ge',
        'git' => 'git',
        'git-square' => 'git-square',
        'github' => 'github',
        'github-alt' => 'github-alt',
        'github-square' => 'github-square',
        'gittip' => 'gittip',
        'google' => 'google',
        'google-plus' => 'google-plus',
        'google-plus-square' => 'google-plus-square',
        'hacker-news' => 'hacker-news',
        'html5' => 'html5',
        'instagram' => 'instagram',
        'joomla' => 'joomla',
        'jsfiddle' => 'jsfiddle',
        'linkedin' => 'linkedin',
        'linkedin-square' => 'linkedin-square',
        'linux' => 'linux',
        'maxcdn' => 'maxcdn',
        'openid' => 'openid',
        'pagelines' => 'pagelines',
        'pied-piper' => 'pied-piper',
        'pied-piper-alt' => 'pied-piper-alt',
        'pied-piper-square' => 'pied-piper-square',
        'pinterest' => 'pinterest',
        'pinterest-square' => 'pinterest-square',
        'qq' => 'qq',
        'ra' => 'ra',
        'rebel' => 'rebel',
        'reddit' => 'reddit',
        'reddit-square' => 'reddit-square',
        'renren' => 'renren',
        'share-alt' => 'share-alt',
        'share-alt-square' => 'share-alt-square',
        'skype' => 'skype',
        'slack' => 'slack',
        'soundcloud' => 'soundcloud',
        'spotify' => 'spotify',
        'stack-exchange' => 'stack-exchange',
        'stack-overflow' => 'stack-overflow',
        'steam' => 'steam',
        'steam-square' => 'steam-square',
        'stumbleupon' => 'stumbleupon',
        'stumbleupon-circle' => 'stumbleupon-circle',
        'tencent-weibo' => 'tencent-weibo',
        'trello' => 'trello',
        'tumblr' => 'tumblr',
        'tumblr-square' => 'tumblr-square',
        'twitter' => 'twitter',
        'twitter-square' => 'twitter-square',
        'vimeo-square' => 'vimeo-square',
        'vine' => 'vine',
        'vk' => 'vk',
        'wechat' => 'wechat',
        'weibo' => 'weibo',
        'weixin' => 'weixin',
        'windows' => 'windows',
        'wordpress' => 'wordpress',
        'xing' => 'xing',
        'xing-square' => 'xing-square',
        'yahoo' => 'yahoo',
        'youtube' => 'youtube',
        'youtube-play' => 'youtube-play',
        'youtube-square' => 'youtube-square',
        'ambulance' => 'ambulance',
        'h-square' => 'h-square',
        'hospital-o' => 'hospital-o',
        'medkit' => 'medkit',
        'plus-square' => 'plus-square',
        'stethoscope' => 'stethoscope',
        'user-md' => 'user-md',
        'wheelchair' => 'wheelchair',
    );
    $ptsc_orderby = array(
        'none' => 'none' ,
        'ID' => 'ID' ,
        'author' => 'author' ,
        'title' => 'title' ,
        'name' => 'name' ,
        'date' => 'date' ,
        'modified' => 'modified' ,
        'parent' => 'parent' ,
        'rand' => 'rand' ,
        'comment_count' => 'comment_count' ,
        );

    $ptsc_limit = array();
    for ($i=0; $i < 25 ; $i++) {
       $ptsc_limit[$i] = $i;
    }

    $ptsc_order = array(
        'ASC' => 'from lowest to highest values (1, 2, 3; a, b, c)' ,
        'DESC' => 'from highest to lowest values (3, 2, 1; c, b, a)' ,
        );

    $ptsc_places = array(
        'none' => 'None' , 'first' => 'First' , 'last' => 'Last' , 'center' => 'Center'
    );


    $portfolio_filters = get_terms('filters');
    $filters_options = array();
    foreach($portfolio_filters as $filter) {
        $filters_options[$filter->slug] = $filter->name;
    }

    $category_options = get_terms('category');
    $categories_options = array();
    foreach($category_options as $cat) {
        $categories_options[$cat->slug] = $cat->name;
    }    

    $tag_options = get_tags();
    $tags_options = array();
    foreach($tag_options as $tag) {
        $tags_options[$tag->slug] = $tag->name;
    }
    

    $ptsc_width = array(
        'one' => 'One' ,
        'two' => 'Two' ,
        'three' => 'Three' ,
        'four' => 'Four' ,
        'five' => 'Five' ,
        'six' => 'Six' ,
        'seven' => 'Seven' ,
        'eight' => 'Eight' ,
        'nine' => 'Nine' ,
        'ten' => 'Ten' ,
        'eleven' => 'Eleven' ,
        'twelve' => 'Twelve' ,
        'thirteen' => 'Thirteen' ,
        'fourteen' => 'Fourteen' ,
        'fifteen' => 'Fifteen' ,
        'sixteen' => 'Sixteen' ,
    );

    $ptsc_perc = array();
    for ($i=0; $i < 101 ; $i=$i+5) {
        $ptsc_perc[$i] = $i."%";
    }

    /* set arrays for shortcodes form */
    $astrum_pt_shortcodes = array(

     'separator' => array(
        'label' => 'Separator',
        'has_content' => false,
        'std' => '',
    ),
      'button' => array(
            'label' => 'Button',
            'has_content' => true,
            'params' => array(
                'url' => array(
                    'type' => 'text',
                    'label' => 'Url',
                    'desc' => 'Set URL',
                    'std' => '',
                ),
                'color' => array(
                    'type' => 'select',
                    'label' => 'Color',
                    'desc' => 'Select the color for button',
                    'options' => array(
                        'gray' => 'Gray',
                        'light' => 'Light',
                        'color' => 'Curent Main Color'
                    ),
                    'std' => '',
                ),
                'customcolor' => array(
                    'type' => 'colorpicker',
                    'label' => 'Custom Color',
                    'desc' => 'Select the custom color for button (ignores previous setting)',
                    'std' => '',
                ),
                'iconcolor' => array(
                    'type' => 'select',
                    'label' => 'Icon Color',
                    'desc' => 'Select the color for icon in the button',
                    'options' => array(
                        'white' => 'White',
                        'dark' => 'Dark'
                    ),
                    'std' => '',
                ),
                'icon' => array(
                    'type' => 'select',
                    'label' => 'Icon',
                    'desc' => 'Select the icon for button',
                    'options' => $ptsc_icons,
                    'std' => '',
                ),
                'target' => array(
                    'type' => 'select',
                    'label' => 'Target',
                    'desc' => 'Select the target of a button link',
                    'options' => array(
                        '_top' => 'Top',
                        '_self' => 'Self',
                        '_blank' => 'Blank',
                        '_parent' => 'Parent'
                    ),
                    'std' => '',
                ),
                'content' => array(
                    'type' => 'textarea',
                    'label' => 'Content',
                    'std' => '',
                ),
                'custom_class' => array(
                    'type' => 'text',
                    'label' => 'Custom class',
                    'std' => '',
                )
            )
        ),
    'icon' => array(
        'label' => 'Icon',
        'has_content' => false,
        'params' => array(
            'icon' => array(
                'type' => 'select',
                'label' => 'Icon',
                'desc' => 'Select icon from the list',
                'options' => $ptsc_icons,
                'std' => '',
            ),
        )
    ),
    'tooltip' => array(
        'label' => 'Tooltip',
        'has_content' => true,
        'params' => array(
            'title' => array(
                    'type' => 'text',
                    'label' => 'Title',
                    'desc' => 'Set title',
                    'std' => '',
                ),
            'url' => array(
                    'type' => 'text',
                    'label' => 'Url',
                    'desc' => 'Set URL',
                    'std' => '',
                ),
            'content' => array(
                'type' => 'textarea',
                'label' => 'Content',
                'std' => '',
                ),
            'side' => array(
                'type' => 'select',
                'label' => 'Side',
                'desc' => 'Select the side of tooltip',
                'options' => array(
                    'top' => 'Top',
                    'left' => 'Left',
                    'bottom' => 'Bottom',
                    'right' => 'Right'
                ),
                'std' => '',
            ),
        )
    ),
  
   
    'column' => array(
        'label' => 'Column',
        'has_content' => true,
        'params' => array(
            'place' => array(
                'type' => 'select',
                'label' => 'Placement',
                'desc' => 'If the columns is already in a container, you need to select place in the row it takes',
                'options' => $ptsc_places,
                'std' => '',
            ),
            'width' => array(
                'type' => 'select',
                'label' => 'Width',
                'desc' => 'Select the width of column',
                'options' => $ptsc_width,
                'std' => 'four'
            ),
            'custom_class' => array(
                'type' => 'text',
                'label' => 'Custom class (optional)',
                'std' => '',
            )
        )
    ),
    'box' => array(
            'label' => 'Alert box',
            'has_content' => true,
            'params' => array(
                'type' => array(
                    'type' => 'select',
                    'label' => 'Type of box',
                    'options' => array(
                        'success' => 'Success',
                        'error' => 'Error',
                        'warning' => 'Warning',
                        'notice' => 'Notice',
                    ),
                    'std' => '',
                ),
                'content' => array(
                    'type' => 'textarea',
                    'label' => 'Content',
                    'std' => '',
                ),
            )
        ),
    'recent_pf' => array(
            'label' => 'Recent portfolio items',
            'has_content' => false,
            'params' => array(
                'limit' => array(
                    'type' => 'select',
                    'label' => 'Limit',
                    'desc' => 'Select number of items to display',
                    'options' => $ptsc_limit,
                    'std' => '',
                ),
                'orderby' => array(
                    'type' => 'select',
                    'label' => 'Oder by',
                    'desc' => '',
                    'options' => $ptsc_orderby,
                    'std' => '',
                ),    
                'order' => array(
                    'type' => 'select',
                    'label' => 'Oder by',
                    'desc' => '',
                    'options' => $ptsc_order,
                    'std' => '',
                ),
                'filters' => array(
                'type' => 'select-multi',
                'label' => 'Filters',
                'desc' => 'Select filters from which you want to display items (leave empty for all)',
                'options' => $filters_options,
                'std' => '',
                ),
               'exclude_posts' => array(
                    'type' => 'text',
                    'label' => 'Posts to exclude',
                    'desc' => 'ID\'s of posts to exclude from list, separated by coma',
                    'std' => '',
                ),
               'lightbox' => array(
                    'type' => 'select',
                    'label' => 'Lightbox',
                    'desc' => 'Should photo link to single item or open it in lightbox?',
                    'options' => array(
                        'yes' => 'Yes',
                        'no' => 'No',
                    ),
                    'std' => 'yes',
                ), 
               'fullpage' => array(
                    'type' => 'select',
                    'label' => 'Full page',
                    'desc' => 'Set yes if the shortcode is used on full-width page',
                    'options' => array(
                        'yes' => 'Yes',
                        'no' => 'No',
                    ),
                    'std' => 'yes',
                ),
               'read_more' => array(
                    'type' => 'select',
                    'label' => 'Add read more button',
                    'desc' => '',
                    'options' => array(
                        'yes' => 'Yes',
                        'no' => 'No',
                    ),
                    'std' => 'no',
                ),
            )
        ),

    'notice' => array(
        'label' => 'Big notice box',
        'has_content' => true,
        'params' => array(
            'title' => array(
                'type' => 'text',
                'label' => 'Title',
                'desc' => '',
                'std' => '',
            ),
            'content' => array(
                'type' => 'textarea',
                'label' => 'Content',
                'desc' => 'You can use other shortcodes like [button] here',
                'std' => '',
                ),
            )
        ),

    'headline' => array(
        'label' => 'Headline (styled header)',
        'has_content' => true,
        'params' => array(
            'content' => array(
                'type' => 'textarea',
                'label' => 'Content',
                'std' => '',
                ),
            'margin' => array(
                'type' => 'text',
                'label' => 'Top margin',
                'desc' => 'Put just a number, it will be added in px',
                'std' => '',
            ),
            'htype' => array(
                'type' => 'select',
                'label' => 'Header type',
                'options' => array(
                    'h3' => 'H3',
                    'h4' => 'H4',
                ),
                'std' => 'h3',
            ),
            )
        ),
     'feature' => array(
        'label' => 'Feature box',
        'has_content' => true,
        'params' => array(
            'title' => array(
                'type' => 'text',
                'label' => 'Title',
                'desc' => 'Set title',
                'std' => '',
            ),
            'content' => array(
                'type' => 'textarea',
                'label' => 'Content',
                'std' => '',
                ),
            'url' => array(
                'type' => 'text',
                'label' => 'URL',
                'desc' => 'Set url for iconbox',
                'std' => '',
            ),
            'icon' => array(
                'type' => 'select',
                'label' => 'Icon',
                'desc' => 'Select the icon to display',
                'options' => $ptsc_icons,
                'std' => '',
            ),
            'custom_icon' => array(
                'type' => 'text',
                'label' => 'Custom Icon',
                'desc' => 'URL for the icon image to display',
                'std' => '',
            ),
        )
    ),
    'recent_blog' => array(
            'label' => 'Recent blog posts',
            'has_content' => true,
            'params' => array(
                'limit' => array(
                    'type' => 'select',
                    'label' => 'Limit',
                    'desc' => 'Select number of items to display',
                    'options' => $ptsc_limit,
                    'std' => '',
                ),
                'orderby' => array(
                    'type' => 'select',
                    'label' => 'Oder by',
                    'desc' => '',
                    'options' => $ptsc_orderby,
                    'std' => '',
                ),    
                'order' => array(
                    'type' => 'select',
                    'label' => 'Oder by',
                    'desc' => '',
                    'options' => $ptsc_order,
                    'std' => '',
                ),
                'categories' => array(
                    'type' => 'select-multi',
                    'label' => 'Categories',
                    'desc' => 'Select filters from which you want to display items (leave empty for all)',
                    'options' => $categories_options,
                    'std' => '',
                ),                
                'tags' => array(
                    'type' => 'select-multi',
                    'label' => 'Tags',
                    'desc' => 'Select filters from which you want to display items (leave empty for all)',
                    'options' => $tags_options,
                    'std' => '',
                ),
               'exclude_posts' => array(
                    'type' => 'text',
                    'label' => 'Posts to exclude',
                    'desc' => 'ID\'s of posts to exclude from list, separated by coma',
                    'std' => '',
                ),
               'limit_words' => array(
                    'type' => 'text',
                    'label' => 'Limit words',
                    'desc' => 'How much text display below each post',
                    'std' => '13',
                ), 
               'read_more' => array(
                    'type' => 'select',
                    'label' => 'Add read more button',
                    'desc' => '',
                    'options' => array(
                        'yes' => 'Yes',
                        'no' => 'No',
                    ),
                    'std' => 'no',
                ),
               'fullpage' => array(
                    'type' => 'select',
                    'label' => 'Full page',
                    'desc' => 'Set yes if the shortcode is used on full-width page',
                    'options' => array(
                        'yes' => 'Yes',
                        'no' => 'No',
                    ),
                    'std' => 'yes',
                ),
            )
        ),

    'list' => array(
        'label' => 'List',
        'has_content' => true,
        'params' => array(
            'type' => array(
                'type' => 'select',
                'label' => 'List style',
                'desc' => 'Set title',
                'options' => array(
                    'list-1' => 'Check',
                    'list-2' => 'Arrow',
                    'list-3' => 'Check with background',
                    'list-4' => 'Arrow with background',
                ),
                'std' => ''
            ),
            'color' => array(
                'type' => 'select',
                'label' => 'Colored icons?',
                'desc' => '',
                'options' => array(
                    'yes' => 'Yes',
                    'no' => 'No',
                ),
                'std' => ''
            ),
             'content' => array(
                'type' => 'textarea',
                'label' => 'Content (use HTML markup for list)',
                'std' => ''
            ),
        )
    ),
    'accordion' => array(
        'label' => 'Accordion',
        'has_content' => true,
        'params' => array(
            'title' => array(
                'type' => 'text',
                'label' => 'Title',
                'desc' => 'Set title',
                'std' => '',
            ),
            'content' => array(
                'type' => 'textarea',
                'label' => 'Content',
                'std' => '',
            ),
        )
    ),
    'toggle' => array(
            'label' => 'Toggle',
            'has_content' => true,
            'params' => array(
                'open' => array(
                    'type' => 'select',
                    'label' => 'Open/closed',
                    'desc' => 'Set type',
                    'options' => array(
                        'no' => 'Closed',
                        'yes' => 'Open',
                    ),
                    'std' => '',
                ),
                'title' => array(
                    'type' => 'text',
                    'label' => 'Title',
                    'std' => '',
                ),
                'icon' => array(
                    'type' => 'select',
                    'label' => 'Icon',
                    'desc' => 'Select the icon',
                    'options' => $ptsc_icons,
                    'std' => '',
                ),
                'content' => array(
                    'type' => 'textarea',
                    'label' => 'Content',
                    'std' => '',
                ),
            )
        ),
    'icon' => array(
        'label' => 'Icon',
        'has_content' => false,
        'params' => array(
            'icon' => array(
                'type' => 'select',
                'label' => 'Icon',
                'desc' => 'Select the icon',
                'options' => $ptsc_icons,
                'std' => '',
            ),
        )
    ),
    'testimonial' => array(
            'label' => 'Tabs',
            'has_content' => true,
            'wrapper' => 'testimonials',
            'params' => array(
                'author' => array(
                    'type' => 'text',
                    'label' => 'Author',
                    'desc' => 'Name',
                    'std' => '',
                ),
                'job' => array(
                    'type' => 'text',
                    'label' => 'Job',
                    'desc' => 'Author\'s position',
                    'std' => '',
                ),
                'content' => array(
                    'type' => 'textarea',
                    'label' => 'Content',
                    'std' => '',
                ),
            )
        ),
   

);
unset($pt_shortcodes['accordion']);
unset($pt_shortcodes['dropcap']);
unset($pt_shortcodes['toggle']);
unset($pt_shortcodes['button']);
$pt_shortcodes = array_merge($pt_shortcodes, $astrum_pt_shortcodes);
return $pt_shortcodes;
}


function add_shortcodes() {
    add_filter( 'ptsc_shortcodes', 'centum_shortcodes_list' );
}
add_action( 'init', 'add_shortcodes' );

 ?>