<?php
	require_once(THEME_SHORTCODES_PATH.'subtitle.php');
	require_once(THEME_SHORTCODES_PATH.'dropcaps.php');
	require_once(THEME_SHORTCODES_PATH.'buttons.php');
	require_once(THEME_SHORTCODES_PATH.'alert.php');
	require_once(THEME_SHORTCODES_PATH.'paragraph.php');
	require_once(THEME_SHORTCODES_PATH.'lists.php');
	require_once(THEME_SHORTCODES_PATH.'qoutes.php');
	require_once(THEME_SHORTCODES_PATH.'marker.php');
	require_once(THEME_SHORTCODES_PATH.'tab.php');
	require_once(THEME_SHORTCODES_PATH.'toggles.php');
	require_once(THEME_SHORTCODES_PATH.'caption.php');
	require_once(THEME_SHORTCODES_PATH.'spacers.php');
	require_once(THEME_SHORTCODES_PATH.'gallery-box.php');
?>