<?php 
/*
* This template controlls the portfolio single entries: These entries are generated by this file in conjunction with includes/loop-portfolio-single.php
*/

global $avia_config;

	/*
	 * check which page template should be applied: 
	 * cecks for dynamic pages as well as for portfolio, fullwidth, blog, contact and any other possibility :)
	 * Be aware that if a match was found another template wil be included and the code bellow will not be executed
 	 * located at the bottom of includes/helper-templates.php
	 */
	 avia_get_template();


	/*
	 * get_header is a basic wordpress function, used to retrieve the header.php file in your theme directory.
	 */	
	 get_header();
 	 
	?>
		
		<!-- ####### MAIN CONTAINER ####### -->
		<div class='container_wrap single-portfolio-entry' id='main'>
		
			<div class='inner_container'>
				
				<?php
				/* Run the loop to output the posts.
				* If you want to overload this in a child theme then include a file
				* called loop-page.php and that will be used instead.
				*/
				get_template_part( 'includes/loop', 'portfolio-single' );
				
				
				
				?>
				

				<div class='offset-by-one large_element'>
					<div class='post_nav'><span class='post_nav_sep'></span>
						<div class='previous_post_link_align'>
							<?php previous_post_link('<span class="previous_post_link post-nav-link"><span>&larr;</span> %link </span>'); ?>
						</div>
						<div class='next_post_link_align'>
							<?php next_post_link('<span class="next_post_link post-nav-link">%link <span>&rarr;</span></span>'); ?>
						</div>
					</div> <!-- end navigation -->
				</div>
				
				<?php
				
				//show related posts based on categories if there are any
				get_template_part( 'includes/related-portfolio-posts');
				
				//wordpress function that loads the comments template "comments.php"
				comments_template( '/includes/comments.php'); 
				
				?>
				
				
			</div><!--end container-->

	</div>
	<!-- ####### END MAIN CONTAINER ####### -->

</div>
<?php 
				wp_reset_query();
				//get the sidebar
				$avia_config['currently_viewing'] = 'portfolio';
				get_sidebar();
				
?>
</div>	


<?php get_footer(); ?>