<?php 

/*
* This template controlls the portfolio overview pages: 4,3 2 and 1 Column Portfolios are generated by this file in conjunction with includes/loop-portfolio.php
*/


global $avia_config;


	//set a deafult query with all portfolio items in case the user just selected to display the page tempalte instead of setting up a portfolio properly
	if(!isset($avia_config['new_query']['tax_query'][0]['terms'][0]) || $avia_config['new_query']['tax_query'][0]['terms'][0] == "null") 
	{ 
		if(!isset($avia_config['portfolio_item_count'])) $avia_config['portfolio_item_count'] = '-1';
	
		$avia_config['new_query'] = array("paged" => get_query_var( 'paged' ),  "posts_per_page" => $avia_config['portfolio_item_count'],  "post_type"=>"portfolio"); 
	}


	/*
	 * get_header is a basic wordpress function, used to retrieve the header.php file in your theme directory.
	 */	
	 get_header();
 	 if(empty($avia_config['portfolio_columns'])) $avia_config['portfolio_columns'] = 4;
 	 
 	 $content = false;
 	 if(isset($post->ID))
 	 { 
 	 	the_post();
	 	if(get_the_content() != "") $content = "with_content";
	}

	?>
		
		<!-- ####### MAIN CONTAINER ####### -->
		<div id='main'>
		
			
			<!--meta info-->
	        <div class="one unit alpha blog-meta">
	        	
	        	<div class='side-container side-container-date'>
	        		
	        		<div class='side-container-inner'>
	        		
	        			<span class='date-day'><?php the_time('d') ?></span>
   						<span class='date-month'><?php the_time('M') ?></span>
   						
	        		</div>
	        		
	        	</div>
				
			</div><!--end meta info-->	
			
			
			<div class='seven units container-portfolio-size-<?php echo $avia_config['portfolio_columns']." portfolio-width-".$avia_config['portfolio_width']." ".$content; ?>'>
				
				<span class='entry-border-overflow extralight-border'></span>
						
				<div class='six units alpha post-entry'>
								
					
					<div class='template-portfolio-overview content portfolio-size-<?php echo $avia_config['portfolio_columns']; ?>'>
					
					<?php
					//display the default content of the portfolio
					
					if($content)
					{
						echo "<h1 class='first-heading'>".get_the_title(avia_get_the_id())."</h1>";
						echo "<div class='post-entry-portfolio-first not-sortable'>";
						the_content();
						echo "</div>";
					}
					
					
					/* Run the loop to output the posts.
					* If you want to overload this in a child theme then include a file
					* called loop-portfolio.php and that will be used instead.
					*/
					
					get_template_part( 'includes/loop', 'portfolio' );
					
					?>
					
					
					<!--end post-entry-->
					</div>
				
				<!--end content-->
				</div>
				
				
			</div><!--end container-->

	</div>
	<!-- ####### END MAIN CONTAINER ####### -->


</div>
<?php 

	//get the sidebar
	$avia_config['currently_viewing'] = 'portfolio';
	get_sidebar();
				
?>
</div>	

<?php get_footer(); ?>