<?php
	
	/**
	 *  The Contact form gets generated by the avia_form class located in framework/php/class-form-generator.php
	 */
 

	$form_args = array(
		
		"heading" => "<h3>".__('Send us mail','avia_framework')."</h3>",
		"success" => "<h3>".__('Your message has been sent!','avia_framework')."</h3><p>".__('Thank you!','avia_framework')."</p>",
		"submit"  => __('Send','avia_framework'),
		"action"  => get_permalink()
	);

	
	$elements = array(
	
		'yourname' 	=> 	array('type'=>'text', 	'label'=>__('Name','avia_framework'), 		'check'=>'is_empty'),			//user name
		'email' 	=> 	array('type'=>'text', 	'label'=>__('E-Mail','avia_framework'), 	'check'=>'is_email'),			//user email
		'website' 	=> 	array('type'=>'text', 	'label'=>__('Website','avia_framework'), 	'check'=>''),					//user website
		'subject' 	=> 	array('type'=>'text', 	'label'=>__('Subject','avia_framework'), 	'check'=>'is_empty'),			//subject
		'message' 	=> 	array('type'=>'textarea','label'=>__('Message','avia_framework'), 	'check'=>'is_empty'),			//message
		'myemail' 	=> 	array('type'=>'hidden',	'label'=>'', 'check'=>'', 'value'=> avia_get_option('email') ),				//email adress the form should be sent to
		'myblogname'=> 	array('type'=>'hidden',	'label'=>'', 'check'=>'', 'value'=> get_option('blogname') ),				//name of the website, gets added to the subject line
		'username'	=> 	array('type'=>'decoy',	'label'=>'', 'check'=>'must_empty'),										//decoy input field for bots, input field gets hidden, if bot enters value form wont be submitted
	
	);
	
	
	$contact_form = new avia_form($form_args);
	$contact_form->create_elements($elements);
	$contact_form->display_form();
	

?>
