        <div class="the-icons span3" data-search="aboveground-rail"><i class="scicon-maki-aboveground-rail"></i><span class="i-name">.scicon-maki-aboveground-rail</span></div>
        <div class="the-icons span3" data-search="warehouse"><i class="scicon-maki-warehouse"></i><span class="i-name">.scicon-maki-warehouse</span></div>
        <div class="the-icons span3" data-search="airport"><i class="scicon-maki-airport"></i><span class="i-name">.scicon-maki-airport</span></div>
        <div class="the-icons span3" data-search="art-gallery"><i class="scicon-maki-art-gallery"></i><span class="i-name">.scicon-maki-art-gallery</span></div>
        <div class="the-icons span3" data-search="bar"><i class="scicon-maki-bar"></i><span class="i-name">.scicon-maki-bar</span></div>
        <div class="the-icons span3" data-search="baseball"><i class="scicon-maki-baseball"></i><span class="i-name">.scicon-maki-baseball</span></div>
        <div class="the-icons span3" data-search="basketball"><i class="scicon-maki-basketball"></i><span class="i-name">.scicon-maki-basketball</span></div>
        <div class="the-icons span3" data-search="beer"><i class="scicon-maki-beer"></i><span class="i-name">.scicon-maki-beer</span></div>
        <div class="the-icons span3" data-search="belowground-rail"><i class="scicon-maki-belowground-rail"></i><span class="i-name">.scicon-maki-belowground-rail</span></div>
        <div class="the-icons span3" data-search="bicycle"><i class="scicon-maki-bicycle"></i><span class="i-name">.scicon-maki-bicycle</span></div>
        <div class="the-icons span3" data-search="bus"><i class="scicon-maki-bus"></i><span class="i-name">.scicon-maki-bus</span></div>
        <div class="the-icons span3" data-search="cafe"><i class="scicon-maki-cafe"></i><span class="i-name">.scicon-maki-cafe</span></div>
        <div class="the-icons span3" data-search="campsite"><i class="scicon-maki-campsite"></i><span class="i-name">.scicon-maki-campsite</span></div>
        <div class="the-icons span3" data-search="cemetery"><i class="scicon-maki-cemetery"></i><span class="i-name">.scicon-maki-cemetery</span></div>
        <div class="the-icons span3" data-search="cinema"><i class="scicon-maki-cinema"></i><span class="i-name">.scicon-maki-cinema</span></div>
        <div class="the-icons span3" data-search="college"><i class="scicon-maki-college"></i><span class="i-name">.scicon-maki-college</span></div>
        <div class="the-icons span3" data-search="commerical-building"><i class="scicon-maki-commerical-building"></i><span class="i-name">.scicon-maki-commerical-building</span></div>
        <div class="the-icons span3" data-search="credit-card"><i class="scicon-maki-credit-card"></i><span class="i-name">.scicon-maki-credit-card</span></div>
        <div class="the-icons span3" data-search="cricket"><i class="scicon-maki-cricket"></i><span class="i-name">.scicon-maki-cricket</span></div>
        <div class="the-icons span3" data-search="embassy"><i class="scicon-maki-embassy"></i><span class="i-name">.scicon-maki-embassy</span></div>
        <div class="the-icons span3" data-search="fast-food"><i class="scicon-maki-fast-food"></i><span class="i-name">.scicon-maki-fast-food</span></div>
        <div class="the-icons span3" data-search="ferry"><i class="scicon-maki-ferry"></i><span class="i-name">.scicon-maki-ferry</span></div>
        <div class="the-icons span3" data-search="fire-station"><i class="scicon-maki-fire-station"></i><span class="i-name">.scicon-maki-fire-station</span></div>
        <div class="the-icons span3" data-search="football"><i class="scicon-maki-football"></i><span class="i-name">.scicon-maki-football</span></div>
        <div class="the-icons span3" data-search="fuel"><i class="scicon-maki-fuel"></i><span class="i-name">.scicon-maki-fuel</span></div>
        <div class="the-icons span3" data-search="garden"><i class="scicon-maki-garden"></i><span class="i-name">.scicon-maki-garden</span></div>
        <div class="the-icons span3" data-search="giraffe"><i class="scicon-maki-giraffe"></i><span class="i-name">.scicon-maki-giraffe</span></div>
        <div class="the-icons span3" data-search="golf"><i class="scicon-maki-golf"></i><span class="i-name">.scicon-maki-golf</span></div>
        <div class="the-icons span3" data-search="grocery-store"><i class="scicon-maki-grocery-store"></i><span class="i-name">.scicon-maki-grocery-store</span></div>
        <div class="the-icons span3" data-search="harbor"><i class="scicon-maki-harbor"></i><span class="i-name">.scicon-maki-harbor</span></div>
        <div class="the-icons span3" data-search="heliport"><i class="scicon-maki-heliport"></i><span class="i-name">.scicon-maki-heliport</span></div>
        <div class="the-icons span3" data-search="airfield"><i class="scicon-maki-airfield"></i><span class="i-name">.scicon-maki-airfield</span></div>
        <div class="the-icons span3" data-search="industrial-building"><i class="scicon-maki-industrial-building"></i><span class="i-name">.scicon-maki-industrial-building</span></div>
        <div class="the-icons span3" data-search="library"><i class="scicon-maki-library"></i><span class="i-name">.scicon-maki-library</span></div>
        <div class="the-icons span3" data-search="lodging"><i class="scicon-maki-lodging"></i><span class="i-name">.scicon-maki-lodging</span></div>
        <div class="the-icons span3" data-search="london-underground"><i class="scicon-maki-london-underground"></i><span class="i-name">.scicon-maki-london-underground</span></div>
        <div class="the-icons span3" data-search="minefield"><i class="scicon-maki-minefield"></i><span class="i-name">.scicon-maki-minefield</span></div>
        <div class="the-icons span3" data-search="monument"><i class="scicon-maki-monument"></i><span class="i-name">.scicon-maki-monument</span></div>
        <div class="the-icons span3" data-search="museum"><i class="scicon-maki-museum"></i><span class="i-name">.scicon-maki-museum</span></div>
        <div class="the-icons span3" data-search="pharmacy"><i class="scicon-maki-pharmacy"></i><span class="i-name">.scicon-maki-pharmacy</span></div>
        <div class="the-icons span3" data-search="pitch"><i class="scicon-maki-pitch"></i><span class="i-name">.scicon-maki-pitch</span></div>
        <div class="the-icons span3" data-search="police"><i class="scicon-maki-police"></i><span class="i-name">.scicon-maki-police</span></div>
        <div class="the-icons span3" data-search="post"><i class="scicon-maki-post"></i><span class="i-name">.scicon-maki-post</span></div>
        <div class="the-icons span3" data-search="prison"><i class="scicon-maki-prison"></i><span class="i-name">.scicon-maki-prison</span></div>
        <div class="the-icons span3" data-search="rail"><i class="scicon-maki-rail"></i><span class="i-name">.scicon-maki-rail</span></div>
        <div class="the-icons span3" data-search="religious-christian"><i class="scicon-maki-religious-christian"></i><span class="i-name">.scicon-maki-religious-christian</span></div>
        <div class="the-icons span3" data-search="religious-islam"><i class="scicon-maki-religious-islam"></i><span class="i-name">.scicon-maki-religious-islam</span></div>
        <div class="the-icons span3" data-search="religious-jewish"><i class="scicon-maki-religious-jewish"></i><span class="i-name">.scicon-maki-religious-jewish</span></div>
        <div class="the-icons span3" data-search="restaurant"><i class="scicon-maki-restaurant"></i><span class="i-name">.scicon-maki-restaurant</span></div>
        <div class="the-icons span3" data-search="roadblock"><i class="scicon-maki-roadblock"></i><span class="i-name">.scicon-maki-roadblock</span></div>
        <div class="the-icons span3" data-search="school"><i class="scicon-maki-school"></i><span class="i-name">.scicon-maki-school</span></div>
        <div class="the-icons span3" data-search="shop"><i class="scicon-maki-shop"></i><span class="i-name">.scicon-maki-shop</span></div>
        <div class="the-icons span3" data-search="skiing"><i class="scicon-maki-skiing"></i><span class="i-name">.scicon-maki-skiing</span></div>
        <div class="the-icons span3" data-search="soccer"><i class="scicon-maki-soccer"></i><span class="i-name">.scicon-maki-soccer</span></div>
        <div class="the-icons span3" data-search="swimming"><i class="scicon-maki-swimming"></i><span class="i-name">.scicon-maki-swimming</span></div>
        <div class="the-icons span3" data-search="tennis"><i class="scicon-maki-tennis"></i><span class="i-name">.scicon-maki-tennis</span></div>
        <div class="the-icons span3" data-search="theatre"><i class="scicon-maki-theatre"></i><span class="i-name">.scicon-maki-theatre</span></div>
        <div class="the-icons span3" data-search="toilet"><i class="scicon-maki-toilet"></i><span class="i-name">.scicon-maki-toilet</span></div>
        <div class="the-icons span3" data-search="town-hall"><i class="scicon-maki-town-hall"></i><span class="i-name">.scicon-maki-town-hall</span></div>
        <div class="the-icons span3" data-search="trash"><i class="scicon-maki-trash"></i><span class="i-name">.scicon-maki-trash</span></div>
        <div class="the-icons span3" data-search="tree-1"><i class="scicon-maki-tree-1"></i><span class="i-name">.scicon-maki-tree-1</span></div>
        <div class="the-icons span3" data-search="tree-2"><i class="scicon-maki-tree-2"></i><span class="i-name">.scicon-maki-tree-2</span></div>
        <div class="the-icons span3" data-search="hospital"><i class="scicon-maki-hospital"></i><span class="i-name">.scicon-maki-hospital</span></div>

<div class="clear"></div><hr>
<a href="https://www.mapbox.com/maki/" target="_blank">https://www.mapbox.com/maki/</a>
<div class="clear"></div><hr><br>