        <div class="the-icons span3" data-search="search"><i class="scicon-mgf-search"></i><span class="i-name">.scicon-mgf-search</span></div>
        <div class="the-icons span3" data-search="mfg-logo-circled"><i class="scicon-mgf-mfg-logo-circled"></i><span class="i-name">.scicon-mgf-mfg-logo-circled</span></div>
        <div class="the-icons span3" data-search="heart"><i class="scicon-mgf-heart"></i><span class="i-name">.scicon-mgf-heart</span></div>
        <div class="the-icons span3" data-search="heart-broken"><i class="scicon-mgf-heart-broken"></i><span class="i-name">.scicon-mgf-heart-broken</span></div>
        <div class="the-icons span3" data-search="star"><i class="scicon-mgf-star"></i><span class="i-name">.scicon-mgf-star</span></div>
        <div class="the-icons span3" data-search="star-empty"><i class="scicon-mgf-star-empty"></i><span class="i-name">.scicon-mgf-star-empty</span></div>
        <div class="the-icons span3" data-search="star-half"><i class="scicon-mgf-star-half"></i><span class="i-name">.scicon-mgf-star-half</span></div>
        <div class="the-icons span3" data-search="star-half_empty"><i class="scicon-mgf-star-half_empty"></i><span class="i-name">.scicon-mgf-star-half_empty</span></div>
        <div class="the-icons span3" data-search="user"><i class="scicon-mgf-user"></i><span class="i-name">.scicon-mgf-user</span></div>
        <div class="the-icons span3" data-search="user-male"><i class="scicon-mgf-user-male"></i><span class="i-name">.scicon-mgf-user-male</span></div>
        <div class="the-icons span3" data-search="user-female"><i class="scicon-mgf-user-female"></i><span class="i-name">.scicon-mgf-user-female</span></div>
        <div class="the-icons span3" data-search="users"><i class="scicon-mgf-users"></i><span class="i-name">.scicon-mgf-users</span></div>
        <div class="the-icons span3" data-search="movie"><i class="scicon-mgf-movie"></i><span class="i-name">.scicon-mgf-movie</span></div>
        <div class="the-icons span3" data-search="videocam"><i class="scicon-mgf-videocam"></i><span class="i-name">.scicon-mgf-videocam</span></div>
        <div class="the-icons span3" data-search="isight"><i class="scicon-mgf-isight"></i><span class="i-name">.scicon-mgf-isight</span></div>
        <div class="the-icons span3" data-search="camera"><i class="scicon-mgf-camera"></i><span class="i-name">.scicon-mgf-camera</span></div>
        <div class="the-icons span3" data-search="menu"><i class="scicon-mgf-menu"></i><span class="i-name">.scicon-mgf-menu</span></div>
        <div class="the-icons span3" data-search="th-thumb"><i class="scicon-mgf-th-thumb"></i><span class="i-name">.scicon-mgf-th-thumb</span></div>
        <div class="the-icons span3" data-search="th-thumb-empty"><i class="scicon-mgf-th-thumb-empty"></i><span class="i-name">.scicon-mgf-th-thumb-empty</span></div>
        <div class="the-icons span3" data-search="th-list"><i class="scicon-mgf-th-list"></i><span class="i-name">.scicon-mgf-th-list</span></div>
        <div class="the-icons span3" data-search="ok"><i class="scicon-mgf-ok"></i><span class="i-name">.scicon-mgf-ok</span></div>
        <div class="the-icons span3" data-search="ok-circled"><i class="scicon-mgf-ok-circled"></i><span class="i-name">.scicon-mgf-ok-circled</span></div>
        <div class="the-icons span3" data-search="cancel"><i class="scicon-mgf-cancel"></i><span class="i-name">.scicon-mgf-cancel</span></div>
        <div class="the-icons span3" data-search="cancel-circled"><i class="scicon-mgf-cancel-circled"></i><span class="i-name">.scicon-mgf-cancel-circled</span></div>
        <div class="the-icons span3" data-search="plus"><i class="scicon-mgf-plus"></i><span class="i-name">.scicon-mgf-plus</span></div>
        <div class="the-icons span3" data-search="help-circled"><i class="scicon-mgf-help-circled"></i><span class="i-name">.scicon-mgf-help-circled</span></div>
        <div class="the-icons span3" data-search="help-circled-alt"><i class="scicon-mgf-help-circled-alt"></i><span class="i-name">.scicon-mgf-help-circled-alt</span></div>
        <div class="the-icons span3" data-search="info-circled"><i class="scicon-mgf-info-circled"></i><span class="i-name">.scicon-mgf-info-circled</span></div>
        <div class="the-icons span3" data-search="info-circled-alt"><i class="scicon-mgf-info-circled-alt"></i><span class="i-name">.scicon-mgf-info-circled-alt</span></div>
        <div class="the-icons span3" data-search="home"><i class="scicon-mgf-home"></i><span class="i-name">.scicon-mgf-home</span></div>
        <div class="the-icons span3" data-search="link"><i class="scicon-mgf-link"></i><span class="i-name">.scicon-mgf-link</span></div>
        <div class="the-icons span3" data-search="attach"><i class="scicon-mgf-attach"></i><span class="i-name">.scicon-mgf-attach</span></div>
        <div class="the-icons span3" data-search="lock"><i class="scicon-mgf-lock"></i><span class="i-name">.scicon-mgf-lock</span></div>
        <div class="the-icons span3" data-search="lock-alt"><i class="scicon-mgf-lock-alt"></i><span class="i-name">.scicon-mgf-lock-alt</span></div>
        <div class="the-icons span3" data-search="lock-open"><i class="scicon-mgf-lock-open"></i><span class="i-name">.scicon-mgf-lock-open</span></div>
        <div class="the-icons span3" data-search="lock-open-alt"><i class="scicon-mgf-lock-open-alt"></i><span class="i-name">.scicon-mgf-lock-open-alt</span></div>
        <div class="the-icons span3" data-search="eye"><i class="scicon-mgf-eye"></i><span class="i-name">.scicon-mgf-eye</span></div>
        <div class="the-icons span3" data-search="download"><i class="scicon-mgf-download"></i><span class="i-name">.scicon-mgf-download</span></div>
        <div class="the-icons span3" data-search="upload"><i class="scicon-mgf-upload"></i><span class="i-name">.scicon-mgf-upload</span></div>
        <div class="the-icons span3" data-search="download-cloud"><i class="scicon-mgf-download-cloud"></i><span class="i-name">.scicon-mgf-download-cloud</span></div>
        <div class="the-icons span3" data-search="upload-cloud"><i class="scicon-mgf-upload-cloud"></i><span class="i-name">.scicon-mgf-upload-cloud</span></div>
        <div class="the-icons span3" data-search="reply"><i class="scicon-mgf-reply"></i><span class="i-name">.scicon-mgf-reply</span></div>
        <div class="the-icons span3" data-search="pencil"><i class="scicon-mgf-pencil"></i><span class="i-name">.scicon-mgf-pencil</span></div>
        <div class="the-icons span3" data-search="export"><i class="scicon-mgf-export"></i><span class="i-name">.scicon-mgf-export</span></div>
        <div class="the-icons span3" data-search="print"><i class="scicon-mgf-print"></i><span class="i-name">.scicon-mgf-print</span></div>
        <div class="the-icons span3" data-search="retweet"><i class="scicon-mgf-retweet"></i><span class="i-name">.scicon-mgf-retweet</span></div>
        <div class="the-icons span3" data-search="comment"><i class="scicon-mgf-comment"></i><span class="i-name">.scicon-mgf-comment</span></div>
        <div class="the-icons span3" data-search="chat"><i class="scicon-mgf-chat"></i><span class="i-name">.scicon-mgf-chat</span></div>
        <div class="the-icons span3" data-search="bell"><i class="scicon-mgf-bell"></i><span class="i-name">.scicon-mgf-bell</span></div>
        <div class="the-icons span3" data-search="attention"><i class="scicon-mgf-attention"></i><span class="i-name">.scicon-mgf-attention</span></div>
        <div class="the-icons span3" data-search="attention-alt"><i class="scicon-mgf-attention-alt"></i><span class="i-name">.scicon-mgf-attention-alt</span></div>
        <div class="the-icons span3" data-search="location"><i class="scicon-mgf-location"></i><span class="i-name">.scicon-mgf-location</span></div>
        <div class="the-icons span3" data-search="trash"><i class="scicon-mgf-trash"></i><span class="i-name">.scicon-mgf-trash</span></div>
        <div class="the-icons span3" data-search="doc"><i class="scicon-mgf-doc"></i><span class="i-name">.scicon-mgf-doc</span></div>
        <div class="the-icons span3" data-search="newspaper"><i class="scicon-mgf-newspaper"></i><span class="i-name">.scicon-mgf-newspaper</span></div>
        <div class="the-icons span3" data-search="folder"><i class="scicon-mgf-folder"></i><span class="i-name">.scicon-mgf-folder</span></div>
        <div class="the-icons span3" data-search="folder-open"><i class="scicon-mgf-folder-open"></i><span class="i-name">.scicon-mgf-folder-open</span></div>
        <div class="the-icons span3" data-search="folder-empty"><i class="scicon-mgf-folder-empty"></i><span class="i-name">.scicon-mgf-folder-empty</span></div>
        <div class="the-icons span3" data-search="folder-open-empty"><i class="scicon-mgf-folder-open-empty"></i><span class="i-name">.scicon-mgf-folder-open-empty</span></div>
        <div class="the-icons span3" data-search="cog"><i class="scicon-mgf-cog"></i><span class="i-name">.scicon-mgf-cog</span></div>
        <div class="the-icons span3" data-search="calendar"><i class="scicon-mgf-calendar"></i><span class="i-name">.scicon-mgf-calendar</span></div>
        <div class="the-icons span3" data-search="login"><i class="scicon-mgf-login"></i><span class="i-name">.scicon-mgf-login</span></div>
        <div class="the-icons span3" data-search="logout"><i class="scicon-mgf-logout"></i><span class="i-name">.scicon-mgf-logout</span></div>
        <div class="the-icons span3" data-search="mic"><i class="scicon-mgf-mic"></i><span class="i-name">.scicon-mgf-mic</span></div>
        <div class="the-icons span3" data-search="mic-off"><i class="scicon-mgf-mic-off"></i><span class="i-name">.scicon-mgf-mic-off</span></div>
        <div class="the-icons span3" data-search="clock"><i class="scicon-mgf-clock"></i><span class="i-name">.scicon-mgf-clock</span></div>
        <div class="the-icons span3" data-search="stopwatch"><i class="scicon-mgf-stopwatch"></i><span class="i-name">.scicon-mgf-stopwatch</span></div>
        <div class="the-icons span3" data-search="hourglass"><i class="scicon-mgf-hourglass"></i><span class="i-name">.scicon-mgf-hourglass</span></div>
        <div class="the-icons span3" data-search="zoom-in"><i class="scicon-mgf-zoom-in"></i><span class="i-name">.scicon-mgf-zoom-in</span></div>
        <div class="the-icons span3" data-search="zoom-out"><i class="scicon-mgf-zoom-out"></i><span class="i-name">.scicon-mgf-zoom-out</span></div>
        <div class="the-icons span3" data-search="down-open"><i class="scicon-mgf-down-open"></i><span class="i-name">.scicon-mgf-down-open</span></div>
        <div class="the-icons span3" data-search="left-open"><i class="scicon-mgf-left-open"></i><span class="i-name">.scicon-mgf-left-open</span></div>
        <div class="the-icons span3" data-search="right-open"><i class="scicon-mgf-right-open"></i><span class="i-name">.scicon-mgf-right-open</span></div>
        <div class="the-icons span3" data-search="up-open"><i class="scicon-mgf-up-open"></i><span class="i-name">.scicon-mgf-up-open</span></div>
        <div class="the-icons span3" data-search="down"><i class="scicon-mgf-down"></i><span class="i-name">.scicon-mgf-down</span></div>
        <div class="the-icons span3" data-search="left"><i class="scicon-mgf-left"></i><span class="i-name">.scicon-mgf-left</span></div>
        <div class="the-icons span3" data-search="mail"><i class="scicon-mgf-mail"></i><span class="i-name">.scicon-mgf-mail</span></div>
        <div class="the-icons span3" data-search="up"><i class="scicon-mgf-up"></i><span class="i-name">.scicon-mgf-up</span></div>
        <div class="the-icons span3" data-search="down-bold"><i class="scicon-mgf-down-bold"></i><span class="i-name">.scicon-mgf-down-bold</span></div>
        <div class="the-icons span3" data-search="left-bold"><i class="scicon-mgf-left-bold"></i><span class="i-name">.scicon-mgf-left-bold</span></div>
        <div class="the-icons span3" data-search="right-bold"><i class="scicon-mgf-right-bold"></i><span class="i-name">.scicon-mgf-right-bold</span></div>
        <div class="the-icons span3" data-search="up-bold"><i class="scicon-mgf-up-bold"></i><span class="i-name">.scicon-mgf-up-bold</span></div>
        <div class="the-icons span3" data-search="down-fat"><i class="scicon-mgf-down-fat"></i><span class="i-name">.scicon-mgf-down-fat</span></div>
        <div class="the-icons span3" data-search="left-fat"><i class="scicon-mgf-left-fat"></i><span class="i-name">.scicon-mgf-left-fat</span></div>
        <div class="the-icons span3" data-search="right-fat"><i class="scicon-mgf-right-fat"></i><span class="i-name">.scicon-mgf-right-fat</span></div>
        <div class="the-icons span3" data-search="up-fat"><i class="scicon-mgf-up-fat"></i><span class="i-name">.scicon-mgf-up-fat</span></div>
        <div class="the-icons span3" data-search="ccw"><i class="scicon-mgf-ccw"></i><span class="i-name">.scicon-mgf-ccw</span></div>
        <div class="the-icons span3" data-search="shuffle"><i class="scicon-mgf-shuffle"></i><span class="i-name">.scicon-mgf-shuffle</span></div>
        <div class="the-icons span3" data-search="play"><i class="scicon-mgf-play"></i><span class="i-name">.scicon-mgf-play</span></div>
        <div class="the-icons span3" data-search="pause"><i class="scicon-mgf-pause"></i><span class="i-name">.scicon-mgf-pause</span></div>
        <div class="the-icons span3" data-search="stop"><i class="scicon-mgf-stop"></i><span class="i-name">.scicon-mgf-stop</span></div>
        <div class="the-icons span3" data-search="to-end"><i class="scicon-mgf-to-end"></i><span class="i-name">.scicon-mgf-to-end</span></div>
        <div class="the-icons span3" data-search="to-start"><i class="scicon-mgf-to-start"></i><span class="i-name">.scicon-mgf-to-start</span></div>
        <div class="the-icons span3" data-search="fast-forward"><i class="scicon-mgf-fast-forward"></i><span class="i-name">.scicon-mgf-fast-forward</span></div>
        <div class="the-icons span3" data-search="fast-backward"><i class="scicon-mgf-fast-backward"></i><span class="i-name">.scicon-mgf-fast-backward</span></div>
        <div class="the-icons span3" data-search="trophy"><i class="scicon-mgf-trophy"></i><span class="i-name">.scicon-mgf-trophy</span></div>
        <div class="the-icons span3" data-search="monitor"><i class="scicon-mgf-monitor"></i><span class="i-name">.scicon-mgf-monitor</span></div>
        <div class="the-icons span3" data-search="tablet"><i class="scicon-mgf-tablet"></i><span class="i-name">.scicon-mgf-tablet</span></div>
        <div class="the-icons span3" data-search="mobile"><i class="scicon-mgf-mobile"></i><span class="i-name">.scicon-mgf-mobile</span></div>
        <div class="the-icons span3" data-search="data-science"><i class="scicon-mgf-data-science"></i><span class="i-name">.scicon-mgf-data-science</span></div>
        <div class="the-icons span3" data-search="data-science-inv"><i class="scicon-mgf-data-science-inv"></i><span class="i-name">.scicon-mgf-data-science-inv</span></div>
        <div class="the-icons span3" data-search="inbox"><i class="scicon-mgf-inbox"></i><span class="i-name">.scicon-mgf-inbox</span></div>
        <div class="the-icons span3" data-search="globe"><i class="scicon-mgf-globe"></i><span class="i-name">.scicon-mgf-globe</span></div>
        <div class="the-icons span3" data-search="globe-inv"><i class="scicon-mgf-globe-inv"></i><span class="i-name">.scicon-mgf-globe-inv</span></div>
        <div class="the-icons span3" data-search="flash"><i class="scicon-mgf-flash"></i><span class="i-name">.scicon-mgf-flash</span></div>
        <div class="the-icons span3" data-search="cloud"><i class="scicon-mgf-cloud"></i><span class="i-name">.scicon-mgf-cloud</span></div>
        <div class="the-icons span3" data-search="coverflow"><i class="scicon-mgf-coverflow"></i><span class="i-name">.scicon-mgf-coverflow</span></div>
        <div class="the-icons span3" data-search="coverflow-empty"><i class="scicon-mgf-coverflow-empty"></i><span class="i-name">.scicon-mgf-coverflow-empty</span></div>
        <div class="the-icons span3" data-search="math"><i class="scicon-mgf-math"></i><span class="i-name">.scicon-mgf-math</span></div>
        <div class="the-icons span3" data-search="math-circled"><i class="scicon-mgf-math-circled"></i><span class="i-name">.scicon-mgf-math-circled</span></div>
        <div class="the-icons span3" data-search="math-circled-empty"><i class="scicon-mgf-math-circled-empty"></i><span class="i-name">.scicon-mgf-math-circled-empty</span></div>
        <div class="the-icons span3" data-search="paper-plane"><i class="scicon-mgf-paper-plane"></i><span class="i-name">.scicon-mgf-paper-plane</span></div>
        <div class="the-icons span3" data-search="paper-plane-alt"><i class="scicon-mgf-paper-plane-alt"></i><span class="i-name">.scicon-mgf-paper-plane-alt</span></div>
        <div class="the-icons span3" data-search="paper-plane-alt2"><i class="scicon-mgf-paper-plane-alt2"></i><span class="i-name">.scicon-mgf-paper-plane-alt2</span></div>
        <div class="the-icons span3" data-search="fontsize"><i class="scicon-mgf-fontsize"></i><span class="i-name">.scicon-mgf-fontsize</span></div>
        <div class="the-icons span3" data-search="color-adjust"><i class="scicon-mgf-color-adjust"></i><span class="i-name">.scicon-mgf-color-adjust</span></div>
        <div class="the-icons span3" data-search="fire"><i class="scicon-mgf-fire"></i><span class="i-name">.scicon-mgf-fire</span></div>
        <div class="the-icons span3" data-search="chart-bar"><i class="scicon-mgf-chart-bar"></i><span class="i-name">.scicon-mgf-chart-bar</span></div>
        <div class="the-icons span3" data-search="hdd"><i class="scicon-mgf-hdd"></i><span class="i-name">.scicon-mgf-hdd</span></div>
        <div class="the-icons span3" data-search="connected-object"><i class="scicon-mgf-connected-object"></i><span class="i-name">.scicon-mgf-connected-object</span></div>
        <div class="the-icons span3" data-search="ruler"><i class="scicon-mgf-ruler"></i><span class="i-name">.scicon-mgf-ruler</span></div>
        <div class="the-icons span3" data-search="vector"><i class="scicon-mgf-vector"></i><span class="i-name">.scicon-mgf-vector</span></div>
        <div class="the-icons span3" data-search="vector-pencil"><i class="scicon-mgf-vector-pencil"></i><span class="i-name">.scicon-mgf-vector-pencil</span></div>
        <div class="the-icons span3" data-search="at"><i class="scicon-mgf-at"></i><span class="i-name">.scicon-mgf-at</span></div>
        <div class="the-icons span3" data-search="hash"><i class="scicon-mgf-hash"></i><span class="i-name">.scicon-mgf-hash</span></div>
        <div class="the-icons span3" data-search="female"><i class="scicon-mgf-female"></i><span class="i-name">.scicon-mgf-female</span></div>
        <div class="the-icons span3" data-search="male"><i class="scicon-mgf-male"></i><span class="i-name">.scicon-mgf-male</span></div>
        <div class="the-icons span3" data-search="spread"><i class="scicon-mgf-spread"></i><span class="i-name">.scicon-mgf-spread</span></div>
        <div class="the-icons span3" data-search="king"><i class="scicon-mgf-king"></i><span class="i-name">.scicon-mgf-king</span></div>
        <div class="the-icons span3" data-search="anchor"><i class="scicon-mgf-anchor"></i><span class="i-name">.scicon-mgf-anchor</span></div>
        <div class="the-icons span3" data-search="joystick"><i class="scicon-mgf-joystick"></i><span class="i-name">.scicon-mgf-joystick</span></div>
        <div class="the-icons span3" data-search="spinner1"><i class="scicon-mgf-spinner1"></i><span class="i-name">.scicon-mgf-spinner1</span></div>
        <div class="the-icons span3" data-search="spinner2"><i class="scicon-mgf-spinner2"></i><span class="i-name">.scicon-mgf-spinner2</span></div>
        <div class="the-icons span3" data-search="github"><i class="scicon-mgf-github"></i><span class="i-name">.scicon-mgf-github</span></div>
        <div class="the-icons span3" data-search="github-circled"><i class="scicon-mgf-github-circled"></i><span class="i-name">.scicon-mgf-github-circled</span></div>
        <div class="the-icons span3" data-search="github-circled-alt"><i class="scicon-mgf-github-circled-alt"></i><span class="i-name">.scicon-mgf-github-circled-alt</span></div>
        <div class="the-icons span3" data-search="github-circled-alt2"><i class="scicon-mgf-github-circled-alt2"></i><span class="i-name">.scicon-mgf-github-circled-alt2</span></div>
        <div class="the-icons span3" data-search="twitter"><i class="scicon-mgf-twitter"></i><span class="i-name">.scicon-mgf-twitter</span></div>
        <div class="the-icons span3" data-search="twitter-circled"><i class="scicon-mgf-twitter-circled"></i><span class="i-name">.scicon-mgf-twitter-circled</span></div>
        <div class="the-icons span3" data-search="facebook"><i class="scicon-mgf-facebook"></i><span class="i-name">.scicon-mgf-facebook</span></div>
        <div class="the-icons span3" data-search="facebook-circled"><i class="scicon-mgf-facebook-circled"></i><span class="i-name">.scicon-mgf-facebook-circled</span></div>
        <div class="the-icons span3" data-search="gplus"><i class="scicon-mgf-gplus"></i><span class="i-name">.scicon-mgf-gplus</span></div>
        <div class="the-icons span3" data-search="gplus-circled"><i class="scicon-mgf-gplus-circled"></i><span class="i-name">.scicon-mgf-gplus-circled</span></div>
        <div class="the-icons span3" data-search="linkedin"><i class="scicon-mgf-linkedin"></i><span class="i-name">.scicon-mgf-linkedin</span></div>
        <div class="the-icons span3" data-search="linkedin-circled"><i class="scicon-mgf-linkedin-circled"></i><span class="i-name">.scicon-mgf-linkedin-circled</span></div>
        <div class="the-icons span3" data-search="dribbble"><i class="scicon-mgf-dribbble"></i><span class="i-name">.scicon-mgf-dribbble</span></div>
        <div class="the-icons span3" data-search="dribbble-circled"><i class="scicon-mgf-dribbble-circled"></i><span class="i-name">.scicon-mgf-dribbble-circled</span></div>
        <div class="the-icons span3" data-search="instagram"><i class="scicon-mgf-instagram"></i><span class="i-name">.scicon-mgf-instagram</span></div>
        <div class="the-icons span3" data-search="instagram-circled"><i class="scicon-mgf-instagram-circled"></i><span class="i-name">.scicon-mgf-instagram-circled</span></div>
        <div class="the-icons span3" data-search="soundcloud"><i class="scicon-mgf-soundcloud"></i><span class="i-name">.scicon-mgf-soundcloud</span></div>
        <div class="the-icons span3" data-search="soundcloud-circled"><i class="scicon-mgf-soundcloud-circled"></i><span class="i-name">.scicon-mgf-soundcloud-circled</span></div>
        <div class="the-icons span3" data-search="mfg-logo"><i class="scicon-mgf-mfg-logo"></i><span class="i-name">.scicon-mgf-mfg-logo</span></div>
        <div class="the-icons span3" data-search="right"><i class="scicon-mgf-right"></i><span class="i-name">.scicon-mgf-right</span></div>

<div class="clear"></div><hr>
<a href="http://mfglabs.com/" target="_blank">http://mfglabs.com/</a>
<div class="clear"></div><hr><br>