/**
 * Additional script for theme settings page
 *
 * WARNING: This file is part of the core PrimaThemes framework.
 * DO NOT edit this file under any circumstances. 
 *
 * Credits (and Inspirations): 
 * - Genesis Framework by StudioPress http://studiopress.com 
 * - WooFramework by WooThemes http://woothemes.com
 * - OptionTree by Derek Herman https://github.com/valendesigns/option-tree
 * - Options Framework by Devin Price http://wptheming.com/options-framework-theme/‎ 
 */
 
jQuery(document).ready( function($) {

    var isUnsaved = false, $prima_settings = $('#prima-theme-settings');
	
	$('.button-reset').click(function() {
        return prima_confirm(prima.warnReset);
    })
	
    // Add dirty flag when we change an option
    $('input, select', $prima_settings).change(function() {
        isUnsaved = true;
    })
	
    // Remove dirty flag when we save options
    $('form', $prima_settings).submit (function() {
       isUnsaved = false; 
    });
	
    // Give warning if value changed and we try to leave the page before saving.
    $(window).bind('beforeunload', function(){
        if (isUnsaved) {
            return prima.warnUnsaved;
        }
    });
	
	// Tab
	tab = jQuery('.nav-tab-wrapper').children().first().attr('rel');
	jQuery('.prima-settings-section').hide();
	jQuery('.prima-settings-tab-' + tab).slideDown().show();
	jQuery('.prima-settings-nav').hide();
	jQuery('.prima-settings-nav-' + tab).slideDown().show();
	jQuery('.nav-tab-wrapper .nav-tab-setting').click(function(){
		jQuery('.nav-tab-wrapper .nav-tab-setting').removeClass('nav-tab-active');
		jQuery(this).addClass('nav-tab-active');
		tab = jQuery(this).attr('rel');
		jQuery('.prima-settings-section').hide();
		jQuery('.prima-settings-tab-' + tab).slideDown().show();
		jQuery('.prima-settings-nav').hide();
		jQuery('.prima-settings-nav-' + tab).slideDown().show();
		if ( tab == 'settings' ) {
			jQuery('.prima-settings-submit').hide();
		}
		else {
			jQuery('.prima-settings-submit').show();
		}
	});
	
	// Radio (Image)
	jQuery('.prima-radio-img-image').click(function(){
		jQuery(this).parent().parent().find('.prima-radio-img-image').removeClass('prima-radio-img-selected');
		jQuery(this).addClass('prima-radio-img-selected');
		
	});
	jQuery('.prima-radio-img-label').hide();
	jQuery('.prima-radio-img-image').show();
	jQuery('.prima-radio-img-radio').hide();
	
	// Upload
	jQuery(".prima_upload_button").click( function( event ) {
        formfield = jQuery(this).prev('input').attr('id');
        formID = jQuery(this).attr('rel');
		formtitle = jQuery(this).parents('.section').find('.heading').text();
		event.preventDefault();
		prima_file_frame = null;
		prima_file_frame = wp.media.frames.downloadable_file = wp.media({
			title: formtitle,
			button: {
				text: prima.useImage,
			},
			library: {
				type: 'image'
			},
			multiple: false
		});
		prima_file_frame.on( 'select', function() {
			attachment = prima_file_frame.state().get('selection').first().toJSON();
            btnContent = '<img src="'+attachment.url+'" alt="" /><a href="#" class="prima_upload_remove">'+prima.removeImage+'</a>';
			jQuery('#' + formfield).val(attachment.url);
			jQuery('#' + formfield).parents('fieldset').find('.prima_upload_screenshot').slideDown().html(btnContent);
		});
		prima_file_frame.open();
	});
	jQuery('.prima_upload_remove').live('click', function(event) { 
		event.preventDefault();
		jQuery(this).hide();
		jQuery(this).parents('fieldset').find('.prima_upload').attr('value', '');
		jQuery(this).parents('.prima_upload_screenshot').slideUp();
	});
	
});

// Confirmation
function prima_confirm(text){
	var answer=confirm(text);
	if(answer){return true;}
	else{return false;}
}
