/**
 * Additional script for post/taxonomy metaboxes
 *
 * WARNING: This file is part of the core PrimaThemes framework.
 * DO NOT edit this file under any circumstances. 
 *
 * Credits (and Inspirations): 
 * - Genesis Framework by StudioPress http://studiopress.com 
 * - WooFramework by WooThemes http://woothemes.com
 * - OptionTree by Derek Herman https://github.com/valendesigns/option-tree
 * - Options Framework by Devin Price http://wptheming.com/options-framework-theme/‎ 
 */
 
jQuery(document).ready(function(){
	
	//JQUERY MEDIA UPLOAD
	jQuery(".prima_upload_button").click( function( event ) {
        formfield = jQuery(this).prev('input').attr('id');
        formID = jQuery(this).attr('rel');
		formtitle = jQuery(this).parents('tr').find('th.meta_names label').text();;
		event.preventDefault();
		prima_file_frame = null;
		prima_file_frame = wp.media.frames.downloadable_file = wp.media({
			title: formtitle,
			button: {
				text: prima.useImage,
			},
			library: {
				type: 'image'
			},
			multiple: false
		});
		prima_file_frame.on( 'select', function() {
			attachment = prima_file_frame.state().get('selection').first().toJSON();
            btnContent = '<img src="'+attachment.url+'" alt="" /><a href="#" class="prima_upload_remove">'+prima.removeImage+'</a>';
			jQuery('#' + formfield).val(attachment.url);
			jQuery('#' + formfield).parents('td').find('.prima_upload_screenshot').slideDown().html(btnContent);
		});
		prima_file_frame.open();
	});
	jQuery('.prima_upload_remove').live('click', function(event) { 
		event.preventDefault();
		jQuery(this).hide();
		jQuery(this).parents('td').find('.prima_upload').attr('value', '');
		jQuery(this).parents('.prima_upload_screenshot').slideUp();
	});
	
	jQuery('.meta-radio-img-image').click(function(){
		jQuery(this).parent().find('.meta-radio-img-image').removeClass('meta-radio-img-selected');
		jQuery(this).addClass('meta-radio-img-selected');
	});
	jQuery('.meta-radio-img-label').hide();
	jQuery('.meta-radio-img-image').show();
	jQuery('.meta-radio-img-radio').hide();
});
