<?php
/**
 * Functions to handle shortcodes
 *
 * WARNING: This file is part of the core PrimaThemes framework.
 * DO NOT edit this file under any circumstances. 
 *
 * @category   PrimaThemes
 * @package    Framework
 * @subpackage Functions
 * @author     PrimaThemes
 * @link       http://www.primathemes.com
 */

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

/**
 * Add shortcode generator button to visual editor.
 *
 * @since PrimaShop 2.0
 */
add_action( 'init', 'prima_shortcode_add_button' );
function prima_shortcode_add_button() {
	if ( ! current_user_can('edit_posts') && ! current_user_can('edit_pages') ) return;
	if ( get_user_option('rich_editing') == 'true') :
		add_filter('mce_external_plugins', 'prima_shortcode_add_tinymce_plugin');
		add_filter('mce_buttons', 'prima_shortcode_register_button', 1);
	endif;
}

/**
 * Register shortcode generator button.
 *
 * @since PrimaShop 2.0
 */
function prima_shortcode_register_button($buttons) {
	array_push($buttons, "PrimaShortcodes");
	return $buttons;
}

/**
 * Register shortcode generator javascript.
 *
 * @since PrimaShop 2.0
 */
function prima_shortcode_add_tinymce_plugin($plugin_array) {
	global $prima;
	$plugin_array['PrimaShortcodes'] = PRIMA_CUSTOM_URI . '/theme/js/shortcodes.js';
	return $plugin_array;
}

/**
 * Register shortcode generator icon
 *
 * @since PrimaShop 2.0
 */
add_action( 'admin_head', 'prima_shortcode_add_style' );
function prima_shortcode_add_style() {
	$icon = prima_get_setting( "adminlogo_url" );
	if ( !$icon ) return;
	echo '
	<style type="text/css">
	.mce-ico.mce-i-PrimaShortcodes { background-image: url('.PRIMA_URI.'/inc/theme/images/shortcodes.png) !important; }
	</style>
	';
}