<?php

class FontAwesomeMigrateHelper {



    public static function FontAwesomeMigrate ($value) {

        $newclasses = array(
            'fa fa-ban',
            'fa fa-bar-chart-o',
            'fa fa-flask',
            'fa fa-bell-o',
            'fa fa-bell',
            'fa fa-bitbucket-square',
            'fa fa-bookmark-o',
            'fa fa-building-o',
            'fa fa-calendar-o',
            'fa fa-square-o',
            'fa fa-minus-square-o',
            'fa fa-check-square',
            'fa fa-check-square-o',
            'fa fa-chevron-down',
            'fa fa-chevron-left',
            'fa fa-chevron-right',
            'fa fa-chevron-up',
            'fa fa-arrow-circle-down',
            'fa fa-arrow-circle-left',
            'fa fa-arrow-circle-right',
            'fa fa-arrow-circle-up',
            'fa fa-circle-o',
            'fa fa-rub',
            'fa fa-minus-square-o',
            'fa fa-caret-square-o-up',
            'fa fa-caret-square-o-down',
            'fa fa-comment-o',
            'fa fa-comments-o',
            'fa fa-files-o',
            'fa fa-scissors',
            'fa fa-tachometer',
            'fa fa-angle-double-down',
            'fa fa-angle-double-left',
            'fa fa-angle-double-right',
            'fa fa-angle-double-up',
            'fa fa-arrow-circle-o-down',
            'fa fa-download',
            'fa fa-pencil-square',
            'fa fa-pencil-square-o',
            'fa fa-ellipsis-h ',
            'fa fa-ellipsis-v ',
            'fa fa-envelope-o',
            'fa fa-exclamation-circle',
            'fa fa-plus-square-o',
            'fa fa-caret-square-o-right',
            'fa fa-external-link-square',
            'fa fa-eye-slash',
            'fa fa-eye',
            'fa fa-facebook-square',
            'fa fa-video-camera',
            'fa fa-file-o',
            'fa fa-file-text-o',
            'fa fa-flag-o',
            'fa fa-folder-o',
            'fa fa-folder',
            'fa fa-folder-open-o',
            'fa fa-cutlery',
            'fa fa-frown-o',
            'fa fa-arrows-alt',
            'fa fa-github-square',
            'fa fa-google-plus-square',
            'fa fa-users',
            'fa fa-h-square',
            'fa fa-hand-o-down',
            'fa fa-hand-o-left',
            'fa fa-hand-o-right',
            'fa fa-hand-o-up',
            'fa fa-hdd-o',
            'fa fa-heart-o',
            'fa fa-hospital-o',
            'fa fa-outdent',
            'fa fa-indent',
            'fa fa-info-circle',
            'fa fa-keyboard-o',
            'fa fa-gavel',
            'fa fa-lemon-o',
            'fa fa-lightbulb-o',
            'fa fa-linkedin-square',
            'fa fa-meh-o',
            'fa fa-microphone-slash',
            'fa fa-minus-square',
            'fa fa-minus-circle',
            'fa fa-mobile',
            'fa fa-moon-o',
            'fa fa-arrows',
            'fa fa-power-off',
            'fa fa-check-circle-o',
            'fa fa-check-circle',
            'fa fa-check',
            'fa fa-paperclip',
            'fa fa-clipboard',
            'fa fa-phone-square',
            'fa fa-picture-o',
            'fa fa-pinterest-square',
            'fa fa-play-circle-o',
            'fa fa-play-circle',
            'fa fa-plus-square',
            'fa fa-plus-circle',
            'fa fa-thumb-tack',
            'fa fa-question-circle',
            'fa fa-times-circle-o',
            'fa fa-times-circle',
            'fa fa-times',
            'fa fa-bars',
            'fa fa-expand',
            'fa fa-arrows-h',
            'fa fa-compress',
            'fa fa-arrows-v',
            'fa fa-rss-square',
            'fa fa-floppy-o',
            'fa fa-crosshairs',
            'fa fa-share',
            'fa fa-share-square',
            'fa fa-share-square-o',
            'fa fa-square',
            'fa fa-sign-in',
            'fa fa-sign-out',
            'fa fa-smile-o',
            'fa fa-sort-alpha-desc',
            'fa fa-sort-alpha-asc',
            'fa fa-sort-amount-desc',
            'fa fa-sort-amount-asc',
            'fa fa-sort-numeric-desc',
            'fa fa-sort-numeric-asc',
            'fa fa-sort-desc',
            'fa fa-sort-asc',
            'fa fa-stack-overflow',
            'fa fa-star-o',
            'fa fa-star-half-o',
            'fa fa-sun-o',
            'fa fa-thumbs-o-down',
            'fa fa-thumbs-o-up',
            'fa fa-clock-o',
            'fa fa-trash-o',
            'fa fa-tumblr-square',
            'fa fa-twitter-square',
            'fa fa-chain-broken',
            'fa fa-arrow-circle-o-up',
            'fa fa-upload',
            'fa fa-exclamation-triangle',
            'fa fa-xing-square',
            'fa fa-youtube-square',
            'fa fa-search-plus',
            'fa fa-search-minus',
            'fa fa-credit-card',
            'fa fa-globe',
            'fa fa-thumbs-up',
            'fa fa-desktop',
            'fa fa-cogs',
            'fa fa-adn',
            'fa fa-android',
            'fa fa-apple',
            'fa fa-bitbucket',
            'fa fa-bitbucket-sign',
            'fa fa-bitcoin',
            'fa fa-btc',
            'fa fa-css3',
            'fa fa-dribbble',
            'fa fa-dropbox',
            'fa fa-facebook',
            'fa fa-facebook-sign',
            'fa fa-flickr',
            'fa fa-foursquare',
            'fa fa-github',
            'fa fa-github-alt',
            'fa fa-github-sign',
            'fa fa-gittip',
            'fa fa-google-plus',
            'fa fa-google-plus-sign',
            'fa fa-html5',
            'fa fa-instagram',
            'fa fa-linkedin',
            'fa fa-linkedin-sign',
            'fa fa-linux',
            'fa fa-maxcdn',
            'fa fa-pinterest',
            'fa fa-pinterest-sign',
            'fa fa-renren',
            'fa fa-skype',
            'fa fa-stackexchange',
            'fa fa-trello',
            'fa fa-tumblr',
            'fa fa-tumblr-sign',
            'fa fa-twitter',
            'fa fa-twitter-sign',
            'fa fa-vk',
            'fa fa-weibo',
            'fa fa-windows',
            'fa fa-xing',
            'fa fa-xing-sign',
            'fa fa-youtube',
            'fa fa-youtube-play',
            'fa fa-youtube-sign',
            'fa fa-adjust',
            'fa fa-anchor',
            'fa fa-archive',
            'fa fa-asterisk',
            'fa fa-ban-circle',
            'fa fa-bar-chart',
            'fa fa-barcode',
            'fa fa-beaker',
            'fa fa-beer',
            'fa fa-bell',
            'fa fa-bell-alt',
            'fa fa-bolt',
            'fa fa-book',
            'fa fa-bookmark',
            'fa fa-bookmark-empty',
            'fa fa-briefcase',
            'fa fa-bug',
            'fa fa-building',
            'fa fa-bullhorn',
            'fa fa-bullseye',
            'fa fa-calendar',
            'fa fa-calendar-empty',
            'fa fa-camera',
            'fa fa-camera-retro',
            'fa fa-certificate',
            'fa fa-check',
            'fa fa-check-empty',
            'fa fa-check-minus',
            'fa fa-check-sign',
            'fa fa-circle',
            'fa fa-circle-blank',
            'fa fa-cloud',
            'fa fa-cloud-download',
            'fa fa-cloud-upload',
            'fa fa-code',
            'fa fa-code-fork',
            'fa fa-coffee',
            'fa fa-cog',
            'fa fa-cogs',
            'fa fa-collapse',
            'fa fa-collapse-alt',
            'fa fa-collapse-top',
            'fa fa-comment',
            'fa fa-comment-alt',
            'fa fa-comments',
            'fa fa-comments-alt',
            'fa fa-compass',
            'fa fa-credit-card',
            'fa fa-crop',
            'fa fa-dashboard',
            'fa fa-desktop',
            'fa fa-download',
            'fa fa-download-alt',
            'fa fa-edit',
            'fa fa-edit-sign',
            'fa fa-ellipsis-horizontal',
            'fa fa-ellipsis-vertical',
            'fa fa-envelope',
            'fa fa-envelope-alt',
            'fa fa-eraser',
            'fa fa-exchange',
            'fa fa-exclamation',
            'fa fa-exclamation-sign',
            'fa fa-expand',
            'fa fa-expand-alt',
            'fa fa-external-link',
            'fa fa-external-link-sign',
            'fa fa-eye-close',
            'fa fa-eye-open',
            'fa fa-facetime-video',
            'fa fa-female',
            'fa fa-fighter-jet',
            'fa fa-film',
            'fa fa-filter',
            'fa fa-fire',
            'fa fa-fire-extinguisher',
            'fa fa-flag',
            'fa fa-flag-alt',
            'fa fa-flag-checkered',
            'fa fa-folder-close',
            'fa fa-folder-close-alt',
            'fa fa-folder-open',
            'fa fa-folder-open-alt',
            'fa fa-food',
            'fa fa-frown',
            'fa fa-gamepad',
            'fa fa-gear',
            'fa fa-gears',
            'fa fa-gift',
            'fa fa-glass',
            'fa fa-globe',
            'fa fa-group',
            'fa fa-hdd',
            'fa fa-headphones',
            'fa fa-heart',
            'fa fa-heart-empty',
            'fa fa-home',
            'fa fa-inbox',
            'fa fa-info',
            'fa fa-info-sign',
            'fa fa-key',
            'fa fa-keyboard',
            'fa fa-laptop',
            'fa fa-leaf',
            'fa fa-legal',
            'fa fa-lemon',
            'fa fa-level-down',
            'fa fa-level-up',
            'fa fa-lightbulb',
            'fa fa-location-arrow',
            'fa fa-lock',
            'fa fa-magic',
            'fa fa-magnet',
            'fa fa-mail-forward',
            'fa fa-mail-reply',
            'fa fa-mail-reply-all',
            'fa fa-male',
            'fa fa-map-marker',
            'fa fa-meh',
            'fa fa-microphone',
            'fa fa-microphone-off',
            'fa fa-minus',
            'fa fa-minus-sign',
            'fa fa-minus-sign-alt',
            'fa fa-mobile-phone',
            'fa fa-money',
            'fa fa-moon',
            'fa fa-move',
            'fa fa-music',
            'fa fa-off',
            'fa fa-ok',
            'fa fa-ok-circle',
            'fa fa-ok-sign',
            'fa fa-pencil',
            'fa fa-phone',
            'fa fa-phone-sign',
            'fa fa-picture',
            'fa fa-plane',
            'fa fa-plus',
            'fa fa-plus-sign',
            'fa fa-plus-sign-alt',
            'fa fa-power-off',
            'fa fa-print',
            'fa fa-pushpin',
            'fa fa-puzzle-piece',
            'fa fa-qrcode',
            'fa fa-question',
            'fa fa-question-sign',
            'fa fa-quote-left',
            'fa fa-quote-right',
            'fa fa-random',
            'fa fa-refresh',
            'fa fa-remove',
            'fa fa-remove-circle',
            'fa fa-remove-sign',
            'fa fa-reorder',
            'fa fa-reply',
            'fa fa-reply-all',
            'fa fa-resize-horizontal',
            'fa fa-resize-vertical',
            'fa fa-retweet',
            'fa fa-road',
            'fa fa-rocket',
            'fa fa-rss',
            'fa fa-rss-sign',
            'fa fa-screenshot',
            'fa fa-search',
            'fa fa-share',
            'fa fa-share-alt',
            'fa fa-share-sign',
            'fa fa-shield',
            'fa fa-shopping-cart',
            'fa fa-sign-blank',
            'fa fa-signal',
            'fa fa-signin',
            'fa fa-signout',
            'fa fa-sitemap',
            'fa fa-smile',
            'fa fa-sort',
            'fa fa-sort-by-alphabet',
            'fa fa-sort-by-alphabet-alt',
            'fa fa-sort-by-attributes',
            'fa fa-sort-by-attributes',
            'fa fa-sort-by-order',
            'fa fa-sort-by-order-alt',
            'fa fa-sort-down',
            'fa fa-sort-up',
            'fa fa-spinner',
            'fa fa-star',
            'fa fa-star-empty',
            'fa fa-star-half',
            'fa fa-star-half-empty',
            'fa fa-star-half-full',
            'fa fa-subscript',
            'fa fa-suitcase',
            'fa fa-sun-o',
            'fa fa-superscript',
            'fa fa-tablet',
            'fa fa-tag',
            'fa fa-tags',
            'fa fa-tasks',
            'fa fa-terminal',
            'fa fa-thumbs-down',
            'fa fa-thumbs-down-alt',
            'fa fa-thumbs-up',
            'fa fa-thumbs-up-alt',
            'fa fa-ticket',
            'fa fa-time',
            'fa fa-tint',
            'fa fa-trash',
            'fa fa-trophy',
            'fa fa-truck',
            'fa fa-umbrella',
            'fa fa-unchecked',
            'fa fa-unlock',
            'fa fa-unlock-alt',
            'fa fa-upload',
            'fa fa-upload-alt',
            'fa fa-user',
            'fa fa-volume-down',
            'fa fa-volume-off',
            'fa fa-volume-up',
            'fa fa-warning-sign',
            'fa fa-wrench',
            'fa fa-zoom-in',
            'fa fa-zoom-out',
            'fa fa-bitcoin',
            'fa fa-btc',
            'fa fa-cny',
            'fa fa-dollar',
            'fa fa-eur',
            'fa fa-euro',
            'fa fa-gbp',
            'fa fa-inr',
            'fa fa-jpy',
            'fa fa-krw',
            'fa fa-renminbi',
            'fa fa-rupee',
            'fa fa-usd',
            'fa fa-won',
            'fa fa-yen',
            'fa fa-align-center',
            'fa fa-align-justify',
            'fa fa-align-left',
            'fa fa-align-right',
            'fa fa-bold',
            'fa fa-columns',
            'fa fa-copy',
            'fa fa-cut',
            'fa fa-eraser',
            'fa fa-file',
            'fa fa-file-alt',
            'fa fa-file-text',
            'fa fa-file-text-alt',
            'fa fa-font',
            'fa fa-indent-left',
            'fa fa-indent-right',
            'fa fa-italic',
            'fa fa-link',
            'fa fa-list',
            'fa fa-list-alt',
            'fa fa-list-ol',
            'fa fa-list-ul',
            'fa fa-paper-clip',
            'fa fa-paperclip',
            'fa fa-paste',
            'fa fa-repeat',
            'fa fa-rotate-left',
            'fa fa-rotate-right',
            'fa fa-save',
            'fa fa-strikethrough',
            'fa fa-table',
            'fa fa-text-height',
            'fa fa-text-width',
            'fa fa-th',
            'fa fa-th-large',
            'fa fa-th-list',
            'fa fa-underline',
            'fa fa-undo',
            'fa fa-unlink',
            'fa fa-angle-down',
            'fa fa-angle-left',
            'fa fa-angle-right',
            'fa fa-angle-up',
            'fa fa-arrow-down',
            'fa fa-arrow-left',
            'fa fa-arrow-right',
            'fa fa-arrow-up',
            'fa fa-caret-down',
            'fa fa-caret-left',
            'fa fa-caret-right',
            'fa fa-caret-up',
            'fa fa-chevron-down',
            'fa fa-chevron-left',
            'fa fa-chevron-right',
            'fa fa-chevron-sign-down',
            'fa fa-chevron-sign-left',
            'fa fa-chevron-sign-right',
            'fa fa-chevron-sign-up',
            'fa fa-chevron-up',
            'fa fa-circle-arrow-down',
            'fa fa-circle-arrow-left',
            'fa fa-circle-arrow-right',
            'fa fa-circle-arrow-up',
            'fa fa-double-angle-down',
            'fa fa-double-angle-left',
            'fa fa-double-angle-right',
            'fa fa-double-angle-up',
            'fa fa-hand-down',
            'fa fa-hand-left',
            'fa fa-hand-right',
            'fa fa-hand-up',
            'fa fa-long-arrow-down',
            'fa fa-long-arrow-left',
            'fa fa-long-arrow-right',
            'fa fa-long-arrow-up',
            'fa fa-backward',
            'fa fa-eject',
            'fa fa-fast-backward',
            'fa fa-fast-forward',
            'fa fa-forward',
            'fa fa-fullscreen',
            'fa fa-pause',
            'fa fa-play',
            'fa fa-play-circle',
            'fa fa-play-sign',
            'fa fa-resize-full',
            'fa fa-resize-small',
            'fa fa-backward',
            'fa fa-step-forward',
            'fa fa-stop',
            'fa fa-youtube-play',
            'fa fa-ambulance',
            'fa fa-h-sign',
            'fa fa-hospital',
            'fa fa-medkit',
            'fa fa-plus-sign-alt',
            'fa fa-stethoscope',
            'fa fa-user-md',
        );


       $oldclasses = array(
            'icon-ban-circle',
            'icon-bar-chart',
            'icon-beaker',
            'icon-bell',
            'icon-bell-alt',
            'icon-bitbucket-sign',
            'icon-bookmark-empty',
            'icon-building',
            'icon-calendar-empty',
            'icon-check-empty',
            'icon-check-minus',
            'icon-check-sign',
            'icon-check',
            'icon-chevron-sign-down',
            'icon-chevron-sign-left',
            'icon-chevron-sign-right',
            'icon-chevron-sign-up',
            'icon-circle-arrow-down',
            'icon-circle-arrow-left',
            'icon-circle-arrow-right',
            'icon-circle-arrow-up',
            'icon-circle-blank',
            'icon-cny',
            'icon-collapse-alt',
            'icon-collapse-top',
            'icon-collapse',
            'icon-comment-alt',
            'icon-comments-alt',
            'icon-copy',
            'icon-cut',
            'icon-dashboard',
            'icon-double-angle-down',
            'icon-double-angle-left',
            'icon-double-angle-right',
            'icon-double-angle-up',
            'icon-download',
            'icon-download-alt',
            'icon-edit-sign',
            'icon-edit',
            'icon-ellipsis-horizontal',
            'icon-ellipsis-vertical',
            'icon-envelope-alt',
            'icon-exclamation-sign',
            'icon-expand-alt',
            'icon-expand',
            'icon-external-link-sign',
            'icon-eye-close',
            'icon-eye-open',
            'icon-facebook-sign',
            'icon-facetime-video',
            'icon-file-alt',
            'icon-file-text-alt',
            'icon-flag-alt',
            'icon-folder-close-alt',
            'icon-folder-close',
            'icon-folder-open-alt',
            'icon-food',
            'icon-frown',
            'icon-fullscreen',
            'icon-github-sign',
            'icon-google-plus-sign',
            'icon-group',
            'icon-h-sign',
            'icon-hand-down',
            'icon-hand-left',
            'icon-hand-right',
            'icon-hand-up',
            'icon-hdd',
            'icon-heart-empty',
            'icon-hospital',
            'icon-indent-left',
            'icon-indent-right',
            'icon-info-sign',
            'icon-keyboard',
            'icon-legal',
            'icon-lemon',
            'icon-lightbulb',
            'icon-linkedin-sign',
            'icon-meh',
            'icon-microphone-off',
            'icon-minus-sign-alt',
            'icon-minus-sign',
            'icon-mobile-phone',
            'icon-moon',
            'icon-move',
            'icon-off',
            'icon-ok-circle',
            'icon-ok-sign',
            'icon-ok',
            'icon-paper-clip',
            'icon-paste',
            'icon-phone-sign',
            'icon-picture',
            'icon-pinterest-sign',
            'icon-play-circle',
            'icon-play-sign',
            'icon-plus-sign-alt',
            'icon-plus-sign',
            'icon-pushpin',
            'icon-question-sign',
            'icon-remove-circle',
            'icon-remove-sign',
            'icon-remove',
            'icon-reorder',
            'icon-resize-full',
            'icon-resize-horizontal',
            'icon-resize-small',
            'icon-resize-vertical',
            'icon-rss-sign',
            'icon-save',
            'icon-screenshot',
            'icon-share-alt',
            'icon-share-sign',
            'icon-share',
            'icon-sign-blank',
            'icon-signin',
            'icon-signout',
            'icon-smile',
            'icon-sort-by-alphabet-alt',
            'icon-sort-by-alphabet',
            'icon-sort-by-attributes-alt',
            'icon-sort-by-attributes',
            'icon-sort-by-order-alt',
            'icon-sort-by-order',
            'icon-sort-down',
            'icon-sort-up',
            'icon-stackexchange',
            'icon-star-empty',
            'icon-star-half-empty',
            'icon-sun',
            'icon-thumbs-down-alt',
            'icon-thumbs-up-alt',
            'icon-time',
            'icon-trash',
            'icon-tumblr-sign',
            'icon-twitter-sign',
            'icon-unlink',
            'icon-upload',
            'icon-upload-alt',
            'icon-warning-sign',
            'icon-xing-sign',
            'icon-youtube-sign',
            'icon-zoom-in',
            'icon-zoom-out',
            'icon-credit-card',
            'icon-globe',
            'icon-thumbs-up',
            'icon-desktop',
            'icon-cogs',
            'icon-adn',
           'icon-android',
           'icon-apple',
           'icon-bitbucket',
           'icon-bitbucket-sign',
           'icon-bitcoin',
           'icon-btc',
           'icon-css3',
           'icon-dribbble',
           'icon-dropbox',
           'icon-facebook',
           'icon-facebook-sign',
           'icon-flickr',
           'icon-foursquare',
           'icon-github',
           'icon-github-alt',
           'icon-github-sign',
           'icon-gittip',
           'icon-google-plus',
           'icon-google-plus-sign',
           'icon-html5',
           'icon-instagram',
           'icon-linkedin',
           'icon-linkedin-sign',
           'icon-linux',
           'icon-maxcdn',
           'icon-pinterest',
           'icon-pinterest-sign',
           'icon-renren',
           'icon-skype',
           'icon-stackexchange',
           'icon-trello',
           'icon-tumblr',
           'icon-tumblr-sign',
           'icon-twitter',
           'icon-twitter-sign',
           'icon-vk',
           'icon-weibo',
           'icon-windows',
           'icon-xing',
           'icon-xing-sign',
           'icon-youtube',
           'icon-youtube-play',
           'icon-youtube-sign',
           'icon-adjust',
           'icon-anchor',
           'icon-archive',
           'icon-asterisk',
           'icon-ban-circle',
 'icon-bar-chart',
 'icon-barcode',
 'icon-beaker',
 'icon-beer',
 'icon-bell',
 'icon-bell-alt',
 'icon-bolt',
 'icon-book',
 'icon-bookmark',
 'icon-bookmark-empty',
 'icon-briefcase',
 'icon-bug',
 'icon-building',
 'icon-bullhorn',
 'icon-bullseye',
 'icon-calendar',
 'icon-calendar-empty',
 'icon-camera',
 'icon-camera-retro',
 'icon-certificate',
 'icon-check',
 'icon-check-empty',
 'icon-check-minus',
 'icon-check-sign',
 'icon-circle',
 'icon-circle-blank',
 'icon-cloud',
 'icon-cloud-download',
 'icon-cloud-upload',
 'icon-code',
 'icon-code-fork',
 'icon-coffee',
 'icon-cog',
 'icon-cogs',
 'icon-collapse',
 'icon-collapse-alt',
 'icon-collapse-top',
 'icon-comment',
 'icon-comment-alt',
 'icon-comments',
 'icon-comments-alt',
 'icon-compass',
 'icon-credit-card',
 'icon-crop',
 'icon-dashboard',
 'icon-desktop',
 'icon-download',
 'icon-download-alt',
 'icon-edit',
 'icon-edit-sign',
 'icon-ellipsis-horizontal',
 'icon-ellipsis-vertical',
 'icon-envelope',
 'icon-envelope-alt',
 'icon-eraser',
 'icon-exchange',
 'icon-exclamation',
 'icon-exclamation-sign',
 'icon-expand',
 'icon-expand-alt',
 'icon-external-link',
 'icon-external-link-sign',
 'icon-eye-close',
 'icon-eye-open',
 'icon-facetime-video',
 'icon-female',
 'icon-fighter-jet',
 'icon-film',
 'icon-filter',
 'icon-fire',
 'icon-fire-extinguisher',
 'icon-flag',
 'icon-flag-alt',
 'icon-flag-checkered',
 'icon-folder-close',
 'icon-folder-close-alt',
 'icon-folder-open',
 'icon-folder-open-alt',
 'icon-food',
 'icon-frown',
 'icon-gamepad',
 'icon-gear',
 'icon-gears',
 'icon-gift',
 'icon-glass',
 'icon-globe',
 'icon-group',
 'icon-hdd',
 'icon-headphones',
 'icon-heart',
 'icon-heart-empty',
 'icon-home',
 'icon-inbox',
 'icon-info',
 'icon-info-sign',
 'icon-key',
 'icon-keyboard',
 'icon-laptop',
 'icon-leaf',
 'icon-legal',
 'icon-lemon',
 'icon-level-down',
 'icon-level-up',
 'icon-lightbulb',
 'icon-location-arrow',
 'icon-lock',
 'icon-magic',
 'icon-magnet',
 'icon-mail-forward',
 'icon-mail-reply',
 'icon-mail-reply-all',
 'icon-male',
 'icon-map-marker',
 'icon-meh',
 'icon-microphone',
 'icon-microphone-off',
 'icon-minus',
 'icon-minus-sign',
 'icon-minus-sign-alt',
 'icon-mobile-phone',
 'icon-money',
 'icon-moon',
 'icon-move',
 'icon-music',
 'icon-off',
 'icon-ok',
 'icon-ok-circle',
 'icon-ok-sign',
 'icon-pencil',
 'icon-phone',
 'icon-phone-sign',
 'icon-picture',
 'icon-plane',
 'icon-plus',
 'icon-plus-sign',
 'icon-plus-sign-alt',
 'icon-power-off',
 'icon-print',
 'icon-pushpin',
 'icon-puzzle-piece',
 'icon-qrcode',
 'icon-question',
 'icon-question-sign',
 'icon-quote-left',
 'icon-quote-right',
 'icon-random',
 'icon-refresh',
 'icon-remove',
 'icon-remove-circle',
 'icon-remove-sign',
 'icon-reorder',
 'icon-reply',
 'icon-reply-all',
 'icon-resize-horizontal',
 'icon-resize-vertical',
 'icon-retweet',
 'icon-road',
 'icon-rocket',
 'icon-rss',
 'icon-rss-sign',
 'icon-screenshot',
 'icon-search',
 'icon-share',
 'icon-share-alt',
 'icon-share-sign',
 'icon-shield',
 'icon-shopping-cart',
 'icon-sign-blank',
 'icon-signal',
 'icon-signin',
 'icon-signout',
 'icon-sitemap',
 'icon-smile',
 'icon-sort',
 'icon-sort-by-alphabet',
 'icon-sort-by-alphabet-alt',
 'icon-sort-by-attributes',
 'icon-sort-by-attributes',
 'icon-sort-by-order',
 'icon-sort-by-order-alt',
 'icon-sort-down',
 'icon-sort-up',
 'icon-spinner',
 'icon-star',
 'icon-star-empty',
 'icon-star-half',
 'icon-star-half-empty',
 'icon-star-half-full',
 'icon-subscript',
 'icon-suitcase',
 'icon-sun-o',
 'icon-superscript',
 'icon-tablet',
 'icon-tag',
 'icon-tags',
 'icon-tasks',
 'icon-terminal',
 'icon-thumbs-down',
 'icon-thumbs-down-alt',
 'icon-thumbs-up',
 'icon-thumbs-up-alt',
 'icon-ticket',
 'icon-time',
 'icon-tint',
 'icon-trash',
 'icon-trophy',
 'icon-truck',
 'icon-umbrella',
 'icon-unchecked',
 'icon-unlock',
 'icon-unlock-alt',
 'icon-upload',
 'icon-upload-alt',
 'icon-user',
 'icon-volume-down',
 'icon-volume-off',
 'icon-volume-up',
 'icon-warning-sign',
 'icon-wrench',
 'icon-zoom-in',
 'icon-zoom-out',
 'icon-bitcoin',
 'icon-btc',
 'icon-cny',
 'icon-dollar',
 'icon-eur',
 'icon-euro',
 'icon-gbp',
 'icon-inr',
 'icon-jpy',
 'icon-krw',
 'icon-renminbi',
 'icon-rupee',
 'icon-usd',
 'icon-won',
 'icon-yen',
 'icon-align-center',
 'icon-align-justify',
 'icon-align-left',
 'icon-align-right',
 'icon-bold',
 'icon-columns',
 'icon-copy',
 'icon-cut',
 'icon-eraser',
 'icon-file',
 'icon-file-alt',
 'icon-file-text',
 'icon-file-text-alt',
 'icon-font',
 'icon-indent-left',
 'icon-indent-right',
 'icon-italic',
 'icon-link',
 'icon-list',
 'icon-list-alt',
 'icon-list-ol',
 'icon-list-ul',
 'icon-paper-clip',
 'icon-paperclip',
 'icon-paste',
 'icon-repeat',
 'icon-rotate-left',
 'icon-rotate-right',
 'icon-save',
 'icon-strikethrough',
 'icon-table',
 'icon-text-height',
 'icon-text-width',
 'icon-th',
 'icon-th-large',
 'icon-th-list',
 'icon-underline',
 'icon-undo',
 'icon-unlink',
 'icon-angle-down',
 'icon-angle-left',
 'icon-angle-right',
 'icon-angle-up',
 'icon-arrow-down',
 'icon-arrow-left',
 'icon-arrow-right',
 'icon-arrow-up',
 'icon-caret-down',
 'icon-caret-left',
 'icon-caret-right',
 'icon-caret-up',
 'icon-chevron-down',
 'icon-chevron-left',
 'icon-chevron-right',
 'icon-chevron-sign-down',
 'icon-chevron-sign-left',
 'icon-chevron-sign-right',
 'icon-chevron-sign-up',
 'icon-chevron-up',
 'icon-circle-arrow-down',
 'icon-circle-arrow-left',
 'icon-circle-arrow-right',
 'icon-circle-arrow-up',
 'icon-double-angle-down',
 'icon-double-angle-left',
 'icon-double-angle-right',
 'icon-double-angle-up',
 'icon-hand-down',
 'icon-hand-left',
 'icon-hand-right',
 'icon-hand-up',
 'icon-long-arrow-down',
 'icon-long-arrow-left',
 'icon-long-arrow-right',
 'icon-long-arrow-up',
 'icon-backward',
 'icon-eject',
 'icon-fast-backward',
 'icon-fast-forward',
 'icon-forward',
 'icon-fullscreen',
 'icon-pause',
 'icon-play',
 'icon-play-circle',
 'icon-play-sign',
 'icon-resize-full',
 'icon-resize-small',
 'icon-backward',
 'icon-step-forward',
 'icon-stop',
 'icon-youtube-play',
 'icon-ambulance',
 'icon-h-sign',
 'icon-hospital',
 'icon-medkit',
 'icon-plus-sign-alt',
 'icon-stethoscope',
 'icon-user-md',




        );

      return str_replace ($oldclasses ,$newclasses ,$value);



    }

}
new FontAwesomeMigrateHelper();
