<?php if ( ! defined( 'ABSPATH' ) ) {
	die( 'Cheatin&#8217; uh?' );
}

/* ==========================================================================
	Available AddThis Services
============================================================================= */

if( ! function_exists( 'shiroi_addthis_services' ) ):

function shiroi_addthis_services() {
	return array(
		'facebook_like', 
		'foursquare', 
		'google_plusone', 
		'tweet', 
		'pinterest', 
		'compact', 
		'100zakladok', 
		'2tag', 
		'2linkme', 
		'a97abi', 
		'addressbar', 
		'adfty', 
		'adifni', 
		'advqr', 
		'amazonwishlist', 
		'amenme', 
		'aim', 
		'aolmail', 
		'apsense', 
		'arto', 
		'azadegi', 
		'baang', 
		'baidu', 
		'balltribe', 
		'beat100', 
		'biggerpockets', 
		'bitly', 
		'bizsugar', 
		'bland', 
		'blinklist', 
		'blogger', 
		'bloggy', 
		'blogkeen', 
		'blogmarks', 
		'blurpalicious', 
		'bobrdobr', 
		'bonzobox', 
		'socialbookmarkingnet', 
		'bookmarkycz', 
		'bookmerkende', 
		'box', 
		'brainify', 
		'bryderi', 
		'buddymarks', 
		'buffer', 
		'buzzzy', 
		'camyoo', 
		'care2', 
		'foodlve', 
		'chiq', 
		'cirip', 
		'citeulike', 
		'classicalplace', 
		'cleanprint', 
		'cleansave', 
		'cndig', 
		'colivia', 
		'technerd', 
		'cosmiq', 
		'cssbased', 
		'curateus', 
		'delicious', 
		'digaculturanet', 
		'digg', 
		'diggita', 
		'digo', 
		'diigo', 
		'domelhor', 
		'dotnetshoutout', 
		'douban', 
		'draugiem', 
		'dropjack', 
		'dudu', 
		'dzone', 
		'efactor', 
		'ekudos', 
		'elefantapl', 
		'email', 
		'mailto', 
		'embarkons', 
		'evernote', 
		'extraplay', 
		'ezyspot', 
		'stylishhome', 
		'fabulously40', 
		'facebook', 
		'informazione', 
		'thefancy', 
		'fark', 
		'farkinda', 
		'fashiolista', 
		'favable', 
		'faves', 
		'favlogde', 
		'favoritende', 
		'favorites', 
		'favoritus', 
		'financialjuice', 
		'flaker', 
		'flipboard', 
		'folkd', 
		'formspring', 
		'thefreedictionary', 
		'fresqui', 
		'friendfeed', 
		'funp', 
		'fwisp', 
		'gamekicker', 
		'gg', 
		'giftery', 
		'gigbasket', 
		'givealink', 
		'gmail', 
		'govn', 
		'goodnoows', 
		'google', 
		'googleplus', 
		'googletranslate', 
		'google_plusone_share', 
		'greaterdebater', 
		'hackernews', 
		'hatena', 
		'gluvsnap', 
		'hedgehogs', 
		'historious', 
		'hootsuite', 
		'hotklix', 
		'hotmail', 
		'w3validator', 
		'identica', 
		'ihavegot', 
		'indexor', 
		'instapaper', 
		'iorbix', 
		'irepeater', 
		'isociety', 
		'iwiw', 
		'jamespot', 
		'jappy', 
		'jolly', 
		'jumptags', 
		'kaboodle', 
		'kaevur', 
		'kaixin', 
		'ketnooi', 
		'kindleit', 
		'kledy', 
		'kommenting', 
		'latafaneracat', 
		'librerio', 
		'lidar', 
		'linkedin', 
		'linksgutter', 
		'linkshares', 
		'linkuj', 
		'livejournal', 
		'lockerblogger', 
		'logger24', 
		'mymailru', 
		'margarin', 
		'markme', 
		'mashant', 
		'mashbord', 
		'me2day', 
		'meinvz', 
		'mekusharim', 
		'memonic', 
		'memori', 
		'mendeley', 
		'meneame', 
		'live', 
		'misterwong', 
		'misterwong_de', 
		'mixi', 
		'moemesto', 
		'moikrug', 
		'mrcnetworkit', 
		'myspace', 
		'myvidster', 
		'n4g', 
		'naszaklasa', 
		'netlog', 
		'netvibes', 
		'netvouz', 
		'newsmeback', 
		'newstrust', 
		'newsvine', 
		'nujij', 
		'odnoklassniki_ru', 
		'oknotizie', 
		'openthedoor', 
		'oyyla', 
		'packg', 
		'pafnetde', 
		'pdfonline', 
		'pdfmyurl', 
		'phonefavs', 
		'pinterest_share', 
		'planypus', 
		'plaxo', 
		'plurk', 
		'pocket', 
		'posteezy', 
		'print', 
		'printfriendly', 
		'pusha', 
		'qrfin', 
		'qrsrc', 
		'quantcast', 
		'qzone', 
		'reddit', 
		'rediff', 
		'redkum', 
		'researchgate', 
		'safelinking', 
		'scoopat', 
		'scoopit', 
		'sekoman', 
		'select2gether', 
		'shaveh', 
		'shetoldme', 
		'sinaweibo', 
		'skyrock', 
		'smiru', 
		'sodahead', 
		'sonico', 
		'spinsnap', 
		'yiid', 
		'springpad', 
		'startaid', 
		'startlap', 
		'storyfollower', 
		'studivz', 
		'stuffpit', 
		'stumbleupon', 
		'stumpedia', 
		'sulia', 
		'sunlize', 
		'supbro', 
		'surfingbird', 
		'svejo', 
		'symbaloo', 
		'taaza', 
		'tagza', 
		'tapiture', 
		'taringa', 
		'textme', 
		'thewebblend', 
		'thinkfinity', 
		'thisnext', 
		'thrillon', 
		'throwpile', 
		'toly', 
		'topsitelernet', 
		'transferr', 
		'tuenti', 
		'tulinq', 
		'tumblr', 
		'tvinx', 
		'twitter', 
		'twitthis', 
		'typepad', 
		'upnews', 
		'urlaubswerkde', 
		'viadeo', 
		'virb', 
		'visitezmonsite', 
		'vk', 
		'vkrugudruzei', 
		'voxopolis', 
		'vybralisme', 
		'wanelo', 
		'internetarchive', 
		'sharer', 
		'webnews', 
		'webshare', 
		'werkenntwen', 
		'whatsapp', 
		'domaintoolswhois', 
		'windows', 
		'wirefan', 
		'wishmindr', 
		'wordpress', 
		'wowbored', 
		'raiseyourvoice', 
		'wykop', 
		'xanga', 
		'xing', 
		'yahoobkm', 
		'yahoomail', 
		'yammer', 
		'yardbarker', 
		'yigg', 
		'yookos', 
		'yoolink', 
		'yorumcuyum', 
		'youmob', 
		'yuuby', 
		'zakladoknet', 
		'ziczac', 
		'zingme'
	);
}
endif;

/* ==========================================================================
	Output AddThis Sharing Button
============================================================================= */

if( ! function_exists( 'shiroi_sharing_button' ) ):

function shiroi_sharing_button( $button ) {

	$config = array(
		'facebook_like' => array(
			'fb:like:layout' => 'button_count'
		), 
		'tweet' => array(
			'tw:count' => 'none'
		), 
		'google_plusone' => array(
			'g:plusone:size' => 'medium', 
			'g:plusone:count' => 'false'
		)
	);

	if( in_array( $button, shiroi_addthis_services() ) ) {
		$html = '<a class="addthis_button_' . $button . '"';
		if( array_key_exists( $button, $config ) && is_array( $config[ $button ] ) ) {
			foreach( $config[ $button ] as $key => $value ) {
				$value = esc_attr( $value );
				$html .= " {$key}=\"{$value}\"";
			}
		}
		echo $html . '></a>';
	}
}
endif;
