<?php
/**
 * Handles Design Settings page
 *
 * Since PrimaThemes 2.0, design settings page use Wordpress Customizer page.
 *
 * WARNING: This file is part of the core PrimaThemes framework.
 * DO NOT edit this file under any circumstances. 
 *
 * @category   PrimaThemes
 * @package    Framework
 * @subpackage Admin
 * @author     PrimaThemes
 * @link       http://www.primathemes.com
 */

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

/**
 * Add Design Settings page.
 *
 * @since PrimaThemes 2.0
 */
add_action( 'admin_menu', 'prima_design_settings_init' );
function prima_design_settings_init() {
	global $_prima;
	$_prima->design_settings = add_theme_page( __( 'Design Settings', 'primathemes' ), __( 'Design Settings', 'primathemes' ), apply_filters( "prima_settings_capability", 'edit_theme_options' ), 'customize.php' );
}

/**
 * Reset Design Settings Tab
 *
 * @since PrimaThemes 2.0
 */
add_action( 'prima-theme-settings-form-after', 'prima_design_settings_form_reset' );
function prima_design_settings_form_reset() {
	?>
	<div class="prima-settings-section prima-settings-tab-settings">
		
		<br/>
		<table class="widefat" cellspacing="0">
		<thead><tr><th><?php _e('Reset Design Settings', 'primathemes'); ?></th></tr></thead>
		<tbody>
		<tr><td>
			<p><?php _e('You can reset theme customizer (design settings) value.', 'primathemes'); ?></p>
			<p>
				<form enctype="multipart/form-data" method="post" action="<?php echo add_query_arg( array( 'page' => 'primathemes' ), admin_url( 'themes.php' ) ); ?>">
					<?php wp_nonce_field('primathemes-design-reset'); ?>
					<input type="hidden" name="primathemes-design-reset" value="1" />
					<input type="submit" class="button button-primary" value="<?php _e('Reset Design Settings', 'primathemes'); ?>" />
				</form>
			</p>
		</td></tr>
		</tbody>
		</table>
		
	</div>
	<?php
}

/**
 * Reset Design Settings value
 *
 * @since PrimaThemes 2.0
 */
add_action( 'admin_init', 'prima_design_settings_reset' );
function prima_design_settings_reset() {
	if ( !isset($_REQUEST['page']) || $_REQUEST['page'] != 'primathemes' )
		return;
	if ( empty( $_REQUEST['primathemes-design-reset'] ) )
		return;
	check_admin_referer('primathemes-design-reset');
	update_option( PRIMA_DESIGN_SETTINGS, prima_design_settings_default() );
	wp_redirect( add_query_arg( array( 'page' => 'primathemes', 'design-settings-reset' => 'true' ), admin_url( 'themes.php' ) ) );
	exit;
}

/**
 * Reset Design Settings Message
 *
 * @since PrimaThemes 2.0
 */
add_action( 'prima-theme-settings-form-before', 'prima_design_settings_reset_message' );
function prima_design_settings_reset_message() {
	if ( !isset($_REQUEST['settings-updated']) ) {  
		if ( isset($_REQUEST['design-settings-reset']) && $_REQUEST['design-settings-reset'] == 'true') {  
			echo '<div id="message" class="updated fade"><p><strong>'.__('Design settings is successfully resetted.', 'primathemes').'</strong></p></div>';
			if ( current_theme_supports('prima-design-settings') && function_exists('prima_design_settings_generate_output') ) {
				update_option( PRIMA_DESIGN_SETTINGS.'_output_expire', 'yes' );
				prima_design_settings_generate_output();
			}
		}
	}
}

/**
 * Save custom background settings to Design Settings database
 *
 * @since PrimaThemes 2.0
 */
add_action( 'load-appearance_page_custom-background', 'prima_design_settings_custombackground_save', 99 );
function prima_design_settings_custombackground_save() {
	if ( !isset($_REQUEST['page']) || $_REQUEST['page'] != 'custom-background' )
		return;
		
	$option = (array) get_option( PRIMA_DESIGN_SETTINGS );
	
	$option['background_image'] = get_theme_mod( 'background_image' );
	$option['background_color'] = get_theme_mod( 'background_color' );
	$option['background_repeat'] = get_theme_mod( 'background_repeat' );
	$option['background_position_x'] = get_theme_mod( 'background_position_x' );	
	$option['background_attachment'] = get_theme_mod( 'background_attachment' );
	
	update_option( PRIMA_DESIGN_SETTINGS, $option );
}

/**
 * Import custom background settings when importing Design Settings
 *
 * @since PrimaThemes 2.0
 */
function prima_design_settings_custombackground_import() {
	$option = (array) get_option( PRIMA_DESIGN_SETTINGS );
	if ( isset( $option['background_image'] ) )
		set_theme_mod( 'background_image', $option['background_image'] );
	if ( isset( $option['background_color'] ) )
		set_theme_mod( 'background_color', $option['background_color'] );
	if ( isset( $option['background_repeat'] ) )
		set_theme_mod( 'background_repeat', $option['background_repeat'] );
	if ( isset( $option['background_position_x'] ) )
		set_theme_mod( 'background_position_x', $option['background_position_x'] );	
	if ( isset( $option['background_attachment'] ) )
		set_theme_mod( 'background_attachment', $option['background_attachment'] );
}

/**
 * Import style (full/boxed/custom) settings when importing Design Settings
 *
 * @since PrimaThemes 2.0
 */
function prima_design_settings_style_import() {
	$theme_settings = (array) get_option( PRIMA_THEME_SETTINGS );
	$design_settings = (array) get_option( PRIMA_DESIGN_SETTINGS );
	if ( isset( $design_settings['style'] ) ) {
		$theme_settings['style'] = $design_settings['style'];
		update_option( PRIMA_THEME_SETTINGS, $theme_settings );
	}
}
