<?php
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(564, 'pp_logo_margin_left', '0', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(565, 'pp_logo_margin_top', '0', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(566, 'pp_enable_right_click', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(567, 'pp_right_click_text', 'You can enable/disable right click protection using theme admin', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(569, 'pp_font', 'Yanone+Kaffeesatz', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(570, 'pp_h1_size', '40', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(571, 'pp_h2_size', '32', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(572, 'pp_h3_size', '26', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(573, 'pp_h4_size', '24', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(574, 'pp_h5_size', '22', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(575, 'pp_h6_size', '18', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(576, 'pp_menu_font_size', '12', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(577, 'pp_submenu_font_size', '12', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(578, 'pp_font_color', '#3d3d3d', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(579, 'pp_frame_color', '#000000', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(580, 'pp_content_color', '#ffffff', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(581, 'pp_content_opacity_color', '100', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(582, 'pp_link_color', '#000000', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(583, 'pp_hover_link_color', '#636363', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(584, 'pp_h1_font_color', '#000000', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(585, 'pp_button_bg_color', '#000000', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(586, 'pp_button_font_color', '#ffffff', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(587, 'pp_button_border_color', '#000000', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(588, 'pp_menu_font_color', '#999999', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(589, 'pp_active_menu_font_color', '#ffffff', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(593, 'pp_homepage_style', 'flow', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(594, 'pp_homepage_slideshow_cat', '20', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(595, 'pp_homepage_slideshow_timer', '5', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(596, 'pp_homepage_slideshow_trans', '1', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(597, 'pp_enable_fit_image', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(598, 'pp_portfolio_slideshow_timer', '5', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(599, 'pp_portfolio_slideshow_trans', '1', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(600, 'pp_portfolio_enable_fit_image', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(601, 'pp_enable_reflection', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(604, 'pp_contact_form', 's:8:\"s:1:\"1\";\";', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(605, 'pp_facebook_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(606, 'pp_twitter_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(607, 'pp_google_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(608, 'pp_flickr_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(609, 'pp_youtube_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(610, 'pp_vimeo_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(611, 'pp_tumblr_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(612, 'pp_digg_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(613, 'pp_dribbble_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(614, 'pp_linkedin_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(615, 'pp_pinterest_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(616, 'pp_footer_text', 'You can change this footer text using Theme Setting > Footer', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(617, 'pp_footer_social', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(620, 'pp_font_family', 'Yanone Kaffeesatz', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(624, 'pp_contact_form_sort_data', 's:42:\"a:3:{i:0;s:1:\"1\";i:1;s:1:\"2\";i:2;s:1:\"3\";}\";', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(625, 'pp_enable_responsive', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(626, 'pp_portfolio_enable_gallery_info', 'true', 'yes');");
?>