<?php
$colored_color_background = array(
    0 => '.pace .pace-progress',
    1 => ' .progress-bar.progress-theme',
    2 => 'input[type="submit"]',
    3 => ' #content-container #buddypress input[type="submit"]',
    4 => ' #buddypress #create-group-form input[type="button"]',
    5 => ' #content-container #bbpress-forums button[type="submit"]',
    6 => ' #right-sidebar .widget .intern-box.box-title::after',
    7 => '#nav-sidebar-trigger:hover',
    8 => '.widget.widget_search button',
    9 => ' #content-container .heading::before',
    10 => ' .widget_recent_entries .post-date',
    11 => ' #content-container div.item-list-tabs#subnav ul li.current a',
    12 => ' div.activity-meta a',
    13 => ' #main-content #buddypress div.generic-button a',
    14 => ' #buddypress .comment-reply-link',
    15 => 'a.bp-title-button',
    16 => ' .progress-bar',
    17 => ' #content-container #buddypress .button-nav li a',
    18 => ' #dashboard .widget .box-title::after',
    19 => ' #content-container .masonry-layout .box .box-title::after',
    20 => ' #content-container #buddypress button',
    21 => ' #buddypress ul#members-list li div.item-avatar span.member-role',
    22 => ' #content-container .mv-btn-success',
    23 => ' #content-container td.publish',
    24 => ' #content-container .mv-addfile-wrap a',
    25 => ' #content-container .mv-submitfields button',
    26 => ' #page-wrapper .wcContainer .wcMessage.wcCurrentUserMessage .wcMessageContent',
    27 => ' #content-container #bp-browse-button',
    28 => ' .gantt',
    29 => '.gantt-day.weekend span',
    30 => ' .bbp-topic-tags a',
    31 => ' #content #eventon_form p #evoau_submit',
    32 => ' #content-container .mv-btn-success',
    33 => '#content-container td.publish',
    34 => ' #content-container .mv-addfile-wrap a',
    35 => '#content-container .mv-submitfields button',
    36 => ' #content-container div.item-list-tabs ul li.current a',
    37 => ' .wiki-like-container p.wiki-like.voted',
    38 => ' #content-container .badgeos-item-points:before',
    39 => ' #learndash_next_prev_link a',
    40 => ' #content-container .ssfa_fileup_wrapper span',
    41 => ' #buddypress div.pagination .pagination-links span',
    42 => ' #buddypress div.pagination .pagination-links a',
    43 => ' #rtmedia_create_new_album',
    44 => ' #dashboard .widget .box-title h3:before',
    45 => ' #dashboard .widget .box-title h3:after',
    46 => ' #dashboard .widget.evoFC_Widget h3.widget-title:before',
    47 => ' #dashboard .widget.evoFC_Widget h3.widget-title:after',
    48 => '#content-container #buddypress .dataTables_wrapper .dataTables_paginate .paginate_button:not(.disabled)',
    49 => '#dashboard.is-draggie .widget .widget-drag-button'
);