<?php
$color_notifications_array = array(
    0 => '#user-thumb .notifications',
    1 => ' #user-sidebar nav ul li a span.count',
    2 => '#user-sidebar nav ul li a span.no-count',
    3 => ' #featuredbox.has-search form button',
    4 => ' #featuredbox.has-search form input[type="submit"]',
    5 => ' #content-container div.item-list-tabs ul li.current a span.no-count',
    6 => ' #content-container div.item-list-tabs ul li.current a span.count',
    7 => ' #content-container div.item-list-tabs ul li.current a span',
    8 => ' #content-container div.item-list-tabs ul li.selected a span',
    9 => ' #content-container div.item-list-tabs-wiki ul li.active a span',
    10 => ' #content-container div.item-list-tabs-project ul li.active a span',
    11 => ' #content-container div.item-list-tabs ul li a span.no-count',
    12 => ' #content-container div.item-list-tabs ul li a span.count',
    13 => ' #content-container div.item-list-tabs ul li a span',
    14 => ' #content-container div.item-list-tabs-wiki ul li a span',
    15 => ' #content-container div.item-list-tabs-project ul li a span',
    16 => ' #buddypress a.bp-primary-action span',
    17 => ' #buddypress #reply-title small a span',
    18 => ' #buddypress div#message.error',
    19 => ' #content-container div.wpcf7-validation-errors',
    20 => ' #buddypress div#message.error:hover',
    21 => ' #nav-notification-trigger.active:after',
    22 => ' .notification-color',
);