<?php
$color_light1_color = array(
    0 => '#content-container .intern-box',
    1 => ' #user-sidebar nav ul li a:hover',
    2 => ' .wcContainer .wcMessages .wcMessage .wcMessageContent',
    3 => ' #buddypress table.notifications thead tr',
    4 => ' #buddypress table.notifications-settings thead tr',
    5 => ' #buddypress table.profile-settings thead tr',
    6 => ' #buddypress table.profile-fields thead tr',
    7 => ' #buddypress table.wp-profile-fields thead tr',
    8 => ' #buddypress table.messages-notices thead tr',
    9 => ' #buddypress table.forum thead tr',
    10 => ' #bbpress-forums li.bbp-header',
    11 => ' form .woffice-task .todo-note',
    12 => ' #content-container article.content.type-sfwd-quiz .intern-padding.heading-container:after',
    13 => ' #content-container article.content.type-sfwd-courses .intern-padding.heading-container:after',
    14 => ' #content-container article.content.type-sfwd-lessons .intern-padding.heading-container:after',
    15 => ' #content-container article.content.type-sfwd-transactions .intern-padding.heading-container:after',
    16 => ' #content-container article.content.type-sfwd-certificates .intern-padding.heading-container:after',
    17 => ' #content-container article.content.type-multiverso .intern-padding.heading-container:after',
    18 => ' #content-container article.content.type-sfwd-topic .intern-padding.heading-container:after',
    19 => ' #buddypress .rtm-media-single-comments',
    20 => ' #buddypress .rtmedia-like-info',
    21 => '#buddypress .rtmedia-comments-container',
    22 => ' #buddypress .rtm-comment-list li',
);