<?php
$colored_background_important = array(
    0 => '#wp-submit',
    1 => '.progress-bar',
    2 => '#page-wrapper .wcContainer .wcMessage.wcCurrentUserMessage .wcMessageContent',
    3 => ' input[type="submit"]',
    4 => 'button[type="submit"]',
    5 => '#content-container div.item-list-tabs ul li.selected a',
    6 => ' #main-content .bbb-join input[type=submit]',
    7 => ' .btn.btn-default',
    8 => '#buddypress ul#members-list li div.item-avatar span.member-role',
    9 => ' #main-content span.label',
    10 => ' #main-footer span.label',
    11 => ' #main-content #buddypress a.button',
    12 => ' #content-container div.item-list-tabs-project ul li.active a',
    13 => ' #main-content #buddypress div.generic-button a',
    14 => ' #content-container div.item-list-tabs ul li.selected a',
    15 => ' #content-container div.item-list-tabs-wiki ul li.active a',
    16 => ' #content-container div.item-list-tabs-project ul li.active a',
    17 => ' #content-container div.item-list-tabs ul li.selected a',
    18 => ' #content-container div.item-list-tabs-wiki ul li.active a',
    19 => ' #content-container div.item-list-tabs ul li.current a',
    20 => ' #main-content #buddypress ul.button-nav li a',
    21 => ' .woocommerce span.onsale',
    22 => ' .woocommerce #content-container #respond input#submit:hover',
    23 => ' .woocommerce #content-container a.button:hover',
    24 => ' #content-container .woocommerce button.button:hover',
    25 => ' .woocommerce #content-container #respond input#submit',
    26 => ' .woocommerce #content-container a.button',
    27 => ' .woocommerce #content-container button.button',
    28 => ' .woocommerce #content-container input.button',
    29 => ' #content-container .woocommerce input.button:hover',
    30 => ' #main-content input[type="button"]',
    31 => ' #buddypress input[type=button]:hover',
    32 => ' .woocommerce #content-container nav.woocommerce-pagination ul li a',
    33 => ' .woocommerce #content-container div.product p.price .amount',
    34 => ' #nav-cart-trigger .amount',
    35 => ' #content-container .woocommerce a.button',
    36 => ' .woocommerce #respond input#submit.alt',
    37 => ' .woocommerce a.button.alt',
    38 => ' .woocommerce button.button.alt',
    39 => ' .woocommerce input.button.alt',
    40 => ' .woocommerce #respond input#submit.alt:hover',
    41 => ' .woocommerce a.button.alt:hover',
    42 => ' .woocommerce button.button.alt:hover',
    43 => ' .woocommerce input.button.alt:hover',
    44 => ' #right-sidebar .buttons a',
    45 => ' .woocommerce .widget_price_filter .ui-slider .ui-slider-handle',
    46 => ' .woocommerce .widget_price_filter .ui-slider .ui-slider-range',
    47 => ' .woocommerce-shortcode .woocommerce .flex-direction-nav a',
    48 => ' .it-exchange-product-price ins',
);