<?php
	$absolute_path = __FILE__;
	$path_to_file = explode( 'wp-content', $absolute_path );
	$path_to_wp = $path_to_file[0];
	require_once( $path_to_wp.'/wp-load.php' );

	$dt_sliderType = $_GET['type'];
	switch($dt_sliderType) {
		case 'content-slider':
			$dt_SliderContentAutoplay = get_option('dt_SliderContentAutoplay','false');
			$dt_SliderContentPause = get_option('dt_SliderContentPause','3000');
			$dt_SliderContentSpeed = get_option('dt_SliderContentSpeed','500');
			echo '$(document).ready(function($) {'."\n";
				echo '$(window).bind("load", function() {'."\n";
					echo '$("#content-slider ul.content-slider-elements").bxSlider({'."\n";
						echo 'mode:"fade",'."\n";
						echo 'speed:'.$dt_SliderContentSpeed.','."\n";
						echo 'auto:'.$dt_SliderContentAutoplay.','."\n";
						echo 'autoHover: true,'."\n";
						echo 'pause:'.$dt_SliderContentPause."\n";
					echo '});'; 					
				echo '});';												        
            echo '});';
    	break;
		case 'complex-slider':
			$dt_SliderComplexHeight = get_option('dt_SliderComplexHeight','378');
			$dt_SliderComplexAutoAdvance = get_option('dt_SliderComplexAutoAdvance','true');			
			$dt_SliderComplexDuration = get_option('dt_SliderComplexDuration','600');
			$dt_SliderComplexInterval = get_option('dt_SliderComplexInterval','5000');
			$dt_SliderComplexPauseOnHover = get_option('dt_SliderComplexPauseOnHover','true');
			$dt_SliderComplexArrows = get_option('dt_SliderComplexArrows','true');	
			$dt_SliderComplexTimer = get_option('dt_SliderComplexTimer','true');	
			$dt_SliderComplexDescription = get_option('dt_SliderComplexDescription','true');
			$dt_SliderComplexGallery = get_option('dt_SliderComplexGallery','true');
			$dt_SliderComplexIcon = get_option('dt_SliderComplexIcon','true');										
			echo "$(document).ready(function($) {"."\n";
				echo "$(window).bind(\"load\", function() {"."\n";
					echo "$('.dt_complexslider').dtComplexSlider({"."\n";
						echo "'height': ".$dt_SliderComplexHeight.","."\n";
						echo "'autoAdvance': ".$dt_SliderComplexAutoAdvance.","."\n";
						echo "'autoAdvDuration': ".$dt_SliderComplexDuration.","."\n";
						echo "'autoAdvInterval': ".$dt_SliderComplexInterval.","."\n";
						echo "'autoAdvPauseOnHover': ".$dt_SliderComplexPauseOnHover.","."\n";
						echo "'showArrows': ".$dt_SliderComplexArrows.","."\n";
						echo "'showTimer': ".$dt_SliderComplexTimer.","."\n";
						echo "'showDescription': ".$dt_SliderComplexDescription.","."\n";
						echo "'showGallery': ".$dt_SliderComplexGallery.","."\n";
						echo "'showIcon': '.$dt_SliderComplexIcon.'"."\n";				
					echo "});"."\n";
				echo "});"."\n";			        
			echo "});"."\n";
    	break;
		case 'presentation-slider':	
			$dt_SliderPresentationHeight = get_option('dt_SliderPresentationHeight','300');
			$dt_SliderPresentationAutoAdvance = get_option('dt_SliderPresentationAutoAdvance','true');			
			$dt_SliderPresentationDuration = get_option('dt_SliderPresentationDuration','600');
			$dt_SliderPresentationInterval = get_option('dt_SliderPresentationInterval','5000');
			$dt_SliderPresentationPauseOnHover = get_option('dt_SliderPresentationPauseOnHover','true');
			$dt_SliderPresentationArrows = get_option('dt_SliderPresentationArrows','true');	
			$dt_SliderPresentationTimer = get_option('dt_SliderPresentationTimer','true');
			$dt_SliderPresentationIcon = get_option('dt_SliderPresentationIcon','true');
			$dt_SliderPresentationGallery = get_option('dt_SliderPresentationGallery','true');
			$dt_SliderPresentationGalleryNumber = get_option('dt_SliderPresentationGalleryNumber','true');										
			$dt_SliderPresentationGalleryTitle = get_option('dt_SliderPresentationGalleryTitle','true');			
			$dt_SliderPresentationScroll = get_option('dt_SliderPresentationScroll','true');						
			$dt_SliderPresentationKeybordControl = get_option('dt_SliderPresentationKeybordControl','true');						
			$dt_SliderPresentationDescription = get_option('dt_SliderPresentationDescription','true');						
			$dt_SliderPresentationDescriptionAutoHide = get_option('dt_SliderPresentationDescriptionAutoHide','false');									

			echo "$(document).ready(function($) {"."\n";
				echo "$(window).bind(\"load\", function() {"."\n";				
					echo "$('.dt_presentationslider').dtPresentationSlider({"."\n";
						echo "'height': ".$dt_SliderPresentationHeight.","."\n";
						echo "'autoAdvance': ".$dt_SliderPresentationAutoAdvance.","."\n";
						echo "'autoAdvDuration': ".$dt_SliderPresentationDuration.","."\n";
						echo "'autoAdvInterval': ".$dt_SliderPresentationInterval.","."\n";
						echo "'autoAdvPauseOnHover': ".$dt_SliderPresentationPauseOnHover.","."\n";
						echo "'showArrows': ".$dt_SliderPresentationArrows.","."\n";
						echo "'showTimer': ".$dt_SliderPresentationTimer.","."\n";
						echo "'showIcon': ".$dt_SliderPresentationIcon.","."\n";						
						echo "'showGallery': ".$dt_SliderPresentationGallery.","."\n";
						echo "'showGalleryNumber': ".$dt_SliderPresentationGalleryNumber.","."\n";
						echo "'showGalleryTitle': ".$dt_SliderPresentationGalleryTitle.","."\n";
						echo "'showScroll': ".$dt_SliderPresentationScroll.","."\n";
						echo "'keyboardControl': ".$dt_SliderPresentationKeybordControl.","."\n";
						echo "'autoHideDescription': ".$dt_SliderPresentationDescriptionAutoHide.","."\n";						
						echo "'showDescription': ".$dt_SliderPresentationDescription."\n";
					echo "});"."\n";
				echo "});"."\n";			        
			echo "});"."\n";
		break;				 		
		case 'fullwidth-slider':
			$dt_SliderFullWidthHeight = get_option('dt_SliderFullWidthHeight','500');
			$dt_SliderFullWidthAutoAdvance = get_option('dt_SliderFullWidthAutoAdvance','true');			
			$dt_SliderFullWidthDuration = get_option('dt_SliderFullWidthDuration','600');
			$dt_SliderFullWidthInterval = get_option('dt_SliderFullWidthInterval','5000');	
			$dt_SliderFullWidthPauseOnHover = get_option('dt_SliderFullWidthPauseOnHover','true');
			$dt_SliderFullWidthArrows = get_option('dt_SliderFullWidthArrows','true');
			$dt_SliderFullWidthArrowsAutohide = get_option('dt_SliderFullWidthArrowsAutohide','true');			
			$dt_SliderFullWidthKeybordControls = get_option('dt_SliderFullWidthKeybordControls','true');
			$dt_SliderFullWidthGallery = get_option('dt_SliderFullWidthGallery','true');
			$dt_SliderFullWidthGalleryAutohide = get_option('dt_SliderFullWidthGalleryAutohide','true');			
			$dt_SliderFullWidthTitle = get_option('dt_SliderFullWidthTitle','true');
			$dt_SliderFullWidthTitleAlign = get_option('dt_SliderFullWidthTitleAlign','left');
			$dt_SliderFullWidthDescription = get_option('dt_SliderFullWidthDescription','true');
			$dt_SliderFullWidthDescBoxWidth = get_option('dt_SliderFullWidthDescBoxWidth','480');
			$dt_SliderFullWidthDescBoxHeight = get_option('dt_SliderFullWidthDescBoxHeight','220');											
			$dt_SliderFullWidthTimer = get_option('dt_SliderFullWidthTimer','true');
			$dt_SliderFullWidthIcon = get_option('dt_SliderFullWidthIcon','true');
			$dt_SliderFullWidthHelpBox = get_option('dt_SliderFullWidthHelpBox','true');
			$dt_SliderFullWidthHelpBoxContent = get_option('dt_SliderFullWidthHelpBoxContent','Press the left and right keys on your keyboard to browse through the images.');
			echo "$(document).ready(function($) {"."\n";
				echo "$(window).bind(\"load\", function() {"."\n";
					echo "$('.dt_fullwidthslider').dtFullWidthSlider({"."\n";
						echo "'height': ".$dt_SliderFullWidthHeight.","."\n";
						echo "'autoAdvance': ".$dt_SliderFullWidthAutoAdvance.","."\n";
						echo "'autoAdvDuration': ".$dt_SliderFullWidthDuration.","."\n";
						echo "'autoAdvInterval': ".$dt_SliderFullWidthInterval.","."\n";
						echo "'autoAdvPauseOnHover': ".$dt_SliderFullWidthPauseOnHover.","."\n";
						echo "'showArrows': ".$dt_SliderFullWidthArrows.","."\n";
						echo "'keyboardControl': ".$dt_SliderFullWidthKeybordControls.","."\n";
						echo "'autoHideArrows': ".$dt_SliderFullWidthArrowsAutohide.","."\n";
						echo "'showGallery': ".$dt_SliderFullWidthGallery.","."\n";
						echo "'autoHideGallery': ".$dt_SliderFullWidthGalleryAutohide.","."\n";
						echo "'showTitles': ".$dt_SliderFullWidthTitle.","."\n";
						echo "'titlesAlign': '".$dt_SliderFullWidthTitleAlign."',"."\n";
						echo "'showDescription': ".$dt_SliderFullWidthDescription.","."\n";
						echo "'descBoxWidth':".$dt_SliderFullWidthDescBoxWidth.","."\n";
						echo "'descBoxHeight':".$dt_SliderFullWidthDescBoxHeight.","."\n";
						echo "'showTimer': ".$dt_SliderFullWidthTimer.","."\n";
						echo "'showIcon':  ".$dt_SliderFullWidthIcon.","."\n";
						echo "'helpBox': ".$dt_SliderFullWidthHelpBox.","."\n";
						echo "'helpBoxText': '".$dt_SliderFullWidthHelpBoxContent."'"."\n";
					echo "});"."\n";
				echo "});"."\n";			        
			echo "});"."\n";
    	break;
		case 'fullscreen-slider':
			$dt_SliderFullScreenHeight = get_option('dt_SliderFullScreenHeight','240');
			$dt_SliderFullScreenAutoAdvance = get_option('dt_SliderFullScreenAutoAdvance','true');			
			$dt_SliderFullScreenDuration = get_option('dt_SliderFullScreenDuration','600');
			$dt_SliderFullScreenInterval = get_option('dt_SliderFullScreenInterval','5000');	
			$dt_SliderFullScreenArrows = get_option('dt_SliderFullScreenArrows','true');
			$dt_SliderFullScreenGallery = get_option('dt_SliderFullScreenGallery','true');	
			$dt_SliderFullScreenDescription = get_option('dt_SliderFullScreenDescription','true');						
			$dt_SliderFullScreenKeybordControls = get_option('dt_SliderFullScreenKeybordControls','true');
			$dt_SliderFullScreenBgRepeat = get_option('dt_SliderFullScreenBgRepeat','no-repeat');
			$dt_SliderFullScreenBgPosition = get_option('dt_SliderFullScreenBgPosition','left top');                        
		
			echo "$(document).ready(function($) {"."\n";
				echo "$(window).bind(\"load\", function() {"."\n";
					echo "$('.dt_fullscreenslider').dtFullScreenSlider({"."\n";
						echo "'height': ".$dt_SliderFullScreenHeight.","."\n";
						echo "'autoAdvance': ".$dt_SliderFullScreenAutoAdvance.","."\n";
						echo "'autoAdvDuration': ".$dt_SliderFullScreenDuration.","."\n";
						echo "'autoAdvInterval': ".$dt_SliderFullScreenInterval.","."\n";
						echo "'showArrows': ".$dt_SliderFullScreenArrows.","."\n";
						echo "'keyboardControl': ".$dt_SliderFullScreenKeybordControls.","."\n";
						echo "'showGallery': ".$dt_SliderFullScreenGallery.","."\n";
						echo "'showDescription': ".$dt_SliderFullScreenDescription.","."\n";						
						echo "'bgPosition': '".$dt_SliderFullScreenBgPosition."',"."\n";
						echo "'bgRepeat': '".$dt_SliderFullScreenBgRepeat."'"."\n";
					echo "});"."\n";
				echo "});"."\n";			        
			echo "});"."\n";
    	break;
		
		case 'gallery-slider':
			$dt_SliderGalleryHeight = get_option('dt_SliderGalleryHeight','480');
			$dt_SliderGalleryHeightUnit = floor($dt_SliderGalleryHeight/3);
			$dt_SliderGalleryAutoAdvance = get_option('dt_SliderGalleryAutoAdvance','true');			
			$dt_SliderGalleryDuration = get_option('dt_SliderGalleryDuration','600');
			$dt_SliderGalleryInterval = get_option('dt_SliderGalleryInterval','5000');	
			$dt_SliderGalleryPauseOnHover = get_option('dt_SliderGalleryPauseOnHover','true');
			$dt_SliderGalleryArrows = get_option('dt_SliderGalleryArrows','true');
			$dt_SliderGalleryKeybordControls = get_option('dt_SliderGalleryKeybordControls','true');			
			$dt_SliderGalleryArrowsAutohide = get_option('dt_SliderGalleryArrowsAutohide','true');			
			$dt_SliderGalleryTimer = get_option('dt_SliderGalleryTimer','true');
			$dt_SliderGalleryScroll = get_option('dt_SliderGalleryScroll','true');
			$dt_SliderGalleryDescription = get_option('dt_SliderGalleryDescription','true');									
			echo "$(document).ready(function($) {"."\n";
				echo "$(window).bind(\"load\", function() {"."\n";
					echo "$('.dt_galleryslider').dtGallerySlider({"."\n";
						echo "'height': ".($dt_SliderGalleryHeightUnit*3).","."\n";
						echo "'autoAdvance': ".$dt_SliderGalleryAutoAdvance.","."\n";
						echo "'autoAdvDuration': ".$dt_SliderGalleryDuration.","."\n";
						echo "'autoAdvInterval': ".$dt_SliderGalleryInterval.","."\n";
						echo "'autoAdvPauseOnHover': ".$dt_SliderGalleryPauseOnHover.","."\n";
						echo "'showArrows': ".$dt_SliderGalleryArrows.","."\n";
						echo "'autoHideArrows': ".$dt_SliderGalleryArrowsAutohide.","."\n";
						echo "'showTimer': ".$dt_SliderGalleryTimer.","."\n";
						echo "'showScroll': ".$dt_SliderGalleryScroll.","."\n";
						echo "'keyboardControl': ".$dt_SliderGalleryKeybordControls.","."\n";
						echo "'showDescription': ".$dt_SliderGalleryDescription."\n";
					echo "});"."\n";
				echo "});"."\n";			        
			echo "});"."\n";
    	break;								
	}
?>